### ISSUE TITLE
PDFs don't open

### ISSUE THREAD

**Issue by stshank** [brave/brave-browser#1033]
## Description 
Some PDFs don't open

## Steps to Reproduce

   1. go to https://spark.att.com/5g-white-papers
   2. Click "white papers in upper right
   3. Click "download" buttons

## Actual result:
PDF won't display
Error message:
PDF.js v2.0.673 (build: 31012570)
Message: Failed to fetch

## Expected result:
PDF displays

## Reproduces how often: 
always

## Brave version (about:brave info) 
Version 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
MacOS Mojave beta 10

### Reproducible on current release:
Unknown

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
No
- Is the issue reproducible on the latest version of Chrome? 
No

**Comment by prakaashkpk** [comment]
I am able to open the PDF.js in my mac. but I am using pdf.js version bundled with my browser. 

```
Brave: 0.23.105 
PDF Viewer 1.9.459
OS Release: 17.7.0 
```

**Comment by hugobuddel** [comment]
Another one via https://github.com/brave/browser-laptop/issues/14674#issuecomment-425857997

chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://onlinelibrary.wiley.com/doi/pdf/10.1111/cdev.12853

It is especially annoying with pdf's that require login, because those can't be wget-ed either.

**Comment by oxfordia** [comment]
www.chase.com >> cannot open my monthly statements ("open as pdf") (CAN login and browse site)
www.ebay.com >> cannot open pdf of labels necessary to ship

CHASE.com ERROR:
PDF.js v2.0.673 (build: 31012570)
Message: Unexpected server response (401) while retrieving PDF "https://secure07a.chase.com/svc/rr/documents/secure/idal/v2/pdfdoc/star/list?docKey=c1f3b968-a0a3-4ffc-8581-59d290f89c4c&adaVersion=false&csrftoken=de8d4ad837215be586daa889dad7110098e4c9d45f7e971b74991f37bb6d5f64&download=false&fromOrigin=https%253A%252F%252Fsecure07a.chase.com".


Brave is up to date
Version 0.55.22 Chromium: 70.0.3538.77 (Official Build) (64-bit)

Does not matter if shields are up or down

**Comment by MJae** [comment]
Just encountered the same while trying to download a certificate from OpenLearn: "Invalid or corrupted PDF file."

Clicking on "More information" gives me this:
```
PDF.js v2.0.673 (build: 31012570)
Message: Invalid PDF structure
```

Download link worked without issue in Firefox Nightly 65.0a1

**Comment by srirambv** [comment]
+1 from @avndp via #2135

**Comment by jonathansampson** [comment]
@shriram Thank you for the feedback. If you have a couple URLs that can be shared, that would be helpful. I suspect there may be a couple scenarios represented here, and more data will certainly help to ensure all issues are addressed.

**Comment by shriram** [comment]
Right now all the ones I can think of were behind authentication barriers,
and they represent confidential information. I know that's frustrating to
hear!

But in the two most immediate cases I can think of — one a recommendation
letter upload, the other a pay stub viewing — the PDF viewing was
_embedded_ in a Web page, rather than shown in a stand-alone page. (The
latter, for instance, was inside the popular WorkDay system.) Whereas I
haven't seen the problem with ia stand-alone PDFs. For instance, I just now
went to
https://cs.brown.edu/~sk/Publications/Papers/Published/kf-prog-paradigms-and-beyond/paper.pdf,
which for me turned
into chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/
https://cs.brown.edu/~sk/Publications/Papers/Published/kf-prog-paradigms-and-beyond/paper.pdf,
and it works just fine.

So, conjecture: the problem is when a page tries to embed a PDF viewer.

I'll keep looking for counter-examples in both directions (it could be that
some embeddings work and others don't, so I'll keep an eye out for the page
contents).

**Comment by jonathansampson** [comment]
Internet `fetch` fails due to _no-cors_. This results in a `data:` request, which isn't permitted.

**Comment by hugobuddel** [comment]
Just summarizing, since this is the main reason I _have_ to use other browsers. Using Version 0.56.14 Chromium: 70.0.3538.102 (Official Build) unknown (64-bit)

> ## Steps to Reproduce
> 1. go to https://spark.att.com/5g-white-papers
> 2. Click "white papers in upper right
> 3. Click "download" buttons

This works properly now. 

> Another one via [brave/browser-laptop#14674 (comment)](https://github.com/brave/browser-laptop/issues/14674#issuecomment-425857997)
> 
> chrome-extension://oemmndcbldboiebfnladdacbdfmadadm/https://onlinelibrary.wiley.com/doi/pdf/10.1111/cdev.12853

This one seems to work properly as well.

> It is especially annoying with pdf's that require login, because those can't be wget-ed either.

Perhaps this is one of the main scenario's that is still failing?

> Right now all the ones I can think of were behind authentication barriers, and they represent confidential information.

Same for me. E.g. salary slips, so not possible to share/create an account. (I tried this several times on several computers / brave versions. Then I heard that some HR departments check how often people download their salary slip because this is an indication of employees wanting to leave :sweat_smile:.)

> But in the two most immediate cases I can think of — one a recommendation letter upload, the other a pay stub viewing — the PDF viewing was _embedded_ in a Web page, rather than shown in a stand-alone page. [..] So, conjecture: the problem is when a page tries to embed a PDF viewer.

Nice observation. This might be the problem with my salary slips too.

**Comment by shriram** [comment]
Agreed with @hugobuddel, this is the main reason I need another browser.

Unfortunately, his AT&T white paper example [https://developer.att.com/static-assets/documents/futurist-report/FuturistReport_5G-A-Faster-Smarter-Future_FINAL_083118.pdf] does _not_ work for me in 0.56.15 [build 70.0.3538.110] (slightly newer version than in his report). The PDF.js error message is
```
PDF.js v2.0.673 (build: 31012570)
Message: Failed to fetch
```
Since the above is a .pdf URL, it unfortunately provides a counterexample to my proposition that this is an issue with embedded PDFs only. (I downloaded the file to see whether there was some clever embedding trick being played, but it appears not.)

**Comment by hugobuddel** [comment]
Can confirm that indeed that https://developer.att.com/static-assets/documents/futurist-report/FuturistReport_5G-A-Faster-Smarter-Future_FINAL_083118.pdf does not work. Also not on the version I reported working. I'm quite sure it worked this morning; must have been mistaken.

**Comment by bbondy** [comment]
Thanks for your patience. Fix incoming.

**Comment by MJae** [comment]
Just got updated to Version 0.56.15 Chromium: 70.0.3538.110

Tested example: https://developer.att.com/static-assets/documents/futurist-report/FuturistReport_5G-A-Faster-Smarter-Future_FINAL_083118.pdf

Still doesn't work with error:
```
PDF.js v2.0.673 (build: 31012570)
Message: Failed to fetch
```

**Comment by oxfordia** [comment]
I can also confirm STILL does NOT work.

WAITING PATIENTLY for "Fix incoming"

**Comment by bbondy** [comment]
Fix is coded but not yet released. It's in the review phase right now.  It'll likely get approved within a day or so, and merge to Dev channel 0.58.x which will go to beta channel on Dec 4th and Release channel on Dec 20th. So earlier access on Beta and Dev channel.

**Comment by bbondy** [comment]
I'll try to get it uplifted to beta for release on Dec 4th.

**Comment by bbondy** [comment]
Regarding this one @hugobuddel: 
https://github.com/brave/browser-laptop/issues/14674#issuecomment-425857997

It's not a valid PDF URL, it's just a prefix to consider the URL as a PDF but the site is actually not a PDF at all: https://onlinelibrary.wiley.com/doi/pdf/10.1111/cdev.12853

**Comment by jsquyres** [comment]
Note that this issue seems to have regressed: in Brave 0.68.132, PDFs are downloading again instead of opening -- see #1264.

#1264 has sat in the "Untriaged / Incoming in Shields" project for quite a while.  Can someone please have a look?  Thanks!
