### ISSUE TITLE
Desktop sync v2 does not sync all tabs from other computers

### ISSUE THREAD

**Issue by snowbound** [brave/brave-browser#11183]
## Description 
When Sync is enabled in Version 1.13.66 Chromium: 84.0.4147.125 (Official Build) beta (64-bit) and prior builds and one has Open Tab sync enabled you see a maximum of 4 tabs from other devices under History flyout for that particular computer.

## Steps to Reproduce

   1. Enable Sync on main computer
   2. Use Sync key to add other Windows10 computers to the chain
   3. Ensure that Bookmarks, History and Open Tabs are being syncd across all computers in the chain
   4. Ensure that the computers have more than 4 unique tabs open on each computer that are NOT open on the other computers

## Actual result:
When one looks under HIstory flyout under hamburger menu you will see only 4 tabs under each of the other computers.

## Expected result:
One should see under the History flyout all of the tabs that are at least unique and preferably all the tabs that are open on the other computer under each heading for the respective computer.

## Brave version (brave://version info)

Brave | 1.13.66 Chromium: 84.0.4147.125 (Official Build) beta (64-bit)
-- | --
Revision | d0784639447f2e10d32ebaf9861092b20cfde286-refs/branch-heads/4147@{#1059}
OS | Windows 10 OS Version 1909 (Build 18363.1016)

## Version/Channel Information:
Beta is only one I have installed and is where it is occurring

- Can you reproduce this issue with the current release? No since Sync v2 is not available
- Can you reproduce this issue with the beta channel? YES
- Can you reproduce this issue with the nightly channel? Do not know

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? Rewards is disabled on both Brave 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Same as #11196. Only typed in URL's are sync'd as of now and not tabs that have links opened via context menu or via external file link

cc: @AlexeyBarabash @darkdh

**Comment by snowbound** [comment]
The tabs from these other computers have all been opened by clicking on bookmarks on the said computer or via a session manager on startup. Some of these tabs are showing up in the sync but others are not. There are never more than 4 tabs from any of these computers showing up under the History flyout.

**Comment by bsclifton** [comment]
Is this the same issue as https://github.com/brave/brave-browser/issues/10707?

**Comment by fredless** [comment]
> There are never more than 4 tabs from any of these computers showing up under the History flyout

I am observing precisely the same behavior on stable v1.13.82

**Comment by rebron** [comment]
I'm observing the same behavior, looks like only 4 tabs are being synced via the History menu item.

**Comment by AdnanHodzic** [comment]
I have this same problem, where no more then 4 tabs are synced between Brave on Linux an MacOS. I also have 3 Android phones synced, and only one of devices tabs are being synced (<= 4 tabs), other 2 are not even displayed.

Needless to say, sync has been properly setup for all mentioned devices.

**Comment by snowbound** [comment]
I have removed Sync from the Brave installs here.  I use a service for passwords and bookmarks so the only thing Sync in my case is Open Tabs/history. The open tabs from other devices are not implemented in Sync V2 so I currently do not see SyncV2 being of any use to me. I am on iOS for a couple of devices but those devices are stuck on iOS12  so the default browser option isn't going to work.

**Comment by 64br137** [comment]
Same behavior here, i'm on Linux. 4 tabs synced between devices.

**Comment by AdnanHodzic** [comment]
It's apparent that this problem is present on every platform and it's disappointing Brave team hasn't even acknowledged existence of this issue in 71 days since it's been reported. 

Due to having only 4 or less tabs synced from each device, and not being able to pick up where I left off when I switch to one of my 5 other devices. I tried sending tabs to my devices by using "Send to your devices", but it's very slow to the point of being unusable. 

If I end up leaving Brave this will be the main reason.

**Comment by bsclifton** [comment]
cc: @jsecretan

**Comment by fredless** [comment]
> Brave team hasn't even acknowledged existence

to be fair, @rebron did repro & move it into low-priority backlog last month

**Comment by snowbound** [comment]
Now with the RECapcha issues in Brave forcing one to repeatedly solve captchas on websites like PayPal before one is connected, I have had to switch over to another browser. Frustration is not what I need from a web browser when I need to get business work done.

**Comment by jsecretan** [comment]
Ok I'll see if I can move this one up.

**Comment by AlexeyBarabash** [comment]
it is similar to https://github.com/brave/brave-browser/issues/12391 and will be fixed with https://github.com/brave/brave-core/pull/7121

**Comment by ConercaoAlpha** [comment]
@AlexeyBarabash  Any idea on a release date?

**Comment by AlexeyBarabash** [comment]
@ConercaoAlpha 
There is no the exact date, now PR is under review, then it will be merged into Nightly.
Then either it will be uplifted into Stable and will be available 8th of December.
Or it will migrate to Beta and then will migrate into Stable and will be available 19th of Jan.
https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule

Decision will depend on many factors.

**Comment by ConercaoAlpha** [comment]
@AlexeyBarabash 
Thanks for the info. This sync issue is the only thing that is stopping me using Brave

**Comment by AlexeyBarabash** [comment]
This already works on Nightly, as https://github.com/brave/brave-core/pull/7121 was merged.

**Comment by bsclifton** [comment]
Updated milestone/labels

**Comment by GeetaSarvadnya** [comment]
Verification passed on

```

Brave | 1.19.66 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Windows 10 OS Version 2004 (Build 19041.685)

```
- Verified the STR from the description
- Verified that all the open tabs from other devices synced are shown after clicking on `more...` in the history hamburger menu
Device A:
![image](https://user-images.githubusercontent.com/38657976/103074921-95a4b880-45f0-11eb-84cb-5842609ddf93.png)
![image](https://user-images.githubusercontent.com/38657976/103074946-a8b78880-45f0-11eb-90c7-7d961f217fba.png)

Device B:
![image](https://user-images.githubusercontent.com/38657976/103075084-e7e5d980-45f0-11eb-9153-7295014a31c0.png)
![image](https://user-images.githubusercontent.com/38657976/103075098-f207d800-45f0-11eb-84b1-6c11378300b6.png)

- Logged https://github.com/brave/brave-browser/issues/13293 and https://github.com/brave/brave-browser/issues/13292

**Comment by eljuno** [comment]
@AdnanHodzic the fix will be available from v.1.19.x and the latest stable release is 1.18.x 😅

**Comment by AdnanHodzic** [comment]
@eljuno thanks for the heads up, I somehow managed to miss this. Looking forward to having these changes in stable on January 19th.

**Comment by vfl97** [comment]
Still a desktop only support I guess?

**Comment by urbenlegend** [comment]
I think this needs to be reopened. While I do see "Tabs from other devices" showing more than 4 tabs, not all of my tabs are synchronizing across. It seems like it occasionally skips some tabs and syncs others. Currently I have 7 tabs on one of my desktop PCs but I only see 5 on my laptop. All of them are actual sites and not internal pages. My `brave://sync-internals` shows all green on both machines.

**Comment by snowbound** [comment]
@urbenlegend Do you see a line at the bottom of the list saying "More..." ? Clicking on More should show all of the tabs from the other device.

**Comment by urbenlegend** [comment]
@snowbound Yes that's what I am referring to. The "Tabs from other devices" section doesn't show all my tabs. Here's proof

**Screenshot from my desktop PC**
![Screenshot 2021-01-22 082433](https://user-images.githubusercontent.com/241316/105517467-efe67700-5c8b-11eb-856b-8f338fd4af53.png)

**Screenshot from my laptop**
![Screenshot 2021-01-22 082451_LI](https://user-images.githubusercontent.com/241316/105517503-fa087580-5c8b-11eb-9f0d-640877472604.jpg)

As you can see, some of my pinned tabs aren't there, as well as the Arstechnia and Gamespot tabs. My `brave://sync-internals` show that sync is green and properly connected. I have Sync everything enabled on both devices.

**Comment by snowbound** [comment]
I am on the beta here Version 1.20.83 Chromium: 88.0.4324.96 (Official Build) beta (64-bit) on WIndows 10 sytems here and just noticed the same darn issue here. One computer only is seeing 2 tabs from another desktop computer on the same sync chain even those the other computer has 10 tabs open..

**Comment by bbondy** [comment]
This issue seems to still be happening, so re-opening.

**Comment by snowbound** [comment]
I  trashed the sync chain that I was using and created a new one between these two computers. Both can see each other's Open Tabs at least for now. Whether it will stop working just like the previous sync chain only time will tell.

**Comment by urbenlegend** [comment]
I trashed my sync chain already and the issue happens to me immediately.

**Comment by snowbound** [comment]
@urbenlegend Is your desktop or laptop going into sleep mode?

I swear that the sync between the two machines was working fine for a while here on the old sync chain. Then I noticed one day that it turned into one-way sync. I am going to keep an eye on it here with the new chain and see if it misbehaves. 

Same set up here one computer is a desktop and the other a laptop. Laptop experiences sleep mode (during the day) as well as hibernation mode (at night). The Open tabs from the laptop were the ones that were not showing up properly on the desktop which is always powered on during the day and powered off overnight. Desktop when it was using the old sync chain only seen 2 Open Tabs from the laptop.

**Comment by urbenlegend** [comment]
@snowbound Yes I sleep both machines quite frequently.

**Comment by urbenlegend** [comment]
Okay, so I created a brand new sync chain today and only joined my PC and Tablet. Tab sync seemed to be working fine for a few hours.

I then joined my Pixel 5 phone into the sync chain and after a few minutes, the tab sync issue appeared again.

@snowbound @GeetaSarvadnya @AlexeyBarabash Can you guys test with 2 PC devices and an Android device? Or maybe 3 PC devices? I am wondering if this issue only crops up with more than 2 devices or when an Android device is introduced into the mix.

In the meantime, I will create a new sync chain and only join my PC and laptop to see if it doesn't break.

**Comment by snowbound** [comment]
The last time the sync screwed up here was still with two Windows10 PCs. A desktop and a laptop. The laptop has a Brave Beta and Brave Release installed on it. Both were in the same sync chain as was the desktop which was Brave Beta. I was using only the Beta on the desktop and laptop. After a while I noticed that the Open Tabs on the laptop were not showing up properly on the desktop. I would only see 2 of the laptop Open Tabs when I was using the desktop.  No Android devices here. I could throw Brave on a 3rd PC here that I don't normally use as frequently.

**Comment by snowbound** [comment]
Just installed Brave Beta on a 3rd computer here. Like the other two I have sync set for
Bookmarks, Extensions, History, Settings,Open Tabs. 

Once the sync completed on the third Wind10 desktop I noticed the settings were different on the new computer. **Hide Brave Rewards button** was not enabled nor was **Use wide address bar** Unlike the existing two computers **Allow Twitter embedded tweets**, **Allow Facebook logins and embedded posts**, **Allow Google login buttons on third party sites** were all enabled on the new computer rather than being disabled as is the case on the two existing computers.

I will have to keep an eye on the Open Tabs but settings still are not syncing properly and is something I do not believe ever sync'd correctly. If there is a limitation in Settings then perhaps clearly indicate what "Settings" that SyncV2 is actually capable of syncing.

**Comment by cardin** [comment]
> Once the sync completed on the third Wind10 desktop I noticed the settings were different on the new computer. **Hide Brave Rewards button** was not enabled nor was **Use wide address bar** Unlike the existing two computers **Allow Twitter embedded tweets**, **Allow Facebook logins and embedded posts**, **Allow Google login buttons on third party sites** were all enabled on the new computer rather than being disabled as is the case on the two existing computers.

Those settings are not synced by design, though I'm not sure why.

> If there is a limitation in Settings then perhaps clearly indicate what "Settings" that SyncV2 is actually capable of syncing.

I agree. The sync page seems woefully vague and outdated. It doesn't even mention desktop, Android, and iOS sync differences! It even still claims iOS sync is unsupported!

https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-
https://support.brave.com/hc/en-us/articles/360047642371-Sync-FAQ

**Comment by urbenlegend** [comment]
@snowbound So your current sync chain has been working okay for a few days? I was able to reproduce the tab sync issue on a brand new chain pretty much immediately when I added my Android device. Do you perhaps have an Android device available for testing?

As for your settings sync, I believe not all settings are included in the settings sync. The settings that you mention have never synced across devices for me, and I can definitely see how people would want those as independent settings on each device that they have. This issue is also probably best discussed in a separate bug report. We should try to keep the discussion here just about the tabs.

**Comment by snowbound** [comment]
@urbenlegend yes the two windows10 machines seem to be syncing Open Tabs ok so far once I created a new sync chain. Will see how it behaves with 3 Windows10 computers now.

**Comment by snowbound** [comment]
I have added the above Sync settings issues on to an existing r[eport](https://github.com/brave/brave-browser/issues/13555)

**Comment by snowbound** [comment]
@urbenlegend I think you may be on to something regarding 3 devices. I have 3 desktop Windows10 computers with Brave Beta installed. Computer A is a desktop on which I initiated the current sync after deleting the prior one. Computer B is a laptop. Computer A could see ALL of computer B Open Tabs and vice versa. I added a new computer C, last night. It never had Brave installed and added it to the sync chain.

Computer A can see computer C's open tabs yet Computer C only sees only 3 of the 13 Open Tabs on computer A. 

This is the History view from Computer C only showing 3 open tabs from Computer A

![image](https://user-images.githubusercontent.com/596147/106167926-57e90180-6153-11eb-9d88-da3bedabc8d4.png)

**Comment by urbenlegend** [comment]
@snowbound Yep, that's pretty much what I see as well on my devices. Over time it gets worse too. I predict that eventually Computer A will be unable to see all tabs from Computer C as well. The issue also doesn't go away until you create a brand new chain. Simply removing the third device doesn't restore functionality.

**Comment by snowbound** [comment]
@urbenlegend Yes that is exactly what I saw last time. Like you I removed a third device and it did nothing. Only creating a new sync chain fixed it.

**Comment by snowbound** [comment]
I just checked the laptop (computer B) in this Sync chain and it is now only seeing 3 Open Tabs on Computer A the desktop that initiated/created the sync.  It sure looks like that there is indeed an issue with Sync v2 when more than 2 devices are involved.  In my case, the computer which creates the Sync chain is the one that winds up not showing all of its Open Tabs correctly in History  once a third device is added to the chain.

**Comment by urbenlegend** [comment]
@snowbound You may also be correct about sleep affecting tab sync as well. In my current 2-device sync chain, I have a desktop PC and a Surface tablet. My desktop PC is on for most of the day and my tablet sleeps frequently. I've noticed that when I have a lot of tabs open on my PC and I wake up my tablet, Brave is unable to sync some of the tabs that are on loaded on my PC.

However, any other tabs I open on my PC AFTER the tablet has been woken up is properly synced, unlike in a 3-device sync chain where tabs are randomly not synced.

**Comment by snowbound** [comment]
Well, my laptop (computer B) which hibernates overnight and goes to sleep during the day was seeing tabs from computer A fine and computer A was seeing Open Tabs from the laptop ok. That was until I introduced the 3rd computer a desktop (computer C) . Now the laptop. Now the laptop only sees 4 of the Open Tabs from computer A.  Computer A still all the open tabs from the Laptop though.

**Comment by snowbound** [comment]
I opened up my laptop out of hibernation and checked the history to see the status of the Sync. Lo and behold the Sync history does not show Computer A at all now.  I go to Sysnc option in settings and it shows  all three computers. Computer A has been powered on all day. Sorry Brave but your Sync v2 has issues w Open Tabs still!

**Comment by urbenlegend** [comment]
@snowbound Agreed, open tabs sync definitely still has a lot of issues. QA needs to improve their testing suite to catch these issues instead of just testing two devices for a few minutes.

**Comment by snowbound** [comment]
Even after removing all of the devices from a sync chain and creating a new chain there are problems. With only two computers, a desktop can see the Open Tabs from a laptop however the laptop only shows 5 tabs from 11 open tabs from the desktop. Sorry It has been a never-ending battle with Sync v2 from day one. Brave but Sync v2 is unreliable for Open tabs.

**Comment by jsecretan** [comment]
Thanks for the detailed analysis of this @snowbound and @urbenlegend.  We're digging in to try to get to the bottom of this.  Can you both confirm something for me?  If you look at brave://sync-internals, under "Status from Last Completed Session", what does "Commit Step Result" say?

@cardin thanks for mentioning the FAQ, I've asked the support team to put in some updates there.

**Comment by snowbound** [comment]
Well, I have resorted to creating a new sync chain and only 2 devices. The two devices appear to be syncing open tabs properly now. Both of the computers were restarted since my [comment ](https://github.com/brave/brave-browser/issues/11183#issuecomment-771152554) 

Commit Step Result | UNSET

**Comment by urbenlegend** [comment]
@jsecretan Thanks for expediting this. Status from Last Completed Session alternates between these two states
![image](https://user-images.githubusercontent.com/241316/106947701-9183b480-66df-11eb-9b4d-f04df9a1d8cc.png)
![image](https://user-images.githubusercontent.com/241316/106947799-b8da8180-66df-11eb-91f3-4ad534575d67.png)

**Comment by jsecretan** [comment]
Hmmm ok thanks, not what I expected honestly.  I am able to recreate a situation locally here where I get a commit step result of SERVER_RETURN_TRANSIENT_ERROR which can hold things up.  Let me dig a little further.  Would either of you be up for a screen share if we get stuck?

**Comment by urbenlegend** [comment]
@jsecretan Both @AlexeyBarabash and I have gotten SERVER_RETURN_TRANSIENT_ERRORs before, specifically when testing https://github.com/brave/brave-browser/issues/11714. I stopped getting that when I created a brand new sync-chain, but I dunno if that error comes back after long-term use.

SERVER_RETURN_TRANSIENT_ERROR does hold up sync quite a bit, but I think the issue in this bug report is different. Sync appears to be going properly and not in backed off mode, but the tab sync randomly chooses to omit tabs on certain devices.

Yes I am willing to do a screen share with my 3 devices to demonstrate the issue if you guys need it. I am able to very quickly reproduce the issue even on a brand-new sync chain once I add more than 2 devices. Even 2 devices get finicky after waking a device up from sleep.

**Comment by snowbound** [comment]
I just checked my laptop again and now it shows the MORE line for the desltop computer's Open Tabs which several hours ago it never did. 


Sync Source | PERIODIC
-- | --
GetKey Step Result | UNSET
Download Step Result | SYNCER_OK
Commit Step Result | UNSET

**Comment by snowbound** [comment]
I checked my laptop here. It showed that there were only 4 Open Tabs from my desktop computer even though the desktop computer had 14 tabs open on it. On the laptop I closed Brave down and started it back up. I checked again and this time the History showed a MORE line for the destkop, Clicking on more showed that Brave indicated that there were 5 open tabs on the desktop computer rather than 14 tabs. The laptop is regularly put into sleep and hibernation but Brave was running on the laptop for at least 30 minutes when I did the initial check today.

Desktop computer showed 
Sync Source | PERIODIC
-- | --
GetKey Step Result | UNSET
Download Step Result | SYNCER_OK
Commit Step Result | UNSET

**Comment by arthurjosse** [comment]
Brave desktop and Brave Android v. 1.19.92

Sync completely fail to retrieve tabs opened on my phone. Nothing happens. Setting up a new chain etc. does nothing (but newly visited tabs on mobile appear after some time in the desktop history). 

It's been 2 years since the release of Sync.

**Comment by snowbound** [comment]
The current version of sync SyncV2 was released back in August 2020 and at the time the Open Tabs was incomplete. My laptop is still unable to see all of the Open Tabs on the desktop computer.

**Comment by GabeVilela** [comment]
I'm also having this issue. 
Curiously enough, I have two Brave windows opened in my desktop PC, but it only syncs a few of the tabs from Window A.
Both are running stable 1.20.103
Devices are Windows 10 20H2 and Android 10

**Comment by snowbound** [comment]
I tried starting yet another new sync chain and between 3 Windows10 20H2 computers here. The Open Tab sync is inconsistent. Tabs are not showing up with any consistency.



Sync Source | PERIODIC
-- | --
GetKey Step Result | UNSET
Download Step Result | SYNCER_OK
Commit Step Result | UNSET

**Comment by snowbound** [comment]
I did some further testing on 2 laptops and a desktop. The desktop computer would show up on the laptops as having only a subset of the actual Open Tabs., The laptops have seen a tab in the Open Tab list for the desktop that had not been open on the desktop for days. I tried removing the desktop from the sync chain and it continued to show up in the History on the laptops. I had to remove all the computers from that sync chain and start a new one to get the Open Tabs from the desktop to show up properly on the laptop.

**Comment by lxwulf** [comment]
I can't even leave my snyc-chain on Windows... don't know what I should do can't sync any device....

**Comment by snowbound** [comment]
@lxwulf There are two ways of leaving a sync chain. At the top of the brave://settings/braveSync/setup page by clicking on the corresponding X and then scrolling all the way to the bottom of the page, there is not a Leave Sync Chain option?

**Comment by AlexeyBarabash** [comment]
This issue was marked as solved by https://github.com/brave/brave-core/pull/7121 and shipped in `1.19.x`.

By this reason I am closing it, but you may keep leave the comments or use another similar issue https://github.com/brave/brave-browser/issues/13293. The work on fix is in progress and has been raised to the highest priority.

Upcoming fix which is intended to fix issue beyond the UI will be linked to another issue https://github.com/brave/brave-browser/issues/13293.

**Comment by snowbound** [comment]
Nothing has changed with Sync and Open Tabs between devices which in my case are a series of desktops and laptops. The Open Tabs listing is unreliable. Open Tabs from devices whose Open Tabs has been disabled hours ago are still showing up on laptops showing erroneous tabs. This is on Version 1.22.45 Chromium: 89.0.4389.58 (Official Build) beta (64-bit)

**Comment by lxwulf** [comment]
I can kinda approve this. In my case my new installed BB on Linux works together with my installed version on my phone (android) but I can't still go out of the sync chain on my Windows version. It says reload, but it doesn't do anything....

**Comment by jsecretan** [comment]
Thanks for the continued detailed feedback @snowbound and @lxwulf we are still working on getting to the bottom of everything here and will be putting in more time on it this week.

**Comment by snowbound** [comment]
I just spent a week using MS Edge Chromium on my desktop, laptop, and iOS-based phone. I saw the full complement of ALL the tabs open on the other devices when I went to its corresponding entry in History.  When I reverted back to Brave Version 1.22.62 Chromium: 89.0.4389.90 (Official Build) beta (64-bit) when I go to my desktop and view the list of Open Tabs for my laptop I see 3 of the  9 tabs that are open on the laptop. The laptop CURRENTLY shows 9 of the 15 Open Tabs on my desktop.

For me, Open Tabs in SyncV2 on Brave as it stands is sorry to say is useless. I feel that I am not the only one with this point of view.

**Comment by snowbound** [comment]
Hello, Brave this issue is not solved why was it closed? the silence is deafening and why some Brave users become former users.

**Comment by jsecretan** [comment]
Hi @snowbound, I'd like to keep this specific issue closed for now and move discussion over to this:

https://github.com/brave/brave-browser/issues/13382

For clarity, I'd like to keep this issue closed because it is easiest from a tracking standpoint to let this cover the feature work for showing More Tabs.

**Comment by urbenlegend** [comment]
As of the most recent update (1.25.68), it seems that tab sync seems to work pretty well. There is still some lag time, but its usually within 10-30 seconds between desktops. On mobile, it still takes a while to get sync updates after waking the device out of sleep because sync keeps saying that there's no network connection.

@snowbound can you confirm on your end? Or is this just a random fluke again?

**Comment by snowbound** [comment]
I will have to re enable Sync here on all my systems and see what happens.

**Comment by snowbound** [comment]
Well, I redid sync yet again. I can see the Open Tabs from my laptop on my desktop but when it comes to mobile in particular iOS sync is hamstrung. All I can see is Bookmarks as Open tabs from either Laptop or Desktop is not showing up on iOS. Nor is any iOS Open Tabs showing up on my PCs.

**Comment by snowbound** [comment]
With Version Beta 1.26.43  on Desktops my desktop can see the Open Tabs on my laptop. Whether that will hold is debatable. iOS sync is a different story https://github.com/brave/brave-browser/issues/11183#issuecomment-850084076

**Comment by eljuno** [comment]
@snowbound iOS don't have tab sync yet.
https://github.com/brave/brave-ios/issues/3229

**Comment by snowbound** [comment]
Oh, must have been MS Edge that has that feature implemented. Sorry about that mixup.

**Comment by GabeVilela** [comment]
Open tabs sync seems to be working as intended now.
Tested with Stable 1.24.86 on Android 10 and Stable 1.25.68 on Windows 10

**Comment by AlexeyBarabash** [comment]
25th of May we have updated the server with the fix of error in protocol, https://github.com/brave/go-sync/pull/68. We used incremental integers as a version code and occasionally happened that for existing opened tabs after re-opening was used lower version code than the previous stored; in such cases client ignored the update and tab was not synced. Now version code is a server-side time code of operation, it is always greater than previous version code for the same object.

Thank you for the feedback.

**Comment by arthurjosse** [comment]
After receiving a notification for the last comments on this issue I've tested for the umpteenth time to sync my opened tabs. v.1.25.68 on Windows 10 and 1.24.86 on Android 7. As always, it's fail as nothing happens.

**Comment by snowbound** [comment]
So Android is suppose to sync Open Tabs? It is not possible at least now
on  iOS

**Comment by lxwulf** [comment]
Update on my situation: I saw no other possibility to save my bookmarks and install brave browser stable. I successfully added my desktop Windows 10 machine to my already existing chain and everything synced properly.

So for me, it's not solved directly, but I found a not pretty workaround with a new installation of another version.

PS: something new maybe for an issue or feature requests itself: can we add feature which remove duplicates in bookmarks? Let me know I would make a new issue/feature request.

Greetings LxWulf

**Comment by calebjacksonhoward** [comment]
I've been jumping around the links amongst three of four different discussions of this issue (with many of the same participants).

I've just discovered this issue (Sync not syncing open tabs).  I'm using: Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit) on Windows 10.  I'm trying to sync to my laptop.  I have a couple-hundred tabs open - sorted into a dozen tab groups.  It's impossible to work on two machines if I can't carry my working context with me.

I saw someone say #wontfix on one of these threads, and I've seen people claim to have something working.  I've also seen suggestions about starting a new sync group, and that maybe it has to do with sleep mode breaking some state.

It seems like Windows is a popular OS, and I'm working in a heterogeneous environment between two of the machines I'm trying to make this work on.  I was hoping someone had a suggestion, workaround, or whole 'nother solution (like an extension that managed grouped tabs?)

I need some kind of a solution, but the Brave feature working would be ideal.

Is this ever going to happen?

**Comment by snowbound** [comment]
@calebjacksonhoward I thought Brave had pushed out a fix for this issue a month or two ago. I batted my head against the wall re Brave Open Tab sync for almost a year.  When I was having this issue I had nowhere near 100 tabs open. Times changed here and I am not using my laptop as much. What was so frustrating over this year-long period was that I saw MS Edge having no issue syncing open tabs almost instantly between 2 Win devices. 

 I can do some testing here over a couple of days and see what is happening here. 

That "wont fix" perhaps was the history syncing aspect, where the only syncing of History Brave will do, is of those URLs which yu manually entered in Brave. Links clicked on via Bookmarks etc are not synced. Sorry just going by memory here and I could be wrong.

**Comment by jsecretan** [comment]
Thanks @snowbound for your help in debugging and feedback.  @calebjacksonhoward as far as I can tell tab sync should be working, but if there's a bug that has crept in, or if it's not scaling to your number of tabs, I'd like to get to the bottom of it.  If you have some time, I'd love to have the sync team do a screen share with you.  Mind emailing me at jimmy@brave.com and we can coordinate?
