### ISSUE TITLE
Google Drive does not play mp4 video

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#1122]
## Description 
Google Drive will not play .mp4 video. Disabling shields and attempting to play the video does not allow video to be played and console shows errors.

## Steps to Reproduce

   1. Clean profile 0.55.3
   2. Login to Google Drive
   3. Attempt to play an .mp4 file --> see notification in URL bar about autoplay being blocked. (https://github.com/brave/brave-browser/issues/1120)
   4. Click on this and choose to Always Allow, video still will not play, console errors.
   5. Put shields down, video still will not play, console errors.

## Actual result:
mp4 video will not play (shields up or down):
![screen shot 2018-09-13 at 12 52 59 pm](https://user-images.githubusercontent.com/28145373/45503137-f8415580-b753-11e8-9dff-408f56cd8dfc.png)

console errors: https://gist.github.com/LaurenWags/bda1b03eaeda8a3b8060b68cfd01ff8b#file-autoplay-txt

## Expected result:
Video should play, no console errors.

## Reproduces how often: 
easily

## Brave version (chrome://version info)
Brave | 0.55.3 Chromium: 70.0.3538.12 (Official Build) dev (64-bit)
Revision | ad61584ca32115f953ce656dd75b44f1c502a75d-refs/branch-heads/3538@{#179}
OS | Mac OS X

### Reproducible on current release:
no, does not reproduce on 0.23.107

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? no
- Is the issue reproducible on the latest version of Chrome?  no

### Additional Information
Reproduced by @srirambv on Win.

Found while testing https://github.com/brave/brave-browser/issues/833

**Comment by bbondy** [comment]
Does this work on browser-laptop?

**Comment by darkdh** [comment]
Does it play after you choose "Always allow" and click "Done" then do a manual refresh?
This kind of dropdown dialog has a general defect which is it will not auto refresh/or prompt to reload when setting changed. 
<img width="513" alt="screen shot 2018-09-13 at 20 13 53" src="https://user-images.githubusercontent.com/11330831/45527650-9c95bd00-b791-11e8-828c-e52960766783.png">
Some content settings required to reload the page when setting changed not just limited to autoplay.

**Comment by LaurenWags** [comment]
@bbondy tested on browser-laptop with `0.23.107` worked without issue. Steps:
1. Clean profile on 0.23.107 (release version)
2. Login to Google Drive
3. Double click on an .mp4 file --> file displays and plays without issue.

**Comment by LaurenWags** [comment]
@darkdh I don't see that message displayed. I don't get an Autoplay prompt at all (to the left of the URL bar) like I would expect. I only see the message to the right telling me Autoplay is blocked: 

![screen shot 2018-09-14 at 9 48 19 am](https://user-images.githubusercontent.com/28145373/45554007-5a0cc880-b803-11e8-9464-8357c77335ca.png)

When I click on that I change the radio button to Always Allow and nothing happens. Reloading the page has no effect - I am still unable to play the mp4 file (shields up or down). 

![screen shot 2018-09-14 at 9 49 12 am](https://user-images.githubusercontent.com/28145373/45554049-76106a00-b803-11e8-9d46-e97a24f37e05.png)

If you want to look at this together let me know.

**Comment by bsclifton** [comment]
This should be working, per having the following set:
https://github.com/brave/brave-browser/blob/0e2e3a222bfe58f93953e665590e2b49f8e150d7/lib/config.js#L63-L64

**Comment by bbondy** [comment]
This is also happening on Android so moving this to the backlog since it doesn't seem like it would stunt growth relative to other issues.

**Comment by bridiver** [comment]
This looks like fingerprinting protection is not getting disabled with shields down

**Comment by bridiver** [comment]
I think we should fix the value to 100%

**Comment by bridiver** [comment]
fixing the battery api does not fix the problem per @bbondy, but if we are moving forward with fixing to 100% we should open a new ticket

**Comment by jonathansampson** [comment]
We appear to still be having issues here.

Version:

Brave | 0.56.15 Chromium: 70.0.3538.110 (Official Build) (64-bit)
-- | --
Revision | ca97ba107095b2a88cf04f9135463301e685cbb0-refs/branch-heads/3538@{#1094}
OS | Windows
JavaScript | V8 7.0.276.40
Flash | 31.0.0.153 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_31_0_0_153.dll
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer,DefaultEnableOopRasterization,VizDisplayCompositor,AutofillSaveCardSignInAfterLocalSave,kAutofillServerCommunication --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe



Steps:

1. Visit https://drive.google.com/file/d/1IjafCgR2HWBDzB-s6XTeCZtXFUM2lXcH/view
2. Attempt to play the video
3. Lower shields
4. Attempt to play the video

Note that the video does not play in Brave Core.

**Comment by srirambv** [comment]
This seems to be fixed on the release version itself. Not sure which PR fixed it. But closing the issue for now.

**Comment by cliffordp** [comment]
Same on Mac OS X Catalina (10.15)
Brave version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)

**Comment by pfoxsounds** [comment]
Having this issue with Mac OS 10.12.6 (16G2136)
Brave 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)

**Comment by timelessthee** [comment]
Also _still_ having this issue on:
Mac OS 10.14.6 (18G103)
Version 0.69.135 Chromium: 77.0.3865.120 (Official Build) (64-bit)

**Comment by bizfreak22** [comment]
Also having this issue on:
Mac OS 10.15.1 (19B88)
Version 0.71.112 Chromium: 78.0.3904.87 (Official Build) beta (64-bit)

**Comment by scrubdaddytm** [comment]
After updating to v1.0.0 I'm no longer experiencing this bug :)

macOS 10.14.6 (18G95)
Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by pfoxsounds** [comment]
Fixed for me as well

Mac OS 10.12.6 (16G2136)
Version 1.0.0 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by bsclifton** [comment]
@bizfreak22 @timelessthee can you please try updating to the latest version (if you haven't already) and then try this again? 😄

**Comment by ryanbr** [comment]
I've tested this, seems to work only when allowing 'Allow all cookies' in shields.

**Comment by ryanbr** [comment]
From a new profile `Brave Beta (Version 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit))`

Just for the record of the cookies are being blocked in google drive:

![drive-google](https://user-images.githubusercontent.com/1659004/74422189-16643580-4eb3-11ea-8894-ccddba132795.png)

**Comment by ryanbr** [comment]
1. Tested with Brave Beta, removed old profile.
2. Logged into gmail, click on the google drive link (top right)
3. View cookies on google drive. see Allowed/blocked items.

Not sure how reproducible it is, closing and re-opening seems to change this

**Comment by pes10k** [comment]
I believe this should be closed as of https://github.com/brave/referrer-whitelist/pull/26.

There may be additional issues here (could be additional cookie related issues) but getting the referrer part straightened out is at least a necessary, if not sufficient, step

**Comment by pes10k** [comment]
This requires additional storage exceptions for as added in https://github.com/brave/brave-core/pull/5313

**Comment by NightStormYT** [comment]
Still an issue.
