### ISSUE TITLE
[Desktop] Text in Address Bar too Small

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-browser#11607]
## Description 
Some users [[1](https://twitter.com/commadelimited/status/1268595387532816384)] have reported that addresses in the omnibar are uncomfortably small on Ubuntu.

![image](https://user-images.githubusercontent.com/815158/92310149-1cb22000-ef71-11ea-9d4c-3e84bebfc891.png)

## Actual result:
Text in address bar (omnibar) is too small.

## Expected result:
Test should be a bit larger; similar to Mozilla Firefox (shown below).

![image](https://user-images.githubusercontent.com/815158/92310184-73b7f500-ef71-11ea-8f90-10037425517b.png)

## Reproduces how often: 
Easy. Always.

## Brave version (brave://version info)
TBD

## Version/Channel Information:
- Can you reproduce this issue with the current release? TBD
- Can you reproduce this issue with the beta channel? TBD
- Can you reproduce this issue with the nightly channel? TBD

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?  N/A
- Does the issue resolve itself when disabling Brave Rewards?  N/A
- Is the issue reproducible on the latest version of Chrome?  TBD

## Miscellaneous Information:

This issue also appears to impact (some versions of?) Chrome:

![image](https://user-images.githubusercontent.com/815158/92310201-9a762b80-ef71-11ea-9951-503d97c1bf5c.png)

**Comment by commadelimited** [comment]
Reporting in with my system details.

```
Brave	1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)
Revision	c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}
OS	Linux
JavaScript	V8 8.4.371.23
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
Command Line	/opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --enable-features=WebUIDarkMode,MixedContentSiteSetting,AutoupgradeMixedContent,PassiveMixedContentWarning,ReducedReferrerGranularity,PasswordImport,PrefetchPrivacyChanges,DnsOverHttps --disable-features=AutofillServerCommunication,AutofillEnableAccountWalletStorage,AllowPopupsDuringPageUnload,NotificationTriggers,TextFragmentAnchor,LookalikeUrlNavigationSuggestionsUI,UseButtonTranslateBubbleUI,VideoPlaybackQuality,TabHoverCards,SmsReceiver --flag-switches-begin --flag-switches-end
Executable Path	/opt/brave.com/brave/brave
Profile Path	/home/user/.config/BraveSoftware/Brave-Browser/Default
```

**Comment by commadelimited** [comment]
Note that while Chrome is my preferred browser, it has some issues on Ubuntu so I don't use it on this machine. I wanted to use Brave as my primary browser, but this display bug forced me to switch to Firefox instead.

**Comment by vgnh** [comment]
Adding to this issue, Microsoft Edge seems to be the only browser that has got the address bar font size right.
While Firefox's address bar font size is smaller than Edge, it is still more readable that Brave.

Brave and Chrome seem to have the same issue with the address bar font size.

![Edge vs Firefox vs Brave](https://user-images.githubusercontent.com/22466712/123773883-980f0480-d8ea-11eb-86f0-a8f447590e80.png)

This is on Fedora (GNOME) with the same display details as @commadelimited.
Resolution: 1920 x 1080 (16:9)
Scale: 100%

```
brave://version

Brave: 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)
Revision: 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS: Linux
JavaScript: V8 9.1.269.36
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Command Line: /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=PrefetchPrivacyChanges,WebUIDarkMode,PasswordImport,ReducedReferrerGranularity,DnsOverHttps,LegacyTLSEnforced,AutoupgradeMixedContent,SafetyTip --disable-features=FledgeInterestGroups,InterestCohortFeaturePolicy,DirectSockets,TrustTokens,SignedExchangeSubresourcePrefetch,FlocIdComputedEventLogging,HandwritingRecognitionWebPlatformApiFinch,IdleDetection,TextFragmentAnchor,EnableProfilePickerOnStartup,SignedExchangePrefetchCacheForNavigations,SubresourceWebBundles,NetworkTimeServiceQuerying,LangClientHintHeader,NotificationTriggers,WebOTP,AutofillServerCommunication,LiveCaption,FederatedLearningOfCohorts,FledgeInterestGroupAPI,AutofillEnableAccountWalletStorage,InterestCohortAPIOriginTrial,FirstPartySets,HandwritingRecognitionWebPlatformApi --flag-switches-begin --flag-switches-end
Executable Path: /opt/brave.com/brave/brave
Profile Path: /home/user/.config/BraveSoftware/Brave-Browser/Default
```

**Comment by jessewriter** [comment]
confirm this is still an issue 1/20/22 linux mint 20.3 Cinnamon

**Comment by kdenhartog** [comment]
This is something that would be quite useful on macOS as well.

When using a 4k external monitor MacOS doesn't scale the text of the browser UI well which is how this would often be solved in other operating systems it seems. For example in Windows I'll just scale my entire screen 150% while keeping my resolution at 4K and that solves the problems. 

From what I can tell if it was possible to scale the browser UI this would be resolved as well.

**Comment by ancho85** [comment]
I was searching for a similar bug before posting one on my own. Why there is so much wasted space between the refresh icon and the bookmark icon? I only see this in Ubuntu, not in Windows. The whole address bar also is shrunk to the right end, before the shields icon. Not a big issue, but still...

**Comment by jaweherbensalah** [comment]
it's 05/2023 and I am facing the same problem on Ubuntu, Is this a chrome issue? weird !!  I have been searching for a solution for a whole day, I changed chrome fonts, and Ubuntu fonts, and still have have a very tiny URL bar, so is there a way to import my google chrome bookmarks to Mozilla so i can make my default browser please?

**Comment by jaweherbensalah** [comment]
it's 06/2023 and I am facing the same problem on Ubuntu, Is this a chrome issue? weird !! I have been searching for a solution for a whole day, I changed chrome fonts, and Ubuntu fonts, and still have have a very tiny URL bar, so is there a way to import my google chrome bookmarks to Mozilla so i can make my default browser please?

**Comment by janbury** [comment]
It's been over 3 years and the issue still persists. Brave is the best browser but the small font and icon sizes really take the fun away from using it on Linux.

**Comment by orange2moon** [comment]
I'd also really appreciate a bigger font in the address bar. I tried increasing the font size in GNOME tweaks without success.

**Comment by jigyansunanda** [comment]
Is this still actively being worked on ? I am using ubuntu and the address bar texts are too tiny and changing the font from system or brave settings does not change it either. it's very difficult to read texts from address bar.

**Comment by markhuyong** [comment]
it works for me:

**Force Wayland backend**

1. Open a new tab in Brave and go to `chrome://flags` or `brave://flags`.
2. Search for `ozone-platform-hint`.
3. Change the setting from "Default" to "Wayland".
4. Restart Brave for the change to take effect.

**Comment by vgnh** [comment]
> it works for me:
> 
> **Force Wayland backend**
> 
> 1. Open a new tab in Brave and go to `chrome://flags` or `brave://flags`.
> 2. Search for `ozone-platform-hint`.
> 3. Change the setting from "Default" to "Wayland".
> 4. Restart Brave for the change to take effect.

`ozone-platform-hint` is a flag that's not available anymore. Could you also post your browser version?

**Comment by markhuyong** [comment]
```
Brave	1.81.137 Chromium: 139.0.7258.158 (Official Build) (64-bit) 
Revision	0849ae3da9da32861edddc9d4c2358ba442f0493
OS	Linux
JavaScript	V8 13.9.205.21
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36
Command Line	/opt/brave.com/brave/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --lso-url=https://no-thanks.invalid --sync-url=https://sync-v2.brave.com/v2 --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --ozone-platform-hint=wayland --flag-switches-end --ozone-platform=wayland --component-updater=url-source=https://go-updater.brave.com/extensions --render-node-override=/dev/dri/renderD128
```

**Comment by zloylinux** [comment]
This is still relevant — it prevents using the browser.

**Comment by ljholiday** [comment]
It is 2026 and this is still an unresolved issue.

i don't see any acknowledgment from dev.

How is an issue that causes people to abandon the product backlog for six years?
