### ISSUE TITLE
Google Sheets won't show print dialogue, prompts to save as PDF instead

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#11913]
## Description 

This seems to be a Windows specific issue. Going to Google Sheets and `File --> Print` (or `ctrl + p`) will show the Sheets print dialogue:
![image](https://user-images.githubusercontent.com/3299098/94585693-37587b80-0235-11eb-8b2c-318ae6afada0.png)

Clicking the `Next` button there should land you on the browser print dialogue screen:

![image](https://user-images.githubusercontent.com/3299098/94585945-86061580-0235-11eb-9b6d-17cfa82dfcdf.png)

This works on macOS and Linux, but for Windows, the browser does not display the second print dialogue box. Instead, you are prompted to download the file and save it as a PDF to your system directly.

## Steps to Reproduce

   1. Visit sheets.google.com using Windows PC
   2. Attempt to print out a sheet
   3. Get prompted to download a PDF of your file rather than print it

## Actual result:

Get prompted to download a PDF of your file rather than print it

## Expected result:
The second browser print dialogue should show.

## Reproduces how often: 

Easily.

## Brave version (brave://version info)

Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? No

## Miscellaneous Information:

Report from user:
https://community.brave.com/t/google-sheets-printing-to-pdf/165332/10

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/print-jobs-get-diverted-to-adobe-acrobat-ac/185981/4

**Comment by muellerryan** [comment]
I am still having this issue, it is annoying since my company is moving to Google for their office software.

**Comment by SatiricPanda** [comment]
I am also having this issue, which is forcing me to switch browsers just to print files.

**Comment by dparker2** [comment]
Also having this issue, but in MacOS.

**Comment by scottdillon** [comment]
To anyone else who is having this problem in 2021:

1. Click the brave lions head icon in the url bar to edit the brave shields settings
2. Click "Advanced view" if you don't see the fingerprinting drop down menu
3. Change the fingerprinting drop down menu to "Allow all fingerprinting"
4. Printing directly from Google Sheets should now work.

**Comment by chrisrosa** [comment]
Disabling Fingerprinting indeed fixes the issue, however I hope the team finds a real solution that preserves this feature.

**Comment by herzer1** [comment]
Fingerprinting change did not fix issue in MacOS
Version 1.29.80 Chromium: 93.0.4577.63 (Official Build) (x86_64)
OS X 10.14.6

**Comment by rumilazzi** [comment]
This is not a Windows specific issue. I have the same issue on MacOS Catalina 10.15.7 (19H1419) with the latest version of Brave - Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64). Printing works fine in standard Chrome browser, but not in Brave. Brave opens a Save PDF file dialog instead.

**Comment by j0hncc** [comment]
I have this issue on Ubuntu 20.04.4 LTS , Brave 1.36.112.
Switching to "Allow all fingerprinting" DOES  resolve/workaround the issue.
