### ISSUE TITLE
System titlebar lost on maximize on linux

### ISSUE THREAD

**Issue by marc1uk** [brave/brave-browser#11967]
## Search for Existing Issues
I've searched for similar issues on brave's extensive history, and found similar ones, but couldn't specifically find this one.

## Description 
The system titlebar offers several options that the Brave CSD bar doesn't - for example, the ability to 'roll up' a window into its titlebar, the option to make the window always-on-top, the option to move the window to a new workspace, or make it visible on all workspaces, etc.

While some find the titlebar a waste of space, personally I find those 6 extra pixels worth that functionality, so I appreciate the option of 'use system titlebar and borders' - kudos on supporting user choices! :+1: 

Unfortunately when maximizing the window, the system titlebar disappears, making the option mostly non-functional. :(

## Steps to Reproduce
   1. Right-click menu bar and check 'enable system title-bar and borders'
   2. Restore the brave window and observe the presence of the system title-bar and borders.
   3. Maximize brave, and observe that they are no longer visible.

## Actual result:
![trash_1](https://user-images.githubusercontent.com/15327579/94916707-19924d00-04a7-11eb-8572-1e42f251ad76.png)
![trash_2](https://user-images.githubusercontent.com/15327579/94916724-1d25d400-04a7-11eb-98fa-54cb1624f60b.png)

## Expected result:
![trash_3](https://user-images.githubusercontent.com/15327579/94917040-b1903680-04a7-11eb-8673-1ebf51947433.png)

## Reproduces how often: 
Always

## Brave version (brave://version info)
Brave | 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | Linux

**Comment by immanuelfodor** [comment]
This is not the case for me on Manjaro KDE, the system title bar is kept when maximized. Maybe it depends on your DE?

What's more annoying for me is that without the system title bar, when Brave is not maximized, there is extraneous space over the tabs and the edge of the browser window. Side-by-side comparison to Firefox:

![image](https://user-images.githubusercontent.com/21174107/111866107-68f00b00-896b-11eb-9812-323ff64b670c.png)

The only workaround is to enable the system title bar, then set no border for the window. However, this loses the ability to manually resize or close or minimize the window (no window action buttons or draggable border are shown), however, moving or snapping to the screen edge works fine:

![image](https://user-images.githubusercontent.com/21174107/111866184-f29fd880-896b-11eb-81d1-e5e76f946b2e.png)

Use case: 4K screen where maximizing the browser is non-viable, but snapping the browser to half of the screen is really comfortable (2K vertical space).

**Comment by Piiit** [comment]
I think this should be considered a bug, because the icons disappear on maximize when the option for native title bars is selected. Someone, might be blocked in a fullscreen view without closing, restore and minimizing icons.

Please give it a higher priority. Thanks for your great work!

**Comment by com2** [comment]
I have version 1.29.81 under Ubuntu 20.04LTS and right clicking in the tab bar in the context menu appears the option "Use system title bar and borders" disabled by default. It does what it says after enabling. Please confirm that this can be considered fixed now. 
![image](https://user-images.githubusercontent.com/1062758/134642479-20ee9087-897c-4d55-b844-696a032c3238.png)

**Comment by Piiit** [comment]
@com2 It is not fixed... I have the same version as you on Cinnamon and when maximizing the window the system title bar disappears

**Comment by Piiit** [comment]
@com2 Tested it also with Chromium Version 93.0.4577.82... there it works correctly

**Comment by com2** [comment]
@Piiit Cinnamon is not KDE based, is it? So may be someone should verify if it is the same under pure Gnome and then decide where this should be reported, here or there?

**Comment by Piiit** [comment]
@com2 Cinnamon is a fork of Gnome3 with GTK3 as graphical framework... but since the first deviation many things were changed under the hood.

**Comment by Piiit** [comment]
Brave is a fork + extras of Chromium, right? So maybe you could check what the differences are... since Chromium works correctly under Cinnamon 5.0.5 on Linux Mint 20.2... I also tested other themes on Cinnamon, sometimes they might cause issues... but it was the same for all themes.

**Comment by simonhong** [comment]
Closed as we can't pro this issue anymore.
