### ISSUE TITLE
Fingerprinting Protections v2: Workers - WebGL Drawing - follow up to 11368, 11839

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#12098]
## Description 

Found while testing https://github.com/brave/brave-browser/issues/11368, https://github.com/brave/brave-browser/issues/11839

Per discussion with @pes10k, assigning to @pilgrim-brave for investigation.

Per instructions on dev-pages.brave.software/farbling.html and dev-pages.bravesoftware.com/farbling.html, for WebGL Drawing the "Worker" column value should match the other columns for that row when FP = standard (since Mode only has standard, not both, for this row) and the value should be different between the two pages.

Additionally, if FP = strict, this is working. This is unexpected since mode = standard for WebGL Drawing. @pes10k @pilgrim-brave could you guys help clear this up? Does WebGL Drawing farbling work for both std and strict?

## Steps to Reproduce

   1. Clean profile, 1.16.x
   2. Navigate to dev-pages.brave.software/farbling.html and dev-pages.bravesoftware.com/farbling.html
   3. Confirm FP = standard
   4. Generate Fingerprints

## Actual result:

For WebGL Drawing the "Worker" column value does not match the others for that row when FP = standard. 

FP = standard
<img width="1204" alt="1 16 x standard FP WebGL Drawing" src="https://user-images.githubusercontent.com/28145373/95786619-f38a5b00-0ca5-11eb-869c-f1efe6c5f92b.png">

FP = strict
<img width="1201" alt="1 16 x strict FP" src="https://user-images.githubusercontent.com/28145373/95786614-f1c09780-0ca5-11eb-836a-117558dfeefa.png">

## Expected result:
For WebGL Drawing the "Worker" column value should match the others for that row when FP = standard. 

## Reproduces how often: 

easily

## Desktop Brave version:

Brave | 1.16.58 Chromium: 86.0.4240.75 (Official Build) dev (x86_64)
-- | --
Revision | c69c33933bfc72a159aceb4aeca939eb0087416c-refs/branch-heads/4240@{#1149}
OS | macOS Version 10.14.6 (Build 18G3020)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? n/a
- Can you reproduce this issue with the beta channel? yes 1.16.x
- Can you reproduce this issue with the nightly channel? yes 1.17.x

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by LaurenWags** [comment]
Reproduces in 1.17.x as well:

FP = standard
<img width="1116" alt="1 17 x standard FP" src="https://user-images.githubusercontent.com/28145373/95786752-36e4c980-0ca6-11eb-8b84-ca055d11906f.png">

FP = strict
<img width="1115" alt="1 17 x strict FP" src="https://user-images.githubusercontent.com/28145373/95786754-38ae8d00-0ca6-11eb-939f-df798a65d034.png">

**Comment by pes10k** [comment]
Similarly, I think this is fixed now and ready for a re-check when you have a chance @LaurenWags.   Thanks!

**Comment by LaurenWags** [comment]
@pes10k what version do you think this should be checked against - Nightly (currently 1.21.x) or one of the other channels?

**Comment by pes10k** [comment]
Ah, sorry @LaurenWags !  It should be fixed in nightly / 1.21.x

**Comment by LaurenWags** [comment]
@pes10k hm, using the below build I don't get any vaules for `WebGL Drawing` (or several others for that matter). Is this expected? This is a clean profile btw.

```
Brave | 1.21.44 Chromium: 88.0.4324.146 (Official Build) beta (x86_64)
-- | --
Revision | 406dc88511162d6598242f2c709be1414a042fb0-refs/branch-heads/4324@{#2088}
OS | macOS Version 10.15.7 (Build 19H15)
```

Example | Example
----- | -----
<img width="1201" alt="Screen Shot 2021-02-05 at 8 20 52 AM" src="https://user-images.githubusercontent.com/28145373/107038900-327b7980-678b-11eb-937e-c232f931f587.png"> | <img width="1199" alt="Screen Shot 2021-02-05 at 8 21 10 AM" src="https://user-images.githubusercontent.com/28145373/107038912-34ddd380-678b-11eb-9b0c-2df7d5d76af7.png">

**Comment by pes10k** [comment]
Ah, apologies @LaurenWags , i was working on the page at the same time you were testing it, sorry for the hassle!  Should be good now :)

**Comment by LaurenWags** [comment]
@pes10k looks like I can still reproduce using a clean profile (default shields, never touched) and the below build:

```
Brave | 1.21.47 Chromium: 88.0.4324.152 (Official Build) beta (x86_64)
-- | --
Revision | 6579930fc53b4dc589c042bec9d0a3778326974d-refs/branch-heads/4324@{#2106}
OS | macOS Version 10.15.7 (Build 19H512)
```

Example | Example
----- | -----
<img width="1034" alt="1" src="https://user-images.githubusercontent.com/28145373/107222850-71a40780-69e3-11eb-9794-d458de651960.png"> | <img width="1035" alt="2" src="https://user-images.githubusercontent.com/28145373/107222855-736dcb00-69e3-11eb-8e29-188bb07f9bcc.png">

**Comment by pes10k** [comment]
Closing because, same as https://github.com/brave/brave-browser/issues/12099, this is not a bug, but needing to use different Web APIs to farble in workers, and so the fabling happening at a different intervention point
