### ISSUE TITLE
Tor window uses Google.com by default

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-browser#1226]
## Description 

On win10 x64, when I select the `Open Tor Window` option from the `sync` menu, the `open Tor window` uses google as the search engine. 

Expected Tor default search engine: 
Tor default, global (except for France & Germany): duckduckgo.com
Tor default, France & Germany: qwant.com 

## Steps to Reproduce

   1.  Click on the `sync` menu
   2.  Open New Tor Window: ![brave-core-tor-issue-09202018](https://user-images.githubusercontent.com/8979240/45862977-f31e7080-bd28-11e8-8b6c-14bedd8f63d5.PNG)
   3.  Enter a keyword into the URL bar. Observe Google.com search results. 

## Actual result:

Google.com results.

## Expected result:
DDG results (global, except for France and Germany) 
Qwant results (France, Germany) 

## Reproduces how often: 

100%

## Brave version (chrome://version info)

```
Brave | 0.55.5 Chromium: 70.0.3538.16 (Official Build) dev (64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Windows
JavaScript | V8 7.0.276.9
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.16 Safari/537.36
Command Line | "C:\Program Files (x86)\BraveSoftware\Brave-Browser-Dev\Application\brave.exe" --enable-tab-audio-muting --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --enable-features=EnableEmojiContextMenu,DesktopPWAWindowing,fill-on-account-select,NewExtensionUpdaterService --disable-features=SharedArrayBuffer --flag-switches-begin --flag-switches-end
```

### Reproducible on current release:

no

### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by rebron** [comment]
cc: @mkarolin

**Comment by simonhong** [comment]
I'll take a look this issue - I implemented private search engine in private window feature.

**Comment by darkdh** [comment]
@simonhong tor window is different than private window. It is a type of guest window with only persistent search engine setting. I recommend setting `kDefaultSearchProviderDataPrefName` when tor profile created and prevent `ProfileManager::SetNonPersonalProfilePrefs` from clearing it.

**Comment by riastradh-brave** [comment]
https://github.com/brave/brave-core/pull/529 partially fixes this so that we don't use Google in Tor windows, which (I think) is the only release-blocking part of this because Google's captcha inundation makes it unusable in Tor, so I'm removing the release/blocking (and feature/tor/leakproofing -- not actually a leak, just usability) labels.  It does not address the part about choosing between DDG and Qwant, so I'll leave this open.

**Comment by darkdh** [comment]
Qwant for France & Germany should be posted as different issue because it is not tor specific but applies for all profiles
Even so, we still can't close this until https://github.com/brave/brave-core/pull/529#discussion_r222366899 is solved

**Comment by srirambv** [comment]
This looks fixed to me on 0.55.12 on both Linux and Windows. Default search engine shown when typing search term in URL is DDG. 

@kjozwiak @LaurenWags to confirm once on macOS. 

Can this be closed ?

**Comment by yrliou** [comment]
@srirambv 
Right now DDG is the default search engine in Tor on all platforms, we didn't close this because users should be able to change their search engines provider in Tor per https://github.com/brave/brave-browser/issues/1226#issuecomment-426696785.
We could probably open a specific issue for the ability to change the search engine in Tor to avoid confusion here. (And one for qwant part too)

**Comment by srirambv** [comment]
Agreed. DDG is default similar to b-l. so this can be closed and new issue can be logged for user settings for search engines in Tor windows.

**Comment by kjozwiak** [comment]
> @kjozwiak @LaurenWags to confirm once on macOS.

Yup, same results on macOS. Thanks for checking Win/Linux @srirambv! Going to add the appropriate flags and close this off as discussed above.

Also created the following issues:

> We could probably open a specific issue for the ability to change the default search engine in Tor to avoid confusion here.

Created https://github.com/brave/brave-browser/issues/1513

> Qwant for France & Germany should be posted as different issue because it is not tor specific but applies for all profiles

Created https://github.com/brave/brave-browser/issues/1514

@yrliou please feel free to re-open if something was missed 👍
