### ISSUE TITLE
Cannot make Brave the default browser on Linux

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#1274]
## Steps to Reproduce

   1. Go to chrome://settings/
   2. Scroll to `Default browser`
   3. Click `Make default`
   4. Open a file explorer and open a html file

## Actual result:

Nothing happens. 
The browser is not made default
File is not opened

## Expected result:
The `Make default` disappears (like on other platforms)
![image](https://user-images.githubusercontent.com/34715963/46041295-b7155200-c112-11e8-82a8-76eee3adcca2.png)

Brave is made the default browser
File is opened

## Reproduces how often: 

always

## Brave version (chrome://version info)

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev(64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

Tested on Ubuntu 17.10

### Reproducible on current release:

Brave | 0.55.6 Chromium: 70.0.3538.16 (Official Build) dev(64-bit)
-- | --
Revision | 16ed95b41bb05e565b11fb66ac33c660b721f778-refs/branch-heads/3538@{#306}
OS | Linux

cc @srirambv @kjozwiak @LaurenWags @GeetaSarvadnya

**Comment by capouch** [comment]
This problem is also on Slackware-current.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/cannot-set-brave-as-default-browser/34661

**Comment by IdlePhysicist** [comment]
Has this fix been released in the stable build yet? I'm experiencing this on 
- ArchLabs 2019.20 
- Brave Version 0.65.121 Chromium: 75.0.3770.100 (Official Build) unknown (64-bit)

I'm assuming that is has been fully merged & released based on this issue being closed, indicating the matter was resolved. But after adjusting each setting I can find to make Brave the default, Brave continually asks me on launch to set it to default.

**Comment by ryanmusante** [comment]
I am having this issue also. How do permanently set default?

**Comment by davemint** [comment]
Still an issue for me too. 

Version 0.65.114 Chromium: 75.0.3770.38 (Official Build) unknown (64-bit)

**Comment by kjozwiak** [comment]
This has been merged/fixed a while ago and released in `0.59.x`. The current release is on `0.66.99` so it's been a while. Definitely possible that this might have regressed on certain distro's.

@ryanmusante & @davemint which distro's are you two using?

**Comment by davemint** [comment]
> This has been merged/fixed a while ago and released in `0.59.x`. The current release is on `0.66.99` so it's been a while. Definitely possible that this might have regressed on certain distro's.
> 
> @ryanmusante & @davemint which distro's are you two using?

Manjaro 18.0.4

**Comment by ryanmusante** [comment]
Manjaro 18 (testing branch)

**Comment by salifm** [comment]
Same issue. Version 0.66.100 Chromium: 75.0.3770.142 (Official Build) Arch Linux (64-bit)

**Comment by anoop-ananthan** [comment]
Same issue here :disappointed:

**Comment by srirambv** [comment]
This works fine on Ubuntu. Making it default in settings sets it as system default browser. Issue could be specific to Arch Linux as we don't have an official package there. @cg505 I believe you run Arch Linux as well. Could you double-check this and log a new issue for it and mark it as Arch specific?

**Comment by cg505** [comment]
This is definitely broken on Arch. I'll see if I can take a look.

**Comment by cg505** [comment]
This is caused by a packaging error on the Arch side of things. I'll let the maintainers know.

**Comment by kjozwiak** [comment]
@cg505 thanks for looking into it! Once you have more information, mind updating this issue or maybe creating another one where we can follow progress?

**Comment by cg505** [comment]
@kjozwiak This should be fixed in the unofficial Arch User Repository packages (https://aur.archlinux.org/cgit/aur.git/commit/?h=brave-bin&id=571d9fb9fde822cdbcc79eb118cb772455ca62ae for `brave-bin` and https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=brave&id=e63f13ba4e458f3f55a14e443c9591a7b7305521 / maximbaz/pkgbuilds#7 for `brave`). Majaro and other Arch-based repos should be using these packages as well.

**Comment by corecontingency** [comment]
@cg505 Still seems to be broken for me. Brave is set as the default browser, but Brave still asks me to set it as default every time I open it. Pressing on the Make Default button in Brave does nothing. Using Arch with KDE and wayland, but still broken if I use a X11 session. Using `brave-bin` package from AUR. 

I don't have any custom desktop files for brave in `~/.local/share/applications`.

[Picture is attached.](https://drive.google.com/open?id=14JtfNEH38nIUfgPgMQJziObhROYueJyO)

**Comment by cg505** [comment]
@corecontingency What is the output of these two commands?

```
pacman -Qi brave-bin
ls -l /usr/share/applications | grep brave
```

Also, what version does brave report in brave://version?

**Comment by corecontingency** [comment]
@cg505 

> pacman -Qi brave-bin

```
Name            : brave-bin
Version         : 0.68.132-1
Description     : Web browser that blocks ads and trackers by default (binary release).
Architecture    : x86_64
URL             : https://brave.com/download
Licenses        : custom
Groups          : None
Provides        : brave  brave-browser
Depends On      : gtk3  nss  alsa-lib  libxss  ttf-font
Optional Deps   : cups: Printer support [installed]
                  pepper-flash: Adobe Flash support
                  libgnome-keyring: Enable GNOME keyring support
Required By     : None
Optional For    : None
Conflicts With  : brave
Replaces        : None
Installed Size  : 228.24 MiB
Packager        : Unknown Packager
Build Date      : Mon 02 Sep 2019 11:53:41 PM MST
Install Date    : Mon 02 Sep 2019 11:55:28 PM MST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```
This is the normal AUR package. I installed it using `yay`, but has the same problem even if using makepkg.

> ls -l /usr/share/applications | grep brave

-rw-r--r-- 1 root    root    4972 Sep  2 23:53 brave-browser.desktop

> Also, what version does brave report in brave://version?

```
Brave | 0.68.132 Chromium: 76.0.3809.132 (Official Build) unknown (64-bit)
-- | --
Revision | fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
```

Is there any setting to make it stop asking to be the default browser outright, like Firefox has? I looked in the settings, but couldn't find anything. Is there an about:config (equivalent) setting that I can flip?

**Comment by cg505** [comment]
@corecontingency Do you have `xdg-utils` installed? You can check by running `pacman -Q xdg-utils`

**Comment by corecontingency** [comment]
@cg505 

> pacman -Q xdg-utils

`xdg-utils 1.1.3+18+g0547886-1`

Yes. Would it help if I uninstalled, and then reinstalled `xdg-utils`, using `pacman -Rns` to wipe config files? Are there any config files in the $HOME directory I would need to manually remove too?

**Comment by cg505** [comment]
That's definitely a bit weird. The notable file would have been `~/.config/mimeapps.list`. Regardless, glad you got it resolved.

**Comment by arnholm** [comment]
I have this problem under Kubuntu 18.04, Brave is set as default browser in KDE and in Brave settings, but  when Brave is started, it claims Brave is not default and ask me to press a button to make it default, but nothing ever happens.

Brave	1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
Revision	ce7134bb3d95141cd18f1e65772a4247f282d950-refs/branch-heads/4103@{#694}
OS	Linux

**Comment by fmarier** [comment]
For Arch users, we are aware of the issue and are tracking it separately here: https://github.com/brave/brave-browser/issues/2377

@arnholm For Ubuntu, here are a few things you could check to make sure that Brave is set as default correctly: https://feeding.cloud.geek.nz/posts/set-default-web-browser-debian-ubuntu/

**Comment by arnholm** [comment]
@fmarier thank you for the Ubuntu tip. I followed all of those steps, but Brave still claims it isn't the default browser. Most things seem to work fine, the Brave browser does start as expected, but I still get the "Brave isn't your default browser". Pressing "Set as default" has no effect.

I am now on Brave Version 1.13.86 Chromium: 85.0.4183.102 (Official Build) (64-bit)
Kubuntu 18.04

**Comment by verndog** [comment]
I used all the above answers to no avail. An obscure comment somewhere suggested using this:
` xdg-mime default brave-browser-nightly.desktop x-scheme-handler/https x-scheme-handler/http
`It worked for me every time!
(change "nightly" to what brave your using)

**Comment by chyandour5** [comment]
This may be a possible fix for some, it worked for me. [https://discuss.getsol.us/d/5550-default-web-browser](url)

**Comment by fmarier** [comment]
> This may be a possible fix for some, it worked for me. https://discuss.getsol.us/d/5550-default-web-browser

Thanks for the link @chyandour5 . That particular problem seems specific to the unofficial Solus packages.

**Comment by cept73** [comment]
Same issue on Ubuntu 20.04.1 LTC. 

Brave was installed via snap.
If I delete second browser - Firefox, Brave became default browser, but every time on start asks to set Brave as default. 
I didn't found where to disable this check (to devs: need to return this option).
If I've installed FF again, FF became default. 

`sudo update-alternatives --config gnome-www-browser`
gives: no alternatives for gnome-www-browser

**Comment by fmarier** [comment]
@cept73 Could you please open a new issue for this. It seems to be snap-specific (I use our official packages on 20.04 without problems) and so we should track that issue separately from this one.

**Comment by vinnyfs89** [comment]
If are you using **Brave Nightly** follow these steps:

```sh
xdg-mime default brave-browser-nightly.desktop x-scheme-handler/https
xdg-mime default brave-browser-nightly.desktop x-scheme-handler/http
xdg-settings set default-web-browser brave-browser-nightly.desktop
```

Hope it helps 👍

https://vinnyfs89.gitbook.io/knowledge/technology/browser/chrome-or-brave/known-issues#set-brave-nightly-as-default-browser-using-linux

**Comment by AndreTrinLove** [comment]
(SOLVED)
I just went on:
Settings - Default apps.. - Web - brave.

![Screenshot from 2022-01-23 08-44-42](https://user-images.githubusercontent.com/98252066/150669470-c9ffe8d8-1c20-4b28-87d8-a92b0786389d.png)


..(PS)..
My linux is Zorin 16 OS (ubuntu)
I'm new here and it is my first time trying to help.
So, i'm sorry for any mistakes or obvious noob moves, in advance.

**Comment by DoughMucker** [comment]
Had the same issue in Lubuntu 22.04. Here's what, counterintuitively, fixed it for me...

Firefox was still my default though I had uninstalled it...
```
$ xdg-settings get default-web-browser
firefox.desktop
```

Tried changing it to Brave with no luck....
```
$ xdg-settings set default-web-browser brave-browser.desktop
xdg-settings: $BROWSER is set and can't be changed with xdg-settings
```

So I tried setting firefox again as the default... 
```
$ xdg-settings set default-web-browser firefox.desktop
xdg-settings: $BROWSER is set and can't be changed with xdg-settings
```

And it worked...
```
$ xdg-settings get default-web-browser
brave-browser.desktop
```

Go figure. I can't guarantee it was exclusively that as I had also been messing around with mimetypes, but that was the last thing I tried before Brave stopped asking me to set it as the default browser.
