### ISSUE TITLE
Shield icon is disappeared or reversed when switching between the tabs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13360]
## Description 

Shield icon is disappeared or reversed when switching between the tabs

## Steps to Reproduce

   1. Clean profile 1.19.69
   2. Enable rewards (enabled from BR panel)
   3. Open a few sites and switch between the tabs
   4. Shield icon is disappeared or reversed when switching between the tabs

## Actual result:

![image](https://user-images.githubusercontent.com/38657976/103537019-93c4da00-4eb9-11eb-8da7-8aa83f685943.png)
![image](https://user-images.githubusercontent.com/38657976/103537034-a0e1c900-4eb9-11eb-8c6d-cb431a35d024.png)
![image](https://user-images.githubusercontent.com/38657976/103537114-cc64b380-4eb9-11eb-9866-4d3a6fafd31d.png)

## Expected result:

Shield icon shouldn't disappear or reverse when switching between the tabs
## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave	1.19.69 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
Revision	9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS	Linux

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? Not sure

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @rebron

**Comment by LaurenWags** [comment]
@GeetaSarvadnya can you reproduce on Windows? I am unable to reproduce on macOS using below build:


Brave | 1.19.73 Chromium: 87.0.4280.101 (Official Build) dev (x86_64)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | macOS Version 10.15.7 (Build 19H15)

**Comment by GeetaSarvadnya** [comment]
I am unable to reproduce the issue in Windows 10 x64  - `1.19.69` and `1.19.73`

**Comment by LaurenWags** [comment]
ok, labelling as `OS/Linux` since you can't reproduce on Windows and I can't reproduce on macOS

**Comment by GeetaSarvadnya** [comment]
BAT logo is also missing in the URL bar. Verified in `1.19.73`
![image](https://user-images.githubusercontent.com/38657976/103546003-5f0c4f00-4ec8-11eb-8351-4e390aa917da.png)

**Comment by kjozwiak** [comment]
hmm strange! I tried the above on my `Mint 19.1 x64` laptop and couldn't reproduce the issue. Is there anything specific that needs to be done @GeetaSarvadnya? I basically followed the STR from https://github.com/brave/brave-browser/issues/13360#issue-778092985.

Wonder if it's due to Mint running in a VM? @rebron believe you have a Linux laptop laying around, can you reproduce the above?

Used the following builds:

```
Brave | 1.19.72 Chromium: 87.0.4280.101 (Official Build) beta (64-bit)
--- | ---
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Linux
```

```
kjozwiak@kjozwiak-XPS15:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tes
```

**Comment by kjozwiak** [comment]
@srirambv mind checking to see if you can reproduce this as you're on Linux as well? If the above is a real problem, we'll need to get this fixed in `1.19.x`. Can't ship with the above regression.

**Comment by srirambv** [comment]
Can't reproduce the issue on 1.19.67 on Linux. Followed the steps from issue description and can't repro it. Suspect its a VM issue as the shield icon is not loaded on the second screenshot

**Comment by btlechowski** [comment]
Works for me. I have been working on Linux past 2 days and did not observe such issue.

Brave | 1.19.73 Chromium: 87.0.4280.101 (Official Build) dev (64-bit)
-- | --
Revision | 9407c80213cda69c2b7abcb4fa8e3f74488f4956-refs/branch-heads/4280@{#1807}
OS | Ubuntu 18.04 LTS

@GeetaSarvadnya Have you tried reinstalling Brave?

**Comment by GeetaSarvadnya** [comment]
@btlechowski Ye, I have tried re-installing brave, the issue is still reproducible. Just now I have tried installing brave dev latest version 1.19.76, I can reproduce the issue in this version as well.

**Comment by kjozwiak** [comment]
I installed the latest `Ubuntu` on my psychical laptop and couldn't reproduce the above either. Tried several times with old/new profiles. As mentioned above, I suspect this is probably a VM issue of some type. I guess we'll see if anyone else eventually runs into this as it's a pretty obvious/easy to spot issue.

 ```
 kjozwiak@kjozwiak-XPS:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

```
Brave | 1.19.86 Chromium: 88.0.4324.96 (Official Build) (64-bit)
--- | ---
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Linux
```
