### ISSUE TITLE
Users are not rewarded for viewing an NTP SI until the browser is restarted

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#13815]
## Description 

Users are not rewarded for viewing an NTP SI until the browser is restarted. 

## Steps to Reproduce

Scenario 1:
   1. Clean profile `1.19.86`
   2. Enable rewards & Ads via brave://rewards
   3. Upgrade to `1.19.88`
   4. View an NTP SI
   5. Users are not rewarded for viewing NTP SI
   6. Restart the browser fixes the issue
   
Scenario 2:
   1. Clean profile `1.19.86`
   2. Enable rewards and disable Ads
   3. Upgrade to `1.19.88` and enable Ads
   4. View an NTP SI
   5. Users are not rewarded for viewing NTP SI
   6. Restart the browser fixes the issue

Note: Restart browser fixes the issue only for US locale not for India   
## Actual result:

Users are not rewarded for viewing an NTP SI until the browser is restarted

```
[14580:13968:0128/183408.571:INFO:creative_new_tab_page_ads_database_table.cc(426)] Failed to get creative new tab page ad
[14580:13968:0128/183408.571:VERBOSE1:new_tab_page_ad.cc(77)] Failed to fire new tab page ad event for wallpaper id
```

## Expected result:
Users should be rewarded for viewing an NTP SI without a browser restart

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Windows 10 OS Version 2004 (Build 19041.746)

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? No
- Can you reproduce this issue with the nightly channel? No

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

cc: @brave/legacy_qa @tmancey @jsecretan @rebron 

Issue is Reproduced by @btlechowski for poland region

**Comment by btlechowski** [comment]
Reproduced on Linux

Brave | 1.20.88 Chromium: 88.0.4324.96 (Official Build) dev (64-bit)
-- | --
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | Ubuntu 18.04 LTS

<details>
<summary>NTP SI logs</summary>

Was not rewarded for NTP SI
```
[7494:7494:0128/151803.807719:INFO:creative_new_tab_page_ads_database_table.cc(426)] Failed to get creative new tab page ad
[7494:7494:0128/151803.808073:VERBOSE1:new_tab_page_ad.cc(77)] Failed to fire new tab page ad event for wallpaper id
```

Issue was fixed after browser restart
```
[14159:14159:0128/160959.141510:VERBOSE3:new_tab_page_ad_event_viewed.cc(26)] Viewed new tab page ad with uuid 76b82841-9786-4ed8-bfdc-ea0bddef1cdc and creative instance id ae0843a5-2859-45ed-be26-b91bd08420b4

```

</details>

<details>
<summary>Ad notification logs</summary>

Was unable to view ads
```
[7494:7494:0128/152037.687266:VERBOSE1:ad_notification_serving.cc(242)] No eligible ads found for untargeted category
[7494:7494:0128/152037.687338:VERBOSE1:ad_notification_serving.cc(243)] Ad notification not served: No eligible ads found
```

Issue was fixed after browser restart
```
[14159:14159:0128/161126.889501:VERBOSE1:ad_notification_serving.cc(98)] Ad notification delivered:
  uuid: 74e5e773-5f53-49a3-b135-ee32de5d2fa6
  creativeInstanceId: e5a7f7d5-b93d-443e-ab07-21fcf096bb83
  creativeSetId: dce1b0d8-cf10-410e-936f-96b2a0b84e00
  campaignId: 028af44e-dca7-4f50-97b0-31b2aa8d0bcc
  category: untargeted
  title: Nexo 12% Fiat Savings Account
  body: Enjoy up to 12% APY on your USD, EUR and GBP with Nexo.
```
</details>

**Comment by kjozwiak** [comment]
Reproduced on `macOS 11.1 x64` as well after upgrading from `1.19.86 CR: 88.0.4324.96` to `1.19.88 CR: 88.0.4324.96`. Another quick work around is disabling/enabling again rather than restarting the browser. Reproduced using the following:

```
Brave | 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)
--- | ---
Revision | 68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}
OS | macOS Version 11.1 (Build 20C69)
```

Provided @tmancey a full log via Slack as well.

**Comment by srirambv** [comment]
+1 on Linux

**Comment by tmancey** [comment]
This issue will occur if the database is migrated. We need to clear the following prefs:
```
brave.brave_ads.catalog_id
brave.brave_ads.catalog_version
brave.brave_ads.catalog_ping
brave.brave_ads.catalog_last_updated
```

**Comment by GeetaSarvadnya** [comment]
I can still reproduce the issue on both RC (1.32.113) and Beta (1.33.90) channels. Restarting the browser doesn't fix the issue. The issue is verified on the clean profile for the US region.

```
[16532:11216:1129/203720.522:INFO:creative_new_tab_page_ads_database_table.cc(523)] Failed to get creative new tab page ad
[16532:11216:1129/203720.523:VERBOSE1:new_tab_page_ad.cc(64)] Failed to fire new tab page ad event due to missing creative instance id 4995fecd-90a0-4a4b-bd9d-63a5734b2375
[16532:11216:1129/203720.524:VERBOSE1:ads_impl.cc(816)] Failed to fire new tab page ad kViewed event for uuid da4cc601-1a6a-4444-bab8-a7390b0cd9df and creative instance id 4995fecd-90a0-4a4b-bd9d-63a5734b2375
[16532:11216:1129/203720.527:VERBOSE2:tab_manager.cc(77)] Tab id 20 was updated
```

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.39.87 Chromium: 101.0.4951.41 (Official Build) beta (64-bit)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | Ubuntu 18.04 LTS



Important: OS locale and actual geolocation need to be the same, for example: US locale and US based IP.
Important: Make sure unblinded tokens are fetched from the server before checking if user was paid for the ad

#### Brave - ads enabled, catalog downloaded before upgrade from 1.38.x
Verified catalog was downloaded after upgrade to 1.39.x
```
[4211:4211:0502/151214.490315:VERBOSE1:ad_server.cc(80)] OnGetCatalog
[4211:4211:0502/151214.490465:VERBOSE1:ad_server.cc(88)] Successfully fetched catalog
[4211:4211:0502/151214.490511:VERBOSE1:ad_server.cc(90)] Parsing catalog
```

Verified NTPSI was shown
![image](https://user-images.githubusercontent.com/34715963/166239465-865ace20-1372-4c26-82ef-4b06123815fb.png)


Verified user was paid for the NTPSI
```
[4211:4211:0502/151248.540240:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id 6fd21432-4fa3-4d12-852f-fd3aa177419e and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[4211:4211:0502/151248.559224:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
[4211:4211:0502/151248.559560:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id 6fd21432-4fa3-4d12-852f-fd3aa177419e and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[4211:4211:0502/151248.579238:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb and view valued at 0.01
[4211:4211:0502/151248.579360:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id 39cd7989-0c54-482e-af89-65755aa8ba90 and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[4211:4211:0502/151325.981713:VERBOSE1:confirmations.cc(296)] Successfully redeemed unblinded token for new_tab_page_ad with confirmation id 4ab29ff8-1cf5-4423-93e2-3daad590fc8c, transaction id 39cd7989-0c54-482e-af89-65755aa8ba90, creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb and view.
```

#### Brave - ads enabled, catalog not downloaded before upgrade from 1.38.x

Made sure that catalog was not downloaded on 1.38.x by overriding the response code 200->500
```
[6881:6881:0502/164949.893966:VERBOSE1:ad_server.cc(81)] OnGetCatalog
[6881:6881:0502/164949.895121:VERBOSE1:ad_server.cc(111)] Failed to parse catalog
```

Verified catalog was downloaded after upgrade to 1.39.x
```
[8091:8091:0502/165937.207326:VERBOSE1:ad_server.cc(80)] OnGetCatalog
[8091:8091:0502/165937.207501:VERBOSE1:ad_server.cc(88)] Successfully fetched catalog
[8091:8091:0502/165937.207557:VERBOSE1:ad_server.cc(90)] Parsing catalog
```

Verified NTPSI was shown
![image](https://user-images.githubusercontent.com/34715963/166257274-fc766a04-1039-4313-8eb9-7a7c1a8fb121.png)

Verified user was paid for the NTPSI
```
[8091:8091:0502/170309.887129:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id 4c249904-072b-445e-b2a4-69aaeb38ec06 and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[8091:8091:0502/170309.915907:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
[8091:8091:0502/170309.933982:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id 4c249904-072b-445e-b2a4-69aaeb38ec06 and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[8091:8091:0502/170309.971324:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb and view valued at 0.01
[8091:8091:0502/170309.971423:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id e973381c-ca5e-42ac-addd-8cd4a6a7a09a and creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb
[8091:8091:0502/170325.164604:VERBOSE1:confirmations.cc(296)] Successfully redeemed unblinded token for new_tab_page_ad with confirmation id 522f44fc-2935-414f-baa7-cfa07edc4dcc, transaction id e973381c-ca5e-42ac-addd-8cd4a6a7a09a, creative instance id 7b710122-1ec3-4073-8e6b-45b9f85f70bb and view.
```

#### Brave - ads enabled, catalog downloaded before upgrade from 1.19.86
Installed 1.19.86 and enabled rewards and ads
Because it is an old version, catalog failed to parse:
```
[9123:9123:0502/174732.953963:VERBOSE1:ad_server.cc(109)] Failed to parse catalog
```
Also the wallet failed to be created.

Verified catalog was downloaded after upgrade to 1.39.x
```
[9428:9428:0502/175033.440890:VERBOSE1:ad_server.cc(80)] OnGetCatalog
[9428:9428:0502/175033.441124:VERBOSE1:ad_server.cc(88)] Successfully fetched catalog
[9428:9428:0502/175033.441224:VERBOSE1:ad_server.cc(90)] Parsing catalog
```

I was unable to view ads due to unblinded tokens not being downloaded. Logged https://github.com/brave/brave-browser/issues/22654
```
[9428:9428:0502/175033.529794:INFO:refill_unblinded_tokens.cc(88)] Failed to refill unblinded tokens due to an invalid wallet

```

**Comment by btlechowski** [comment]
Added `QA/Test-All-Platforms` back. When testing please use different locales than previous verifications.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.39.89 Chromium: 101.0.4951.41 (Official Build) beta (x86_64)
-- | --
Revision | 93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}
OS | macOS Version 12.3.1 (Build 21E258)
```

**Comment by MadhaviSeelam** [comment]
Verified `In-Progress` using
```
Brave | 1.39.101 Chromium: 101.0.4951.64 (Official Build) beta (64-bit)
-- | --
Revision | d1daa9897e1bc1d507d6be8f2346e377e5505905-refs/branch-heads/4951@{#1208}
OS | Windows 11 Version 21H2 (Build 22000.613)
```
<details>
<summary>Brave - ads enabled, catalog downloaded before upgrade from 1.38.x - PASSED</summary>

Verified catalog was downloaded after upgrade to 1.39.x
```
[6976:4344:0512/081333.886:VERBOSE1:ad_server.cc(80)] OnGetCatalog
[6976:4344:0512/081333.887:VERBOSE1:ad_server.cc(88)] Successfully fetched catalog
[6976:4344:0512/081333.887:VERBOSE1:ad_server.cc(90)] Parsing catalog
```
Verified NTPSI was shown

<img width="750" alt="ntpsi" src="https://user-images.githubusercontent.com/98358127/168171475-67c7083a-2142-44d1-8f4f-500834b55867.png">

Verified user was paid for the NTPSI
```
[21752:10376:0512/100830.059:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id 47c415eb-5c95-40a5-aa70-5f369281cf2a and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
.........
[21752:10376:0512/100830.073:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
.........
[21752:10376:0512/100830.079:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id 47c415eb-5c95-40a5-aa70-5f369281cf2a and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
[21752:10376:0512/100830.082:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9 and view valued at 0.01
[21752:10376:0512/100830.082:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id 63b92053-2519-4a54-9174-8ddcfed0768c and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
.........
[21752:10376:0512/100830.085:VERBOSE6:new_tab_page_ad_event_served.cc(31)] Successfully logged new tab page ad served event
.........
[21752:10376:0512/100830.082:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id 63b92053-2519-4a54-9174-8ddcfed0768c and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
```
</details>

<details>
<summary>Brave - ads enabled, catalog not downloaded before upgrade from 1.38.x - PASSED</summary>

Made sure that catalog was not downloaded on 1.38.x by overriding the response code 200->500
```  
[23400:26184:0512/130436.789:VERBOSE1:ad_server.cc(81)] OnGetCatalog
[23400:26184:0512/130436.789:VERBOSE1:ad_server.cc(111)] Failed to parse catalog
```
Verified catalog was downloaded after upgrade to 1.39.x
```
[16132:26880:0512/144719.869:VERBOSE1:ad_server.cc(80)] OnGetCatalog
[16132:26880:0512/144719.869:VERBOSE1:ad_server.cc(88)] Successfully fetched catalog
[16132:26880:0512/144719.870:VERBOSE1:ad_server.cc(90)] Parsing catalog
```
Verified NTPSI was shown
<img width="944" alt="ntpsi2" src="https://user-images.githubusercontent.com/98358127/168173831-2c4d7d4f-6cfe-4925-90a1-a73306f91a09.png">

Verified user was paid for the NTPSI

```
[16132:26880:0512/144934.403:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id c0e996a4-65b9-4da3-9620-39874be403f6 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
..........
[16132:26880:0512/144934.407:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
..........
[16132:26880:0512/144934.413:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id c0e996a4-65b9-4da3-9620-39874be403f6 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
[16132:26880:0512/144934.416:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9 and view valued at 0.01
[16132:26880:0512/144934.416:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id f4f80596-bcf5-4ccc-9549-c5c3b1307439 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
..........
[16132:26880:0512/144940.807:VERBOSE1:confirmations.cc(296)] Successfully redeemed unblinded token for new_tab_page_ad with confirmation id 6e6aafae-572a-4f37-a762-b0efe6d9a9c2, transaction id f4f80596-bcf5-4ccc-9549-c5c3b1307439, creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9 and view. You now have 1 unblinded payment tokens which will be redeemed in 8 hours, 12 minutes, 25 seconds at 23:02:05.737
```

</details>


<details>
<summary>Brave - ads re-enabled, catalog downloaded before upgrade from 1.38.x - PASSED</summary>

in 1.38.x:
```
[8252:15612:0512/110043.323:VERBOSE1:ads_service_impl.cc(707)] Shutting down ads
[8252:15612:0512/110043.327:VERBOSE1:ads_service_impl.cc(723)] Successfully shutdown ads
```

Verified user was paid for the NTPSI
```
[23196:9540:0512/110431.597:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id 6af20545-bddb-4100-829d-290981ca6626 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
........
[23196:9540:0512/110431.611:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
........
[23196:9540:0512/110431.618:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id 6af20545-bddb-4100-829d-290981ca6626 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
[23196:9540:0512/110431.622:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9 and view valued at 0.01
[23196:9540:0512/110431.622:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id f98ab886-061c-4ec6-ba49-d141c68abf95 and creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9
........
[23196:9540:0512/110434.183:VERBOSE1:confirmations.cc(296)] Successfully redeemed unblinded token for new_tab_page_ad with confirmation id db782ba8-3931-4af4-83c9-567ffb87bd9e, transaction id f98ab886-061c-4ec6-ba49-d141c68abf95, creative instance id e31b56de-023b-489f-89e0-afdbfd2e41e9 and view. You now have 2 unblinded payment tokens which will be redeemed in 0 hours, 0 minutes, 0 seconds at 11:04:25.855
```
</details>

<details>
<summary>Brave - ads re-enabled, catalog not downloaded before upgrade from 1.38.x - PASSED</summary>

Made sure that catalog was not downloaded on 1.38.x by overriding the response code 200->500

```
[24444:23464:0512/142848.581:VERBOSE1:ad_server.cc(81)] OnGetCatalog
[24444:23464:0512/142848.582:VERBOSE1:ad_server.cc(111)] Failed to parse catalog
```
In 1.38.x
```
[19380:14608:0512/153110.141:VERBOSE1:ads_service_impl.cc(706)] Shutting down ads
[19380:14608:0512/153110.142:VERBOSE1:ads_service_impl.cc(722)] Successfully shutdown ads
```
Verified user was paid for the NTPSI after upgrade
```
[17192:15544:0512/153721.231:VERBOSE3:new_tab_page_ad_event_viewed.cc(23)] Viewed new tab page ad with placement id 775dbdb7-7dcd-4b94-b566-e40beb762164 and creative instance id 5898b093-a173-4530-93aa-a2a3e9523217
........
[17192:15544:0512/153721.236:VERBOSE6:new_tab_page_ad_event_viewed.cc(31)] Successfully logged new tab page ad viewed event
........
[17192:15544:0512/153721.244:VERBOSE3:new_tab_page_ad_event_served.cc(23)] Served new tab page ad with placement id 775dbdb7-7dcd-4b94-b566-e40beb762164 and creative instance id 5898b093-a173-4530-93aa-a2a3e9523217
[17192:15544:0512/153721.248:VERBOSE3:ads_impl.cc(807)] Successfully processed deposit for new_tab_page_ad with creative instance id 5898b093-a173-4530-93aa-a2a3e9523217 and view valued at 0.01
[17192:15544:0512/153721.248:VERBOSE1:confirmations.cc(60)] Confirming view for new_tab_page_ad with transaction id 8bd2561c-59b9-4087-b5fe-46176f20dd88 and creative instance id 5898b093-a173-4530-93aa-a2a3e9523217
........
[17192:15544:0512/153747.257:VERBOSE1:confirmations.cc(296)] Successfully redeemed unblinded token for new_tab_page_ad with confirmation id fefe469f-8b82-4f3f-be39-46d9aab7796c, transaction id 8bd2561c-59b9-4087-b5fe-46176f20dd88, creative instance id 5898b093-a173-4530-93aa-a2a3e9523217 and view. You now have 1 unblinded payment tokens which will be redeemed in 0 hours, 0 minutes, 0 seconds at 15:35:57.159
```

</details>



<details>
<summary>Brave - ads enabled, catalog downloaded before upgrade from 1.19.86 - PASSED</summary>
