### ISSUE TITLE
Keeps asking to set it as default browser - Forever Loop - Won't accept no!

### ISSUE THREAD

**Issue by desmonk** [brave/brave-browser#14530]
## Description 
I think recent update change made this issue. I am in a permanent incognito mode with strict settings not to allow any site to save settings. This I am thinking also broke the browser setting where it "forgets" that user has denied the permission to set it as a default browser.

## Steps to Reproduce

   1.  Install Brave browser latest stable release.
   2.  Change settings to block fingerprinting, device recognition, third party cookies. 
   3.  I start with incognito argument so always go into incognito mode.
   4.  Start the program, will always ask to set it as default even when you deny it.
   5.  Issue stays even with shields disabled, allowing cookies and fingerprinting.

## Actual result:

![IMG_040](https://user-images.githubusercontent.com/55331939/110209318-b9536d00-7e83-11eb-8857-b495344449ce.gif)

## Expected result:
Should accept a no to setting it up as a default.

## Reproduces how often: 

Easily reproducible.

## Brave version (brave://version info)

Version 1.21.73 Chromium: 89.0.4389.72 (Official Build) (64-bit)

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes.
- Can you reproduce this issue with the beta channel? Not tested.
- Can you reproduce this issue with the nightly channel? Not tested.

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

Started recently on all my systems so might be a recent release has caused this issue.

**Comment by gingsi** [comment]
Can confirm, asks to be default browser on every start and no "never ask again" button anywhere, not in the dialog and not in the settings.

Really hoping this is a bug and not a design choice, it is terribly annoying.

**Comment by ledufff** [comment]
I accepted it by mistake.  Was it intended or a bug?
Please fix this ASAP.

**Comment by da2x** [comment]
[This commit](https://github.com/brave/brave-core/commit/95f3ac32dbcc9a946d86b10fe2daf18d4ae6b442#diff-09482da4177fec7a87c6175081b9caee936cfd4f8f9781b3548cbb0f5c8da231) by @emerick suggests that Brave isn’t intended to ask on every start-up.

**Comment by ryanbr** [comment]
This was resolved in the latest ver, update Brave to `1.21.74`  @desmonk @gingsi  @ledufff  @da2x   Just force an update via `brave://settings/help`

**Comment by desmonk** [comment]
Problem solved and that was so quick. All my machines now back to duty.
Thank you guys very much!

**Comment by ledufff** [comment]
uh...  am I the only one with this bug reproducing again?

**Comment by SaiWebApps** [comment]
@leduff - No, you're not the only one.
I have also started encountering this dialog once again, starting today morning. I am using Brave Browser version 1.21.77.

**Comment by gingsi** [comment]
Just updated to 1.22.67 and it asked me again after the update. Seems this was not fixed by this update

**Comment by rebron** [comment]
@gingsi @ledufff Are you launching into Brave normally or are you launching with special arguments? 

You should only see the dialog twice once at 3rd launch of the browser and again on 20th launch of the browser (if you hadn't set it).

**Comment by ledufff** [comment]
> @gingsi @ledufff Are you launching into Brave normally or are you launching with special arguments?
> 
> You should only see the dialog twice once at 3rd launch of the browser and again on 20th launch of the browser (if you hadn't set it).

I got '/usr/bin/brave-browser-stable -incognito' set to a keybinding.  I haven't seen it again,  but the last time happened three times in a row.  If I ever experience this again I will comment in this issue.

**Comment by gingsi** [comment]
> 
> 
> @gingsi @ledufff Are you launching into Brave normally or are you launching with special arguments?
> 
> You should only see the dialog twice once at 3rd launch of the browser and again on 20th launch of the browser (if you hadn't set it).

Regular launch, happened only once today, maybe this counter resets between updates or something. I had this installation for months now so it shouldn't keep asking

Maybe add the "don't ask again" button, that's how other browsers do it

**Comment by rebron** [comment]
We landed https://github.com/brave/brave-browser/issues/14469 in the latest 1.24.x a couple weeks ago in release channel.
Not seeing default browser prompt anymore right @gingsi and @desmonk with Do Not Ask button checked? 

cc: @emerick

**Comment by rebron** [comment]
@gingsi @desmonk Closing this one out due to #14469. We'll reopen if this remains an issue.
