### ISSUE TITLE
Can't download anything after upgrade to Monterey

### ISSUE THREAD

**Issue by dcervenkov** [brave/brave-browser#19442]
## Description 

After updating Macbook Air M1 to Monterey, Brave can no longer download any files. No error message is given and nothing seems to happen. After trying to download anything, when closing Brave at any time after that, a dialog appears saying "Download is in progress" and gives choice to either Quit or Continue Downloading. Clicking the Continue downloading button opens the downloads tab where no in-progress downloads are shown. 

## Steps to Reproduce

   1. Go to https://arxiv.org/pdf/2109.15248.pdf (the issue appears outside of the PDF viewer as well, e.g. at https://brave.com/download/)
   2. Click Download

## Actual result:

Nothing visible happens and the file is not downloaded.

## Expected result:

The file is downloaded.

## Reproduces how often: 

Easily reproduced (happens every time).

## Brave version (brave://version info)

Brave | 1.31.91 Chromium: 95.0.4638.69 (Official Build) (arm64)
-- | --
Revision | 6a1600ed572fedecd573b6c2b90a22fe6392a410-refs/branch-heads/4638@{#984}
OS | macOS Version 12.0.1 (Build 21A559)

## Version/Channel Information:

- It happens only in the current release; the beta works fine.

## Other Additional Information:

- The issue is not reproducible in Chrome.
- The issue is not resolved by using incognito mode.
- The issue is not resolved by disabling Brave Shields.
- The issue is not resolved by disabling Brave Rewards.

**Comment by woldtwerk** [comment]
can confirm that this is still a problem in the latest brave build

**Comment by jeffreygroneberg** [comment]
Still not working. Any progress here? Is this fixed in a nightly build?

**Comment by toobulkeh** [comment]
Downloads are broken for me too on the Intel Chipset.

**Comment by woldtwerk** [comment]
Just updated to 96.0.4664.93. Now I don't even get a save file dialog when I right click > save image as

**Comment by jeffreygroneberg** [comment]
Same here. Not sure where this should be fixed. But not in my version :) 
![image](https://user-images.githubusercontent.com/101954/146394946-ded9718a-e779-45b9-ac06-3c5439759e3e.png)

**Comment by PMcca** [comment]
Any update on this? Currently experiencing the same. Can't upload files either; the window doesn't show up.

**Comment by woldtwerk** [comment]
I think this might have been a macos bug. I had filesystem issue with vscode aswell. Couldn't use the open folder/file dialog.
Do you have the latest macos version?

**Comment by mcmike2099** [comment]
Hello, I'm still getting this issue in Brave 1.42.88, macOS 12.5.1.

Brave works great for a while. Then at some point (maybe after several days of use), it’ll stop accepting downloads and uploads. 

The issue seems to be that it can’t interact with the macOS file system. If I click a website link to download something, nothing happens. If I click a link to upload something, nothing happens. If I go to Settings > Downloads > Change to change the download location, nothing happens (because that should bring up Finder, which I think is the issue—whenever the browser has to interact with the file system). I can upload files when a website lets me drag them from Finder onto the webpage; it just doesn’t work when I click upload and it’s supposed to open the file system window to choose the file.

When I quit the browser, it pops up a window asking “Downloads are in progress. Quit anyway?” I tried canceling, then going to Downloads and clearing everything. When I try to quit the browser, the “Downloads are in progress” pops up anyway. And, I can see on the app badge in the taskbar that there’s a number indicating those downloads.

When I restart the browser, the issue is fixed (for a few days, then it happens again—this has been going on for weeks or months).

This issue happens even in a private window, and with extensions and anti-virus disabled. No errors in Dev Tools either.

Thanks!

**Comment by trevor-vardeman** [comment]
This is still happening to me, too, on the latest version of Brave. I have 1.43.89 installed on my 2021 MacBook Pro (14 in) with the Apple M1 Pro chip. Running Monterey version 12.3.1. It's been happening for months now. Anything to resolve this would be great. I have to open Chrome anytime I want to download anything.

**Comment by moritzWa** [comment]
I can't upload and download. 

Happening for me since yesterday. I'm running:
- [Version 1.43.89 Chromium: 105.0.5195.102 (Official Build) (arm64)](https://brave.com/latest/)
- macOs Monterey 12.0.1 (21A559)

Yesterday, I resolved the download problem by disabling: Ask where to save each file before downloading
Today, this doesn't fix the issue anymore.

**Comment by deepchandra02** [comment]
Issue is still occuring. It resolves everytime I quit and restart browser, and then 2 days later comes back. [Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (arm64)]

**Comment by etiennedupont** [comment]
Same issue here. Has any workaround been found?

**Comment by mattivilola** [comment]
Same issue still here. I need to restart the browser. Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) (arm64). macOS Monterey 12.6.8

**Comment by aosavi** [comment]
Same issue, but noticed that it occurs on multiple browsers.
Brave Version 1.61.114 Chromium: 120.0.6099.199 (Official Build) (x86_64)
Safari Version 17.2.1 (19617.1.17.11.12)
Firefox 121.0.1 (64-bit)
macOS 14.2.1 (23C71)

**Comment by kr3cj** [comment]
Same here. Restarting the browser is the only way I have found to get around it and it's temporary.
Brave: `Version 1.63.162 Chromium: 122.0.6261.69 (Official Build) (arm64)`
macos: Sonoma `14.3.1` (arm)

**Comment by bsclifton** [comment]
cc: @rebron for triage

**Comment by bsclifton** [comment]
Does anyone subscribed here still have this issue occur? I'm going to close this now - but we can re-open or make a new issue with more info if this is still something that happens.
