### ISSUE TITLE
Tab group resets or not working as expected after browser restart

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#19687]
## Description 
Tab group resets or not working as expected after browser restart. 

**Note**: The issue is reproducible when a tab group is created via the Tab group menu or via drag and drop sites option

## Steps to reproduce 
```
**Case 1:**
1. clean install GPS version `1.32.106`
2. Launch brave an NTP is opened (leave the NTP as is don't open any site in it)
3. Open and a new tab and tap on top tiles and open a site (repeat the same for all the 4 top tiles, at the end    4 sites should be opened in 4 new tabs)
4. open 5th site theverge.com in the 1st Tab which was left as is
5. add 4 sites to the tab group 
6. tap on the remaining site and exit brave via the hamburger menu
7. after sometimes (20 secs) relaunch brave, I could see only 3 sites in the tab group instead of 4 tabs

**Case 2:**
1. clean install GPS version `1.32.106`
2. Launch brave an NTP is opened (leave the NTP as is don't open any site in it)
3. Open and a new tab and tap on top tiles and open a site (repeat the same for all the 4 top tiles, at the end    4 sites should be opened in 4 new tabs)
4. Tap on tab group and select check box for all the 5 tabs and then uncheck NTP tab which was opened in step2
5. create a tab group for the remaining 4 tabs
6. tap on the remaining NTP tab and exit brave via the hamburger menu
7. after sometimes (20 secs) relaunch brave, I could see only 2 sites in the tab group instead of 4 tabs, 3 tabs are outside the group (including NTP (step2))

**Case 3:**
1. clean install GPS version `1.32.106`
2. launch brave, open theverge.com in the 1st NTP
3. open a new tab and tap on top tiles and open 4 sites in 4 new tabs
4. tap on tab group and add 4 sites to the tab group
5. tap on theverge.com and exit brave via the hamburger menu
6. after sometimes (20 secs) relaunch brave 4 tab group is lost, I could see all the tabs outside the group

**Case 4:**
1. clean install GPS version `1.32.106`
2. open a site1 on a new tab page
3. repeat step 2 and open 5 sites
4. add 4 sites to the tab group
5. tap on the 5th site and exist brave via the hamburger menu
6. relaunch brave after 20 sec, tab group is lost, I could see only 2 tabs in tab group 2 tabs are outside the tab group
```
## Actual result 

Tab group resets or not working as expected after browser restart

## Expected result
Tab group should be retained after browser restart

## Issue reproduces how often 
Easy

## Version/Channel Information:

- Can you reproduce this issue with the current Play Store version? Yes
- Can you reproduce this issue with the current Play Store Beta version? Not sure
- Can you reproduce this issue with the current Play Store Nightly version?Not sure

## Device details
   - Install type (ARM, x86): ARM
   - Device type (Phone, Tablet, Phablet): Vivo  X70 Pro
   - Android version: Android 11
   
## Brave version
1.32.106

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

cc: @SergeyZhukovsky @anthonypkeane @brave/legacy_qa

**Comment by samartnik** [comment]
I got slightly different issue, in may case the last 1-2 tabs, that were moved to a tab group, after closing and starting appeared outside of the tab group. The same behaviour I have in Chrome (here, instead of exit, I simply removed app from memory). Apparently tab groups require some time to commit changes and, if we close app before that, we have these issues. I suppose this should be fixed in the upstream.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind double checking to see if what you found is also reproducible on Chrome?

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible in `Chrome 96.0.4664.45` also but the reproducible rate is a bit less as compared to brave. But indeed issue occurs in chrome also

**Prerequisites**: 
Removed cache and storage from Apps->Chrome->Storage before every test case
Chrome doesn't have the `Exit` browser option via the Hamburger menu, hence removed app from memory instead of browser restart

I can reproduce the cases from https://github.com/brave/brave-browser/issues/19687#issue-1061556687

- Reproduced case1 from https://github.com/brave/brave-browser/issues/19687#issue-1061556687 in Chrome also, getting the same result as brave

- Reproduced case2 from https://github.com/brave/brave-browser/issues/19687#issue-1061556687 in Chrome also, getting the diff result in chrome, tab group is lost instead of 4 tab groups I could see only 3 tabs in a group after relaunch

- Reproduced case3 from https://github.com/brave/brave-browser/issues/19687#issue-1061556687 in Chrome also, getting the diff result in chrome, tab group is lost instead of 4 tab groups I could see only 2 tabs in a group after relaunch

- Reproduced case4 from https://github.com/brave/brave-browser/issues/19687#issue-1061556687 in Chrome also, getting the diff result in chrome, tab group is lost for all the tabs, no tab group after relaunch all the tabs are outside the tab group

Listed a few additional scenarios with which I can reproduce the issue consistently in chrome also.

**Case 1:** 
1. Clean profile chrome `Chrome 96.0.4664.45`
2. Open 4 sites in 4 new tabs 
3. Open the 5th tab but don't open any site in it
4. Create tab group of 2 tabs (drag and drop the tabs)
5. Create another tab group of 2 tabs, add a blank 5th tab with any other tab which has site opened in it
6. Remove the app from memory and relaunch chrome

**Actual**: Tab group is lost I could see 4 tabs outside the tab group (5th blank tab added in one of the tab groups is lost/not shown after the relaunch as it was blank, which could be the reason I am not sure) but 1st tab group (created in step 4) is also lost which is not expected.

**Case 2:** 

1. Clean profile chrome `Chrome 96.0.4664.45`
2. Open 7 sites in 7 new tabs 
3. Create tab group of 4 tabs (drag and drop the tabs)
4. Create another tab group of 2 tabs
5. Tap on the 7th tab 
6. Remove the app from memory and relaunch chrome

**Actual**: Both tab groups are lost (tab groups created in steps 3 and 4) I could see all the 7 tabs outside the group

**Comment by kelna** [comment]
I still have the same issue on [Version 1.65.114 Chromium: 124.0.6367.60 (Official Build) unknown (64-bit)](https://brave.com/latest/)
