### ISSUE TITLE
Can't install external extension

### ISSUE THREAD

**Issue by edwada** [brave/brave-browser#20296]
## Description 
Google is now using Chrome Store censorship to stop extensions designed to facilitate exchange of information between users, one example of this is their removal of the Dissent extension by Gab, we need an easy way to install external extensions 

## Steps to Reproduce

   1. Git clone https://github.com/gab-ai-inc/gab-dissenter-extension/
   2. Turn developer mode on and load the unpacked extension from /build/chrome directory
   3. Pack the extension to create the .crx file
   4. Remove the dissenter extension and try to install it from the generated .crx file

## Actual result:
When installing the packaged extension a message saying "This extension is not listed in the Brave Web Store and may have been added without your knowledge." appears and it's not possible to enable the extension
![image](https://user-images.githubusercontent.com/1558735/147901742-348872a9-cd16-4604-9842-2068a1354190.png)

I didn't find any "Brave Web Store" so I'm assuming this message originally meant the Chrome Web Store but the "Chrome" was replaced by "Brave"

## Expected result:
It should be possible to install the packaged extension without enabling developer mode and without it being listed on the Chrome web store, fail to do so makes Google's censorship of their Web Store effective on Brave as well

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)
Brave | 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)
-- | --
Revision | d5ef0e8214bc14c9b5bbf69a1515e431394c62a6-refs/branch-heads/4664@{#1283}
OS | Windows 10 Version 20H2 (Build 19042.1415)
JavaScript | V8 9.6.180.21
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Command Line | "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --disable-client-side-phishing-detection --disable-domain-reliability --enable-dom-distiller --no-pings --component-updater=url-source=https://go-updater.brave.com/extensions --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --enable-features=WebUIDarkMode,PrefetchPrivacyChanges,PasswordImport,ReducedReferrerGranularity,LegacyTLSEnforced,AutoupgradeMixedContent,WinrtGeolocationImplementation,SafetyTip --disable-features=AppDiscoveryRemoteUrlSearch,Fledge,ReadLater,AutofillEnableAccountWalletStorage,IdleDetection,ComputePressure,AdInterestGroupAPI,CopyLinkToText,FirstPartySets,InterestCohortAPIOriginTrial,InterestCohortFeaturePolicy,ReportAllJavaScriptFrameworks,Prerender2,SpeculationRulesPrefetchProxy,ConversionMeasurement,InterestGroupStorage,TextFragmentAnchor,DirectSockets,TrustTokens,Parakeet,AutofillServerCommunication,TabGroupsFeedback,WebSQLInThirdPartyContextEnabled,NavigatorPluginsFixed,SignedExchangeSubresourcePrefetch,NotificationTriggers,WebOTP,LiveCaption,FederatedLearningOfCohorts,NetworkTimeServiceQuerying,SubresourceWebBundles,HandwritingRecognitionWebPlatformApiFinch,FlocIdComputedEventLogging --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe
Profile Path | C:\Users\Eduar\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default
Variations | AdRewardsStudy:NextPaymentDayAdServingStudy:MaximumAdNotificationsPerDay=100/MaximumInlineContentAdsPerHour=8/MaximumInlineContentAdsPerDay=40BraveAds.FrequencyCappingStudy:ExcludeAdIfWithinTimeWindow=0hBraveAds.UserActivityStudy:Triggers=EMPTY/Threshold=0.0/IdleTimeThreshold=5ConversionsStudy:NewDefaultPatternDefault1pBlockingStudy:DisabledEphemeralStorageStudy:EnabledNativeCosmeticFilteringStudy:EnabledPartitionConnectionsByNetworkIsolationKeyStudy:EnabledPermissionLifetimeReleaseStudy:EnabledRequestAdsEnabledApiStudy:EnabledSpeedreaderReleaseStudy:Enabled

**Comment by crimsdings** [comment]
i was able to reproduce the same with another extensions https://github.com/puemos/hls-downloader/releases - 

![image](https://user-images.githubusercontent.com/886421/147909596-818991e5-44e0-4961-a246-1e328158b40f.png)

unable to enable

**Comment by LanceTrahan** [comment]
> unable to enable - https://developer.chrome.com/docs/extensions/mv3/external_extensions/ is not a proper solution for this

I was running into this as well on Mac. The [listed workaround](https://github.com/brave/brave-browser/issues/2457#issuecomment-815320474) no longer works because Chrome is trying to force extensions to be hosted through them (which they can arbitrarily reject).

This message is now present in the prescribed link:
<img width="735" alt="Screen Shot 2022-02-02 at 12 55 41 PM" src="https://user-images.githubusercontent.com/2429609/152219704-5adc193f-3f4e-4772-9319-cd6cc5f22e79.png">

Brave really needs a solution for this as the field of "allowed" extensions continues to narrow daily. Honestly though, since Dissenter has all but been abandoned, having that functionality as a built-in feature in Brave would be really cool. Could be a way for the Brave community to interact with each other through shared commentary on sites that regularly keep their content from being commented on.

**Comment by edwada** [comment]
Dissenter has been abandoned but the fact remains it's still open source and the servers still work, there are still people who believe in the idea of dissenter and nothing stops us from reviving dissenter or making our own Dissenter like extensions other than the extension censorship.

I don't believe this functionality should be part of Brave, it should be an extension so it can be added to any chrome-based browsers, in fact, ideally, all chrome based browsers should come from a censorship free fork of chrome.

**Comment by LanceTrahan** [comment]
> I don't believe this functionality should be part of Brave, it should be an extension so it can be added to any chrome-based browsers, in fact, ideally, all chrome based browsers should come from a censorship free fork of chrome.

The comment was more of a passing thought. This isn't the place for feature requests. I think we agree though that currently users can't currently load external extensions using the currently described workarounds and should be resolved.

**Comment by J0s3f** [comment]
I have the same problem when installing https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/ 
I installed Firefox as second browser and might just use it as main browser in the future. 
Sad, because I like brave, but limiting extensions to those google likes is nothing I can live with. And using two browsers in parallel like I did the last few days also isn't that comfortable.

**Comment by Renari** [comment]
Same issue here, recently one of the extensions I was using got removed from the webstore, the dev posted a zip which allowed me to pack a crx myself, but I cannot install it on Windows.

**Comment by IzK666** [comment]
I wanted to use Brave, because I heard very good opinions, but the impossibility to install a custom crx file that is not from G store mades me discard Brave as a valid browser for me.

**Comment by 424344** [comment]
a CRX is just a ZIP file. 
Just extract the files and load them as an unpacked extension.

**Comment by crimsdings** [comment]
> It should be possible to install the packaged extension without enabling developer mode and without it being listed on the Chrome web store, fail to do so makes Google's censorship of their Web Store effective on Brave as well

please read the ticket again

**Comment by xenstar** [comment]
Please allow to install custom CRX file. Updating manually extension is hard.

**Comment by macbugs** [comment]
@Renari wrote:
> **_Same issue here, recently one of the extensions I was using got removed from the webstore, the dev posted a zip which allowed me to pack a crx myself, but I cannot install it on Windows._**

I think the `👀` reaction you got from that post is begging the question of **_why_** it was removed from the Chrome store.  I recall one case where a legitimate (and popular) extension was sold to another developer for a lot of money and the new developer added some spying code that leaked personal information, so the user of a blacklisted extension is obligated to perform some research and determine the reason for its removal.  But Google will not help you there because they do not want to disclose the reason for censoring extensions.  If the same extension is still available in the official Firefox repository, and the link to the developer's site is the same, then the Firefox extension store might be a source of more information regarding the status & validity of the extension.  However, what we really need is an `extension firewall` within the browser that would notify the user when extensions transmit information (instead of just modifying web page contents), so if that occurs when it is not expected, the user would be aware of it.

**Comment by Pointing8422** [comment]
+1 to this. In Linux it's fixed, but in Windows it doesn't. There are a lot of extensions not available in Chrome Web Store for the Manifest v3. My main is LibRedirect. Ublock Origin full version will not be available next year. If this continue, I will probably have to change to Firefox or Ungoogled Chromium permanently.

**Comment by bsclifton** [comment]
cc: @rebron for help prioritizing

**Comment by macbugs** [comment]
@Pointing8422

> **_My main is LibRedirect._**

Yes, this is another example of an extension which can bypass regional YouTube barriers, but Google does not allow it in the Chrome store because it also prevents tracking.

> **_Ublock Origin full version will not be available next year._**

What is the source of this information?  (And what does Ublock accomplish which Brave Shields does not?)

> **_I will probably have to change to Firefox_**

I do not consider Firefox a realistic option because it has become increasingly unstable, especially when private browsing mode is used to test various things with extensions disabled.  The UI sometimes becomes partially-unresponsive, or behaves erratically, and it sometimes loses sessions… but Brave seems very stable.

**Comment by bayazidbh** [comment]
> And what does Ublock accomplish which Brave Shields does not?

I haven't heard about the uBlock Origin full/separate version, other than general rumbling of what's happening around Manifest V3 and how AdGuard has a lot of limitations they need to work around to even have something functional for Manifest V3.

But I think a few important things that uBlock does that so far Brave Shields doesn't, right now, is [sync-able settings & filters](https://github.com/gorhill/uBlock/wiki/Cloud-storage) (I heard that's coming in next stable upgrade?), [more granular blocking and allowing](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide), and [element zapper](https://github.com/gorhill/uBlock/wiki/Element-zapper) which is useful when something gets past the normal filters but you don't want to add it to filter list for whatever reason (for example, I often zap sticky headerbars).

I think Firefox's making some good strides as far as their PC browser goes, but it's mobile that's making me stay with Brave. Brave has the right mix of being powerful and easy to use as well as working right out of the box. Some people probably care less about their mobile browsers being the same as their PC browser than me, though.

**Comment by 424344** [comment]
> And what does Ublock accomplish which Brave Shields does not?

brave shields doesn't support procedural filtering, so it blocks less ads than ublock origin.

**Comment by dpthegrey** [comment]
> I have the same problem when installing https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/ I installed Firefox as second browser and might just use it as main browser in the future. Sad, because I like brave, but limiting extensions to those google allows is nothing I can live with. And using two browsers in parallel like I did the last few days also isn't that comfortable.

@J0s3f  They have shown a method at `https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/tree/master/allowlist` to add extension to allowlist in windows, mac, linux and I have tried that method works on my macOS. Haven't tried that on windows and linux. That is the only way i managed to use auto updating crx extension.

More References:
- https://github.com/younesaassila/ttv-lol-pro/issues/39

**Comment by AdnanHodzic** [comment]
How I managed to get Bypass Paywall installed on both Linux and MacOS:

1.[Download source code as a ZIP file from GitHub releases.](https://github.com/iamadamdev/bypass-paywalls-chrome/releases)

2.Unzip the file and you should have a folder named bypass-paywalls-chrome-master-$version.

3.In Brave go to the extensions page (brave://extensions)

4.Enable Developer Mode toggle in the upper right.

5.Click LOAD UNPACKED upper left side.

6. Find bypass-paywalls-chrome-master in the step 2 unzip destination folder (do not delete the folder afterwards).

**Comment by dpthegrey** [comment]
any update on installing extension via CRX file?

**Comment by dsiminiuk** [comment]
And here is another scenario where users on Windows (and maybe other platforms) are hosed.
I installed the latest version of a bookmark extension from the webstore and it had a bug. The previous version without the big is no available on the Chrome Webstore and I can't load the crx file for the previous version into the Dev mode page.

Please fix this ASAP. I'm stuck until the extension developer fixes the bug and publishes the next version.

**Comment by kevineduardo** [comment]
I'm almost a year waiting. Nothing new here.

**Comment by dsiminiuk** [comment]
@kevineduardo It's almost like they want you to move to another browser.

**Comment by dpthegrey** [comment]
yeah this is very painful. like enabling developer mode should auto approve extensions, assuming developer mode is for those who know what they are doing

**Comment by Fred-IV** [comment]
So still no solution?
I understand google wanting to screw all users, and block everything that they don't control form their web store, but that's why we're using Brave!!!
Enabling Dev Mode is enough to load the crx, but then there's bi way to enable it.
Brave needs to fix this. It literally goes against their purpose for existing.
If not, then why are we not just using Chrome?

AntiCaptcha automatic captcha solver
Off
This extension is not listed in the Web Store and may have been added without your knowledge. [Learn more](https://support.brave.com/hc/en-us/articles/360017914832-Why-am-I-seeing-the-message-extensions-disabled-by-Brave-?hl=en-US)
Description
This plugin allows you to automatically solve CAPTCHAs found on any webpage.
Version
0.63
Size
1.2 MB
ID
lncaoejhfdpcafpkkcddpjnhnodcajfg

**Comment by dpthegrey** [comment]
sadly installing extension via zip file is the only option at this moment, the reason we want CRX support is it enables auto updating extension, whereas in zip there won't be any auto updating. 

A relatively new chromium based browser `Arc Browser` has no issue with installing crx extensions, It even allows creating custom extensions using a thing called [boosts](https://arc.net/boosts) in browser itself which is very interesting and enables developers to experiment and make the web browsing experience more personalised. 

Brave team should learn from them and enable developers while keeping all the security and privacy instead of limiting the way upstream chromium set it to be, especially when manifest v3 will be enforced people will be looking to move from google chrome and users will not like being limited by the browser on the extensions a user can install.

**Comment by waynebloss** [comment]
If I were the Brave team, I'd wait until Chrome starts enforcing MV3 and then announce Brave's own extension store a few days later to take advantage of the news cycle. At least I hope that's what they're doing!

**Comment by edwada** [comment]
The problem is though, Brave has betrayed its users by forcing them to dox themselves to collect their BATs, there's no coming back from this, Brave is no better than Chrome and cannot be trusted.

**Comment by waynebloss** [comment]
Did they advertise that you could remain anonymous to collect awards?

I've also read that private money transfers would also be against the law for them.

I trust them plenty and every claim I've seen against Brave has been unfounded. In cases where a mistake was made, it was fixed and some people still act like they tried to con users. In this case, it's completely unfounded as far as I can see.

This is a very small team working with code that has 35 million lines, which dwarfs the size of the Linux kernel when you deduct all the driver code. I'm not saying I know what will happen in this particular case of extension sources. They may disallow certain things for security reasons just like they do with the File System API. In that case I wish they would have just enabled it for PWAs at least.

**Comment by arjpar** [comment]
Any update on this issue? Vivaldi allows users to install extensions (CRX) via drag & drop on the extension page.

**Comment by TechFanTheo** [comment]
Not fixed. You can still sideload with a extension file, but no auto-updates. A possible solution is available, but it involves tinkering with your machine settings. https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/blob/master/allowlist/README.md

**Comment by arjpar** [comment]
> Not fixed. You can still sideload with a extension file, but no auto-updates. A possible solution is available, but it involves tinkering with your machine settings. https://gitlab.com/magnolia1234/bypass-paywalls-chrome-clean/-/blob/master/allowlist/README.md

Yup, I saw that already; activating a policy will make Chromium/Brave be considered managed and can disable some settings from being changed (IIRC the only one I remember is forcing https).

I think allowing people to sideload extensions from CRX would be great to differentiate it from most other Chromium browsers. Vivaldi allows you to sideload CRX extensions, Firefox also allows you to sideload XPI extensions -- both with autoupdate IIRC.

**Comment by Chiramisu** [comment]
If money is an issue, I'd even pay a small subscription to cover hosting costs for extensions from a dedicated Brave Webstore. To further save cost, you could limit it to extensions that have been censored by Google.

Sadly, Dissenter died several years ago with their last release in 2019, and the domain changing ownership some time between [Sep 2](https://web.archive.org/web/20230902125146/https://dissenter.com/) and [Oct 11](https://web.archive.org/web/20231011232633/https://dissenter.com/), 2023 (_according to archive.org_).

**Comment by Chiramisu** [comment]
> @[edwada](https://github.com/edwada)
> @Chiramisu
> > **_Sadly, Dissenter died several years ago with their last release in 2019_**
> 
> I do not understand what you mean: although I don't like the design very much, the site and extension still work.

Just what I said. While they apparently rebranded the website to a simple news site, the repo for their [Defiant Browser](https://github.com/gab-ai-inc/defiant-browser) (formerly Dissenter) fork of Brave is archived, with the last release over 5 years ago. Anyway, it's off topic from the OPs request, so nevermind.

**Comment by lukemulks** [comment]
+1 from user in Community on X today. 

https://x.com/r_a_d_a_n_n_e/status/1887620976117940592

Less an issue of it being technically possible through complicated set of steps; more about making adding extensions on Windows easy to do, without needing the Chrome extension store.

**Comment by iwinux** [comment]
What a hilarious fact that a **FORK** of Chrome can't even derivate from its *authoritarian* control. Have Google Chrome approved your fork? It might be illegal! LOL.

**Comment by rinntensho** [comment]
> * it is the intended behavior of Chrome (upon which Brave is based)

Then just use Ungoogled Chromium as the base. Please.

**Comment by holow29** [comment]
It appears ExtensionInstallAllowlist no longer works, at least for unmanaged instances. This means I can't see a way to load a packed .crx extension. Brave's documentation is outdated to begin with (with incorrect Brave paths), and it simply references Google's "official" external extension installation instructions - which don't seem to work for local extensions. Is that accurate?

**Comment by hexxone** [comment]
<img width="422" height="241" alt="Image" src="https://github.com/user-attachments/assets/82372820-4a23-4ad5-9205-2828963130a6" />

Same problem. Still cannot enabled installed, packed `.crx` Extensions on MacOs Brave... Even after confirming I want to install it explicitly... But when I manually run `unzip bla.crx -d bla` then load "bla"-folder as packed extension it can be enabled...

<img width="420" height="252" alt="Image" src="https://github.com/user-attachments/assets/6df50018-8ba6-4c2f-ba47-985a2c0dff70" />

Now can you please explain to me why we have do to this work-around If we have developer-mode enabled anyways?
Why does it even allow "drag-n-drop" install but then not allow to enable them? I don't like how we are being patronized here.

Realistically, a malicious software on the Users PC can **always** do exactly the same... So its not even a security improvement.
