### ISSUE TITLE
Rewards panel has extra padding after rewards summary 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#2486]
## Description 

Rewards panel has extra padding after rewards summary 

## Steps to Reproduce

   1. Enable rewards on 0.58.11
   2. Visit any site and click on the rewards panel
   3. See screenshot

## Actual result:

![screenshot from 2018-12-12 16-05-46](https://user-images.githubusercontent.com/17010094/49874457-8c4eb600-fe44-11e8-9984-0b5833d47d41.png)

## Expected result:
Should not contain any unnecessary padding

## Reproduces how often: 

Easy

## Brave version (brave://version info)

All platforms on 0.58.11

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
@ryanml Logged this issue because https://github.com/brave/brave-core/pull/957 was reverted. Also i think the PR originally was intended to have https://github.com/brave/brave-core/pull/957#pullrequestreview-180096425. Could we have a separate PR done for this issue and not club with other UI fixes. 

cc: @brave/legacy_qa  @NejcZdovc @jasonrsadler @bbondy

**Comment by kjozwiak** [comment]
If https://github.com/brave/brave-core/pull/957 doesn't end up landing in `0.58.x`, we definitely need to make sure that the "empty" space is fixed before we ship `0.58.x`. Just looks very strange.

**Comment by kjozwiak** [comment]
After talking to @NejcZdovc, we won't be including the custom amounts in `0.58.x` but will have a simple PR that fixes the above UI issue. 👍

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.58.14 Chromium: 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows 7

The padding after `rewards summary` is smaller, but still not fully fixed. Logged https://github.com/brave/brave-browser/issues/2590
