### ISSUE TITLE
Hidden bookmarks bar flashes when opening new tab

### ISSUE THREAD

**Issue by georapbox** [brave/brave-browser#25834]
## Description 

If bookmarks bar is always hidden, when opening a new tab, the bookmarks bar appears for few milliseconds and then disappears again. The issue happens only if there are bookmarks saved.

## Steps to Reproduce
   
1. Disable "Show bookmarks bar" under "Settings > Appearance > Show bookmarks bar" 
![Screenshot 2022-10-06 at 10 28 32 AM](https://user-images.githubusercontent.com/6596039/194249330-05efa929-e820-437e-a9c9-6e6a8dcc38a2.png)

2. Open a new tab

## Actual result:

Bookmarks bar appears for a few milliseconds and then disappears again, causing an annoying flash effect.

https://user-images.githubusercontent.com/6596039/194246899-8e41b446-5c55-42a1-8494-c4e28faa0549.mov

## Expected result:

The bookmarks bar should not flash.

## Reproduces how often: 

Always when the bookmarks bar is set to be always hidden.

## Brave version (brave://version info)

**Brave:** 1.44.105 Chromium: 106.0.5249.91 (Official Build) (x86_64)
**Revision:** fa96d5f07b1177d1bf5009f647a5b8c629762157-refs/branch-heads/5249@{#707}
**OS:** macOS Version 10.15.7 (Build 19H1323)

## Version/Channel Information:

Can you reproduce this issue with the current release?
**Yes** 

Can you reproduce this issue with the beta channel?
**Yes**

Can you reproduce this issue with the nightly channel?
**Yes** 

## Other Additional Information:

Does the issue resolve itself when disabling Brave Shields? 
**No**

Does the issue resolve itself when disabling Brave Rewards?
**No**

Is the issue reproducible on the latest version of Chrome?
**No**, in Chrome bookmarks bar is always displayed in new tab page.

## Miscellaneous Information:

The issue might be caused due to the fact that Chromium always displays the bookmarks bar when opening a new tab page. Therefore, there might be a case that Brave delays to hide the bar, hence the flash effect.

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by spylogsster** [comment]
cannot reproduce in Nightly @georapbox can you try on your side? thanks

**Comment by georapbox** [comment]
Hi,

Just tried that with latest Nightly and still happening on my side.

Brave: 1.47.2 Chromium: 107.0.5304.36 (Official Build) nightly (x86_64) 
Revision: 2f9c7a5a1fe357d87e9bc07c65cca9136b3651c5-refs/branch-heads/5304@{#671}
OS: macOS Version 10.15.7 (Build 19H1323)

https://user-images.githubusercontent.com/6596039/197131318-3992e4a6-00e2-445e-b49f-848e2f8abdc1.mov

**Comment by georapbox** [comment]
Just found a related question in reddit if that helps...

https://www.reddit.com/r/brave_browser/comments/yssvml/bookmark_is_hidden_on_new_tab_and_other_tabs_but/

**Comment by manikandancode** [comment]
On a low-end system, it stays for more than 3 sec

**Comment by krwow** [comment]
Are there any chances to have this more than four-month-old bug fixed soon? Any update on that?

**Comment by krwow** [comment]
Any updates after 8 months from reporting issue? When will it be finally solved?

**Comment by void4** [comment]
I have a ton of bookmarks, and I believe this is slowing my browser down. Would be nice if this were solved

**Comment by krwow** [comment]
@spylogsster, @rebron - any updates after nearly 10 months of the bug report?

**Comment by krwow** [comment]
@LaurenWags , @kjozwiak - could let know anybody, who can take care of it, please?

**Comment by LaurenWags** [comment]
fwiw, @rebron this is still reproducible with 1.61.x on macOS

**Comment by simonhong** [comment]
Fixing now.

**Comment by brad86m** [comment]
This is still happening.

**Comment by LaurenWags** [comment]
Hi @brad86m - this fix is only on Nightly and Beta right now and will be coming to the Release channel next week with version 1.64.x. If you're still seeing this issue on Nightly or Beta please do log an issue with additional information (your OS, etc). Thanks!
