### ISSUE TITLE
Video ads on YouTube have no Skip button

### ISSUE THREAD

**Issue by EbonJaeger** [brave/brave-browser#2763]
## Description 

When watching YouTube videos with Shields off, video ads that play have no Skip button like they should. This was briefly mentioned in the last comment on #1145, but it would be better for this to be its own issue.

## Steps to Reproduce

   1. Turn Shields off for YouTube
   2. Watch videos on YouTube until an ad is played
   3. Notice no button to skip the ad on the lower right corner

## Actual result:

http://prntscr.com/m1dj0j

## Expected result:
http://prntscr.com/m1djas
(Taken from Vivaldi)

## Reproduces how often: 

Seems to happen for every ad.

## Brave version (brave://version info)

Brave | 0.58.18 Chromium: 71.0.3578.98 (Official Build) (64-bit)
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Windows

### Website problems only:  
- Is the issue reproducible on the latest version of Chrome? 
    * Does not happen on latest stable Vivaldi, which is also Chromium 71

**Comment by tomlowenthal** [comment]
IIRC, this may be caused by blocking one of the domains that Google uses for ad measurement on YT.

**Comment by vicentelyrio** [comment]
I'm facing this problem even with all shields off for YT. It's something related to the ad container (a div with these classes: `.video-ads .ytp-ad-module`) having `display: none!important`, this div have the counter and the skip button, but for Brave they disabled it.

For now I've created a simple bookmark that I click when a ad starts: `javascript: document.querySelector('.videoAdUiSkipButton,.ytp-ad-skip-button').click()`

**Comment by SohaibJKhan** [comment]
Refresh after 5 seconds. It skips it. I hope that it counts toward the creator. I don't want to be watching ads for no reason.

**Comment by SohaibJKhan** [comment]
Refresh after 5 seconds. It skips it. 
> IIRC, this may be caused by blocking one of the domains that Google uses for ad measurement on YT.
I hope that it counts toward the creator. I don't want to be watching ads for no reason.

**Comment by stephenbe** [comment]
Thanks @vicentelyrio !

I am using [stylebot ](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha/related?hl=en)with this rule :
`.ytp-ad-module {
    display: block!important;
}
`
 Everything is fixed until they push a fix here

**Comment by Brave-Matt** [comment]
+1 from Reddit:
https://www.reddit.com/r/brave_browser/comments/ax75ap/youtube_ads_unskippable/

**Comment by Brave-Matt** [comment]
https://www.reddit.com/r/brave_browser/comments/azekc1/i_cant_skip_ads_on_youtube_when_i_turn_off_the/

**Comment by Brave-Matt** [comment]
+1 from community:
https://community.brave.com/t/youtube-ads-not-skippable/46179/6

**Comment by mheiduk** [comment]
I have this issue too, would be great if the brave team can fix it.

**Comment by RobinLenaerts-r0627775** [comment]
Been having this issue for a couple months now, would be great if it gets fixed because i dont wanna sit through the 4+ minute adds youtube serves me sometimes...

**Comment by Column01** [comment]
I have the same issue.
I used Stylus (chrome extension) and added a custom CSS rule for youtube with the above CSS. It's a different application than they used but still works :D

> Thanks @vicentelyrio !
> 
> I am using [stylebot ](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha/related?hl=en)with this rule :
> `.ytp-ad-module { display: block!important; } `
> Everything is fixed until they push a fix here

**Comment by vicentelyrio** [comment]
I liked the bookmark approach because the ad skips right on and I do not need to give a second click on the skip button

**Comment by ckothwal123** [comment]
+1
I love the browser overall and the speed improvements it has given me over chrome. This is the only issue that stops me from completely shifting to brave. Hope to see this resolved soon !

**Comment by vicentelyrio** [comment]
I still think Google is to blame for this problem, the button is deliberately hidden only in Brave.

**Comment by Column01** [comment]
> I still think Google is to blame for this problem, the button is deliberately hidden only in Brave.

No, it is very much an issue with the brave ad-blocker. I could probably see the "ad" part of the CSS and remove it thinking it's an ad when it is the thing protecting us from ads. Google would not invest time and money into making a specific rule for YouTube to disable the ad skip button when using a certain browser, that would be stupid and waste more money than blocking ads loses them in the first place. Plus most people who have this issue have it with the shields off anyways.

**Comment by cupcakearmy** [comment]
This is still not fixed... Come on bois.

**Comment by szaimen** [comment]
Sry for asking but why should you disable shields (and adblocking) for youtube and therefore need this feature when you can bypass all ads with adblocking enabled?

**Comment by RobinLenaerts-r0627775** [comment]
so you dont screw over a youtubers income, they get paid by the amount of watches/clicks they get on the ads over their videos. if you use adblock and bypass the ads, you deny them some income.

**Comment by cupcakearmy** [comment]
I would like to get ads. I mean I don't like it but I want to support the platforms that deliver content. How are the sites and creators supposed to run otherwise?

**Comment by szaimen** [comment]
Through Brave Rewards, I assume?

**Comment by RobinLenaerts-r0627775** [comment]
brave rewards are not available everywhere yet :( belgium for example :(

**Comment by cupcakearmy** [comment]
While brave rewards are a cool concept (I truly believe they could be the future), it does not solve the underlying issue that even with all the shields down brave still affects a webpage. I expect that if I choose to turn off the shields, brave does not apply any modification to the website in question. In my opinion that is not transparent and I expect from a privacy focused application that it should be transparent as possible.

**Comment by w0rdism** [comment]
This issue is still occuring, would like if it could be fixed. Any word from this? @mkarolin

**Comment by Brave-Matt** [comment]
Another +1
https://community.brave.com/t/i-cannot-skip-any-ads-on-youtube-using-brave-anymore-i-dont-want-to-go-back-to-firefox-help-please/95732

**Comment by LaurenWags** [comment]
@ryanbr could you provide a test plan for this one? PR mentions
```
this will fix a few issues of ad elements showing up on youtube
```
would love to get some detail on what QA should specifically be looking for. 

Additionally, I am still not seeing skip button on YT ads when shields are down, am I doing something incorrectly? My steps are:
Clean install of 1.4.x
Navigate to YT
Toggle shields off for YT
View a video with a pre-roll ad such as https://www.youtube.com/watch?v=8rNhH3BT_Sw
--> pre-roll ad shows and there's no skip button. Fired up Chrome (no ad blocker installed) and saw the skip button on this video.

**Comment by ryanbr** [comment]
This should be fixed in 1.4 from this PR:  https://github.com/brave/brave-core/pull/4403

**Comment by LaurenWags** [comment]
@kjozwiak @bsclifton can you guys take a look at this one? The PR referenced in https://github.com/brave/brave-browser/issues/2763#issuecomment-584881696 doesn't have a milestone but I think it landed in 1.5.x, not 1.4.x. So not sure if we need to uplift something or this issue can be moved to 1.5.x milestone.

**Comment by LaurenWags** [comment]
Had additional discussions with @ryanbr and did some more investigation. For the exact same 15s pre-roll ad on Chrome, Vivaldi and Brave (shields down):
- Chrome shows the skip button
- Vivaldi shows the skip button
- Brave (with shields down) does not show the skip button

Tested https://www.youtube.com/watch?v=Lam-HQoNYKU with 
Chrome `80.0.3987.100`
Brave `1.4.84 Chromium: 80.0.3987.87` and `1.5.86 Chromium: 80.0.3987.87`
Vivaldi `2.10.1745.27 (Stable channel) (64-bit)`

Gifs available by request, some are too large to post

**Comment by ryanbr** [comment]
Okay, I have implemented a fix. https://github.com/brave/brave-core/pull/4603  Just needs to be reviewed.

**Comment by LaurenWags** [comment]
Per process, opened follow up issue https://github.com/brave/brave-browser/issues/8209

cc @kjozwiak @rebron @bsclifton in case you want to consider the follow up issue for uplift to 1.4.x once fix is confirmed.

**Comment by LaurenWags** [comment]
Verified using

Brave | 1.4.84 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

* Skip button does not appear as expected, logged follow up issue https://github.com/brave/brave-browser/issues/8209 and referenced https://github.com/brave/brave-browser/issues/2763#issuecomment-585081422 in it.

**Comment by bsclifton** [comment]
Sorry for all the confusion folks - https://github.com/brave/brave-core/pull/4403 was only merged to 1.5 (which was master at the time). We can uplift to 1.4, per comment here:
https://github.com/brave/brave-core/pull/4403#issuecomment-578346143
> @ryanbr #4094 is only pushed as far as developer channel (1.4). We can uplift there, but a PR would need to be submitted manually (I tried running the automatic tool for uplift and it ran into problem cherry-picking)

So we should consider uplifting https://github.com/brave/brave-core/pull/4403 to 1.4

Is https://github.com/brave/brave-core/pull/4603 still needed?

**Comment by Ladrason** [comment]
@bsclifton 
Sorry if this is an unnecessary comment or I'm bringing something unrelated up.

I've had problems with adds not getting their skip button as well on Windows. I'm right now on Brave nightly 1.6.24 and as can be seen [here](https://i.imgur.com/vP0jnmv.jpg) and [here](https://i.imgur.com/nsmddvE.jpg) the skip button still doesn't appear when an ad starts.

**Comment by LaurenWags** [comment]
@bsclifton I do not get a skip button on 1.5.x either 😞 see:
https://github.com/brave/brave-browser/issues/2763#issuecomment-584886721
https://github.com/brave/brave-browser/issues/8209#issue-564102098

Just tried again on 1.5.x:

Brave | 1.5.90 Chromium: 80.0.3987.87 (Official Build) dev (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | macOS Version 10.14.6 (Build 18G103)

Confirmed that same ad on Chrome does have a skip button, but when ad shows on Brave (shields down), there is no skip button.

**Comment by ryanbr** [comment]
@bsclifton both https://github.com/brave/brave-core/pull/4403 https://github.com/brave/brave-core/pull/4603 are needed .

**Comment by LaurenWags** [comment]
removing `release-notes/include` label as this issue was not fixed in 1.4.x and will be addressed with https://github.com/brave/brave-browser/issues/8209 per https://github.com/brave/brave-browser/issues/2763#issuecomment-585280056

**Comment by marcottt** [comment]
still have same issue..... there is some action to do ?

**Comment by Ladrason** [comment]
> still have same issue..... there is some action to do ?

They are working on fixing it. You can follow the progress [Here](https://github.com/brave/brave-browser/issues/8209).

If you want a quick fix you can install [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) and add
```
.ytp-ad-module {
    display: block;
}
```
to the edit CSS section in the extension when you're on youtube.
