### ISSUE TITLE
Browser crashes when invalid EIP712 request data is submitted

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-browser#28049]
## Description 

https://user-images.githubusercontent.com/23125059/214696853-845d8d9f-b4fd-45e7-99ad-2c36b5c6fb53.mp4

## Steps to Reproduce

   1. clone https://github.com/coinspect/test-dapp-eip-712 and modify line 133 to be `{ name: 'name', type: 1234 },`
   2. start DApp and connect to wallet
   3. click `sign`

## Actual result:
browser crash

## Expected result:
Should fail gracefully and not crash the browser process

## Reproduces how often: 
Easily reproduced

**Comment by neeythann** [comment]
@kdenhartog i can still reproduce the crash with the same STR in latest nightly (v1.50.27) on linux.

**Comment by kdenhartog** [comment]
Can you specify your test value that you're using that's still producing a crash?

**Comment by neeythann** [comment]
@kdenhartog - same as the test case above

https://user-images.githubusercontent.com/89695588/218301582-0caa0fb2-d9ea-49d7-9771-14333ecf2aef.mp4

**Comment by kdenhartog** [comment]
Thanks I'll take a look to see if I can reproduce.

**Comment by srirambv** [comment]
Seeing the crash as well on 1.50.23

[#16883.webm](https://user-images.githubusercontent.com/17010094/218709140-d775ab93-6836-43cd-b2d0-23c920215eb0.webm)

**Comment by kdenhartog** [comment]
Re opening this as it doesn't seem to have been addressed quite yet.

**Comment by kjozwiak** [comment]
@kdenhartog closed https://github.com/brave/brave-core/pull/17099#pullrequestreview-1302104041 & https://github.com/brave/brave-core/pull/17100#pullrequestreview-1302105403 as it looks like the above is still an issue. Once the issue that @srirambv found has been fixed, lets create new uplifts 👍 If this needs to go out ASAP, the `1.48.x` maintenance release is scheduled on `February 22` as per https://github.com/brave/brave-core/pull/17100#pullrequestreview-1302105403. If it doesn't make it, we can just uplift into `1.49.x` if needed.

**Comment by kdenhartog** [comment]
That makes sense to me. Thanks for closing them.

**Comment by kjozwiak** [comment]
Removing this from `1.50.x` as it doesn't appear to be fixed yet. @kdenhartog please close if that's that not the case.

**Comment by kdenhartog** [comment]
That's correct @kjozwiak it's not merged yet. I got stuck trying to resolve a CI build issue and haven't spent the time to try and resolve that yet.

**Comment by kdenhartog** [comment]
We just received a confirmed report on H1 related to this same part of the code so it doesn't look like this has been fully fixed yet.

https://hackerone.com/bugs?report_id=1974397&subject=brave

**Comment by darkdh** [comment]
closed in favor of https://github.com/brave/brave-browser/issues/30212

**Comment by kjozwiak** [comment]
@darkdh thanks 👍 @kdenhartog we usually don't re-open issues that already have PR/code associated with an issue as it gets pretty complicated when there's several PRs/code within a single issue that span several milestones. @darkdh should we label this as `QA/No` and `release-notes/exclude` as this issue is still occurring and fixed via https://github.com/brave/brave-browser/issues/30212?

**Comment by darkdh** [comment]
we can leave the label as it is because https://github.com/brave/brave-browser/issues/30212 has different test plan and this issue has its own, so they should be verified separately.

**Comment by kjozwiak** [comment]
> we can leave the label as it is because #30212 has different test plan and this issue has its own, so they should be verified separately.

@darkdh sounds good 👍 Thanks!

**Comment by kdenhartog** [comment]
> we usually don't re-open issues that already have PR/code associated with an issue as it gets pretty complicated when there's several PRs/code within a single issue that span several milestones

Sounds good, I'll refrain from doing this going forward and keep them separate.

**Comment by srirambv** [comment]
Issue still seem to happen on 1.52.x. Going to mark the issue as QA/No and need to verify it in #30212 

https://github.com/brave/brave-browser/assets/17010094/ec3e2d4a-a583-4c21-af66-e68fe5fc820c
