### ISSUE TITLE
sometimes cmd+C doesn't copy expected text

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#28694]
## Description 

Sometimes when highlighting text on GH (from an issue description for example) and copying to a new GH issue, if I highlight text and copy it with the keyboard shortcut (cmd+C), when I paste into the new issue the URL of the issue I copied text from is pasted instead of the text I highlighted. 

Note, highlighting the text and using the right click context menu > Copy will copy the text as expected, just seems to be a problem w/ cmd+C. I only encountered in one browsing session - but it happened several times when going back and forth between two GH issues. Couldn't reproduce with a clean profile and isn't reproducing right now either.

Could be related to https://github.com/brave/brave-browser/issues/27902.

## Steps to Reproduce

Unsure of exact steps. Generally I was doing the following:
1. Have a GH issue open in one window
2. Have a blank issue open in a second window
3. Use 3 dots on first GH issue and select "Edit"
4. Click in the description box and copy description text (either via mouse or click in the description box and use cmd+A to get the whole description)
5. Use cmd+C to copy highlighted text
6. Go to new issue and cmd+V in issue description
---> sometimes first issue URL is pasted, not the copied text

## Actual result:

URL pasted into new issue

## Expected result:

copied text should be pased

## Reproduces how often: 

Difficult/Intermittent. When it happened it reproduced for a bit but then it stopped. Maybe switching between the browser and Slack had some effect, but haven't been able to reproduce.

## Brave version (brave://version info)

```
Brave | 1.49.102 Chromium: 110.0.5481.104 (Official Build) dev (x86_64)
-- | --
Revision | 46de4a7f41979e829b430bc1ee30ef483aa227ac-refs/branch-heads/5481_77@{#19}
OS | macOS Version 12.6.3 (Build 21G419)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @stephendonner @rebron

**Comment by rebron** [comment]
cc: @spylogsster

**Comment by LaurenWags** [comment]
sent video of what I'm seeing (no steps though) to @spylogsster

**Comment by marcfitt** [comment]
I have the same issue. Honestly, it's quite annoying that it's now the default copy and paste. Why not create a shortcut for it or at least let people change the shortcut to what they want?

 I'm currently considering using another browser because it hinders my productivity while working. I'm on a website wanting to copy text and it copies the url. It's just frustrating, and there's no way to disable this thing. I just want to copy the text I want to copy, please 🙏

**Comment by AustinGitHub** [comment]
is this fixed? I just opened an issue for this because me and other users are seeing it on the latest release https://github.com/brave/brave-browser/issues/29074 
Why are we changing an industry standard keyboard shortcut to something other than the standard? This is one way to drive people away from using the browser and I would like to see it fixed rather than switch browsers to another one because this is very troubling and annoying to even use the browser since I can't even copy and paste properly. Thanks!

**Comment by kjozwiak** [comment]
The above requires `1.49.126` or higher for `1.49.x` verification 👍

**Comment by kjozwiak** [comment]
> is this fixed? I just opened an issue for this because me and other users are seeing it on the latest release #29074 Why are we changing an industry standard keyboard shortcut to something other than the standard? This is one way to drive people away from using the browser and I would like to see it fixed rather than switch browsers to another one because this is very troubling and annoying to even use the browser since I can't even copy and paste properly. Thanks!

It should be fixed on `Nightly` & `BETA` and we'll release the above fix via the `1.49.x` maintenance release which is scheduled for Wednesday March 22, 2023 as per https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule#release-channel-dates.

**Comment by LaurenWags** [comment]
Verification in progress with

```
Brave | 1.49.126 Chromium: 111.0.5563.64 (Official Build) (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 12.6.3 (Build 21G419)
```

**Comment by TheOtherBrianJ** [comment]
This is still broken in 1.49.128 (MacOS 10.15.7)

**Comment by shaisamuel** [comment]
We are on 1.50.121 and this is still not fixed or added as an option to settings. This is so annoying :)

**Comment by AustinGitHub** [comment]
Go to `brave://flags/` and disable Override default copy hotkey with copy clean link
