### ISSUE TITLE
Big Regression: Latest version broke keyboard commands for copying text and pasting it

### ISSUE THREAD

**Issue by AustinGitHub** [brave/brave-browser#29074]
Edit: Next version will have fix see comment below https://github.com/brave/brave-browser/issues/29074#issuecomment-1470530853 
Leaving open until release is public to confirm again the issue is fixed. 

https://community.brave.com/t/latest-update-broke-copy-to-clipboard-with-keyboard-shortcuts/476641
https://community.brave.com/t/copy-keyboard-shortcut-c-sometimes-copies-location-instead-of-highlighted-text/476830
https://community.brave.com/t/in-some-tabs-c-is-copying-a-clean-link-of-the-page-not-copying-selected-text/476706/3

Video 

https://user-images.githubusercontent.com/10100397/225187095-7e5f0834-5d7f-4389-b7a5-8b72801851f4.mov

<img width="726" alt="Screenshot 2023-03-14 at 7 04 48 PM" src="https://user-images.githubusercontent.com/10100397/225185900-c3205804-098f-483b-b23c-ed45ef663eb5.png">

# Work-around

Update to latest version of Brave, then open `brave://flags/#brave-copy-clean-link-by-default` and set this flag to Disabled:
![Screenshot from 2023-03-24 16-43-56](https://user-images.githubusercontent.com/167821/227662994-f885bcdf-8349-4856-9b2e-b57e0a961d82.png)

**Comment by AustinGitHub** [comment]
Why is copy clean link the default for copying text? Who made this change? This is such a major change that I am confused on why this key shortcut was automatically changed and forced onto users

**Comment by AustinGitHub** [comment]
pinged few PRs that might be related to this issue. I'm trying to understand why this was a forced global change and not change the user can set themselves. This type of change should never be forced on users as it is standard that command+c is to copy text, not clean link. This is industry standard keyboard shortcut, to change this to a different command is one way to get people to switch browsers (I've been considering it if this isn't fixed, I'm not going to lie)

**Comment by spylogsster** [comment]
Hi @AustinGitHub, thanks for reporting, I guess this should be fixed in Nightly already, can you try pls?
cc @fmarier

**Comment by AustinGitHub** [comment]
my browser didn't get the update yet but I'll keep an eye on it

**Comment by AustinGitHub** [comment]
<img width="768" alt="Screenshot 2023-03-14 at 10 08 26 PM" src="https://user-images.githubusercontent.com/10100397/225212584-1bcc0a49-586c-4738-a83c-ef2b47e633a8.png">
I am on this build

**Comment by spylogsster** [comment]
@AustinGitHub Nigthly is a separate channel, it can be downloaded here https://brave.com/download-nightly/, stable builds will be updated with this fix a bit later

**Comment by AustinGitHub** [comment]
ok I will try it out in the morning and see, thanks!

**Comment by AustinGitHub** [comment]
I checked and this is fixed in nightly, when can it be expected for the actual brave browser? Thanks!

**Comment by fmarier** [comment]
@AustinGitHub Thanks for the confirmation.

We are preparing to uplift the fixes to the release channel and will QA them.

**Comment by AustinGitHub** [comment]
Thanks! If it's ok, I'd like to leave the issue open until release so people know about it and that when release I can double confirm it and close this out. Thanks!

**Comment by crypto-machia** [comment]
Thank you for opening this issue @AustinGitHub! The issue has pretty much made Brave unusable for me the last few days and was also considering switching default to Chrome. Hope this new release comes quickly.

**Comment by crypto-machia** [comment]
@AustinGitHub Do you know where I can change default from copy clean link back to copy text? I don't see that anywhere in preferences.

**Comment by AustinGitHub** [comment]
> @AustinGitHub Do you know where I can change default from copy clean link back to copy text? I don't see that anywhere in preferences.

They said it's in their other nightly browser version, though this version may contain other bugs so be wary https://github.com/brave/brave-browser/issues/29074#issuecomment-1469357973 I plan to just wait personally for the full release for the fix, hoping it's soon though. Thanks!

**Comment by spylogsster** [comment]
PRs to track it easier:

Beta:
- https://github.com/brave/brave-core/pull/17608
- https://github.com/brave/brave-core/pull/17606
- https://github.com/brave/brave-core/pull/17607

Stable:
- https://github.com/brave/brave-core/pull/17610
- https://github.com/brave/brave-core/pull/17611
- https://github.com/brave/brave-core/pull/17609

**Comment by rrajkowski** [comment]
Has this fix been released yet? I'm on latest +Mac OS 12.4 and still experiencing this issue. 
```
Brave is up to date
[Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (x86_64)](https://brave.com/latest/)
```

**Comment by TokuTrex** [comment]
Also having the same issue. It's driving me crazy, I have a lot of text I copy for work, please fix this soon. Thanks

**Comment by gupta-ayush3210** [comment]
Do we have some other workaround to fix this? Other than using "right click -> copy".

**Comment by Fr3d3r1ck** [comment]
This is painful. Can the devs do something please?

**Comment by shadowhand** [comment]
I use [Flycut](https://github.com/TermiT/Flycut) never experienced this issue (yes, I have the latest Brave). I was only aware of this issue because a coworker mentioned it.

**Comment by DmitryBerdnik** [comment]
Hi this bug ruins my productivity, when is the new version will be out?

**Comment by rebron** [comment]
https://github.com/brave/brave-browser/issues/26013#issuecomment-1472502801

We're aiming for a hotfix early next week. If you'd like to help ensure that the bugs you're seeing are the ones we're currently testing and getting ready for release, there are two things can would help:

[Download Nightly](https://brave.com/download-nightly/) and see whether or not it's fixed.
If it's not fixed, then please describe the exact steps we can take to reproduce (including what OS you're using) on https://github.com/brave/brave-browser/issues/29074.

**Comment by marcfitt** [comment]
I use nightly and it's not fixed on my side. 

Version 1.51.42 Chromium: 111.0.5563.64 (Official Build) nightly (arm64)

**Comment by spylogsster** [comment]
> I use nightly and it's not fixed on my side.
> 
> Version 1.51.42 Chromium: 111.0.5563.64 (Official Build) nightly (arm64)

what are your steps? can you record video maybe? thanks

**Comment by marcfitt** [comment]
Still really wonder what's the point of forcing clean link. Copy paste is a fundamental shortcut and should copy everything we want to copy. I get the privacy side of it and that's why I use brave but we should have the opportunity to set our shortcut if we want to clean UTMs like we can do to copy with  CMD+Shift+V

https://www.loom.com/share/34826466194343909b4ba07eca6cfbd5

The bug happens all the time btw, it's not like once an 1h, I legit just right click and copy at this point.
I will download chrome today because I can't work with brave at all.

**Comment by spylogsster** [comment]
@marcfitt I see you have highlited omnibox and selected text on the page at same time, looks like this is the reason but I cannot find steps how to reproduce it, on my side, if I click to the page, the omnibox is losing focus. Maybe you can share steps (hotkeys or so) how to make text selected and omnibox highlited at same time? thanks

<img width="765" alt="image" src="https://user-images.githubusercontent.com/2965009/226191542-59b5f696-b18b-49ac-adbb-46a6fe40fa13.png">

**Comment by marcfitt** [comment]
I don't use special shortcut, either double click on value I want to copy then CMD+C or I use Shift + arrows.
Let me know if this clean link feature will be removed or adjustable in settings because if not I will make the switch to another browser. I just can't work in a browser where the basic copy paste is not working as it should. 

Thanks

**Comment by oleurud** [comment]
Come on! do a hotfix of this, it can not be used like this

**Comment by mkamranpk** [comment]
As a sidenote, on Mac OS, since I cannot copy using Cmd + C, I tried modifying the keyboard shortcuts by going to brave://extensions/shortcuts but I do not see anything there but a blank screen - does Brave offer the ability to change keyboard shortcuts?

**Comment by pomverte** [comment]
Is it possible to disable coply clean link ?

**Comment by lsarodnik** [comment]
hello, any news about this? Really annoying.

**Comment by fmarier** [comment]
> hello, any news about this? Really annoying.

We are working on a hotfix for these bugs which will come out this week: https://github.com/brave/brave-browser/issues/29074#issuecomment-1474020137

We also heard loud and clear that people want to be able to control the default keyboard shortcut binding and we will add a setting for this, though that will not be part of the hotfix.

**Comment by AustinGitHub** [comment]
<img width="264" alt="Screenshot 2023-03-20 at 3 14 13 PM" src="https://user-images.githubusercontent.com/10100397/226477187-794e46c3-eb0d-4060-a13e-e659266ae0c9.png">
👀

**Comment by willb-zc** [comment]
@fmarier when are we talking? I need to know if I should use Brave tomorrow or download a new chromium browser.

**Comment by fmarier** [comment]
> when are we talking? I need to know if I should use Brave tomorrow or download a new chromium browser.

Likely tomorrow or the day after, depends on when we're done doing all of the QA and release procedure.

**Comment by harithzainudin** [comment]
> Do we have some other workaround to fix this? Other than using "right click -> copy".

well, you can click `cmd+x` as cut for now, although it will cut.
You can just paste it again.

better than copy clean link

**Comment by Lozclark1** [comment]
What's the eta for a fix?  i've had to start using another browser :-(

**Comment by rhulsebos** [comment]
Same question here, any time frame for this?? ist unusable like this, i've had to revert to a different browser as well until this is fixed..

**Comment by vinodhj** [comment]
Any update on this issue plz ?

 This is so irritating, I’m now using a different browser until they fix.

**Comment by vinodhj** [comment]
Is there a way to switch to the brave preview version ?

**Comment by JohnAlbin** [comment]
> I see you have highlited omnibox and selected text on the page at same time, looks like this is the reason but I cannot find steps how to reproduce it, on my side, if I click to the page, the omnibox is losing focus. Maybe you can share steps (hotkeys or so) how to make text selected and omnibox highlited(this is indication that the omnibox holds focus) at same time? thanks

@spylogsster I _think_ using tab groups affects whether the bug occurs. Switching between tabs in different tab groups sometimes triggers the bug, but I can't reliably reproduce.

Right now I have a tab that has the orange highlighted omnibox and selected text and command-c is mapping to "Copy". I also have a different tab that has the orange highlighted omnibox and selected text and command-c is mapping to "Copy Clean Link".

**Comment by muhammetsnts** [comment]
What a big mistake it is, ruining me for days. Please someone merge this PR and fix this asap. I will remove the app if it is not solved tomorrow.

**Comment by rrajkowski** [comment]
> For folks in the issue, can you install our latest release candidate that includes the fix https://github.com/brave/brave-browser/releases/tag/v1.49.126 and let us know if you're still encountering the issue.

I downloaded [v1.49.126](https://github.com/brave/brave-browser/releases/tag/v1.49.126) no issues so far! thanks

**Comment by arpolek** [comment]
@gonzaloafidalgo actually I’m suprised you didnt copy paste the url instead 😀

**Comment by sjohnson-swi-bw** [comment]
v1.49.126 on MacOS M1 resolved the issue for me as well.

**Comment by arpolek** [comment]
confirm, v1.49.126 ARM on M1 Ventura fixed the issue

**Comment by marcfitt** [comment]
It's not 100% fixed it seems. I was able to replicate it on a google sheet. 
Loom available here: https://www.loom.com/share/d61ffbade9ca42e6af1deb99d5829956
Can't wait to be able to disable this option and never use that Clean link "feature"

**Comment by Fr3d3r1ck** [comment]
Uninstalled and reinstalled version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (x86_64) and 'copy clean link' is gone; command+C works again in gDocs, gSheets, gMail, etc.

**Comment by marcfitt** [comment]
> 

Did just that, do you know how to turn off automatic update?
Thanks

**Comment by spylogsster** [comment]
hey @marcfitt I see you have highlighted omnibox (it means the omnibox holds focus) and the cursor inside the doc at same time. This state doesnt look valid for me, unfortunately I cannot reproduce this on my side. Maybe you can find time to record video to see steps from the browser launch to that state? It is important to see the sequence of clicks(focus switches) to achieve that state when you can edit the cell with highlighted omnibox at same time. Many thanks.

**Comment by rhulsebos** [comment]
i've tryed uninstalling and reinstalling as sugested by @marcfitt [Version 1.49.120 Chromium: 111.0.5563.64 (Offizieller Build) (arm64)](https://brave.com/latest/) and it does solve the copy problem!

**Comment by muhammetsnts** [comment]
hey @rrajkowski I uninstalled and reinstalled [Brave-Browser-arm64.dmg](https://github.com/brave/brave-browser/releases/download/v1.49.126/Brave-Browser-arm64.dmg), it is solved for some of the web pages but **still having the same problem on MS Teams web app.**  

![image](https://user-images.githubusercontent.com/76607915/226956737-7831e77a-88f3-4e87-9487-874b6d617550.png)

copied "example" and pasted above

![image](https://user-images.githubusercontent.com/76607915/226957507-4f7cfd7d-8d7d-4204-927b-bfaad1610900.png)

**Comment by sbitenc** [comment]
Why is this even a thing?
Who thought it'd be a good idea to copy a link instead of the selected text?
Just give it a different shortcut geez

**Comment by fmarier** [comment]
> Who thought it'd be a good idea to copy a link instead of the selected text?

Just to be clear, that's a bug and not the intent of the feature. If you're copying text that's not a URL, it's always been *supposed* to copy the text regardless of whether or not this feature is enabled.

**Comment by marcfitt** [comment]
> 

As you know, not having the same shortcut would have prevented this from happening.  Having a clean link feature not working well it's one thing, but basic cmd+c not working as intended is quite a nightmare. Can't wait to have this fixed.

**Comment by marcfitt** [comment]
Just got the new update, do you think we can have it disable by default as it's not a normal hotkey to begin with?

**Comment by jmartinez77x** [comment]
I downloaded .126 before .128 was available and it was resolved and then randomly changed back. When I downloaded .128 the same thing happened, it was fixed and then broke again.

**Comment by Nezteb** [comment]
I just updated to `Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64)`. As far as I can tell, the copy/paste behavior is back to normal. 🤞

**Comment by muhammetsnts** [comment]
I updated `Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64)` but having the same issue, especially on JupyterHub app.

![image](https://user-images.githubusercontent.com/76607915/227495120-57cfd4b2-df7d-4c87-bd3e-873bb4153280.png)

**Comment by Saoma1** [comment]
I am on `Version 1.49.128 Chromium: 111.0.5563.110 (Official Build) (arm64)` and the problem still returns some times.
When I then reload the page `cmd + c` &  `cmd + v` work again

**Comment by vinodhj** [comment]
Yes, the problem reappears from time to time. Even after clearing the cache, the problem persists some time, it is not stable.

**Comment by vinodhj** [comment]
@spylogsster I updated to the latest version but am still experiencing the same problem, it works some of the time but not all of the time.

<img width="387" alt="Screenshot 2023-03-24 at 8 32 13 PM" src="https://user-images.githubusercontent.com/88649849/227563343-d283cfbd-76d3-49aa-a199-4c7bca07152a.png">

**Comment by jmartinez77x** [comment]
I set the brave://flags/#brave-copy-clean-link-by-default flag to disabled and I think that fixed it, time will tell.

**Comment by vinodhj** [comment]
Thanks @stephendonner. The issue seems to be resolved now and will post again if the problem persists.

**Comment by fmarier** [comment]
Thanks for all of the feedback and testing. Our fixes for macOS look like they did not address all of the corner cases that people are running into. We will be flipping the flag to off-by-default on Monday. A PR and hotfix are also coming: https://github.com/brave/brave-core/pull/17752

**Comment by AustinGitHub** [comment]
Just got the update, I turned flag off to disabled for this, I'll update sunday night how well this worked for me over weekend. Thanks!

**Comment by rodrigoamds** [comment]
I am currently using version 1.49.128 and I have noticed that some pages, like TikTok, still do not have their 'copy' functionality working properly. Thank you for your attention.
<img width="240" alt="copy-tiktok" src="https://user-images.githubusercontent.com/13823773/227747183-52ca4054-8041-42bd-b616-74009d099b9c.png">

**Comment by tripleee** [comment]
As a tedious, and ultimately untenable workaround you can control-click on the selected text and get a dropdown menu whose Copy command works.

**Comment by tripleee** [comment]
As a tedious, and ultimately untenable workaround you can control-click on the selected text and get a dropdown menu whose Copy command works.

**Comment by AustinGitHub** [comment]
> Just got the update, I turned flag off to disabled for this, I'll update sunday night how well this worked for me over weekend. Thanks!

updating, this worked for me, thanks!

**Comment by Taifun07** [comment]
Hi, this issue started again! 
All of a sudden cmd+C in Google sheets copies the link. 
How to fix this awful mistake of a "feature"? 

![Screenshot 2023-03-29 at 14 03 27](https://user-images.githubusercontent.com/128387850/228514215-14309e37-83b0-4e9f-96eb-11a2244824d7.png)

**Comment by spylogsster** [comment]
@Taifun07 on brave://flags page you can disable `Override default copy hotkey with copy clean link`:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/2965009/228524320-218ae75b-a2b1-4840-986a-88e8c4be4975.png">

**Comment by fmarier** [comment]
@Taifun07 What version of the browser are you using? 1.49.132 is the one that has cmd+C mapped to regular copy.

**Comment by oleurud** [comment]
OMG, it is happening again!!! Version v1.49.132 in mac

**Comment by FelikZ** [comment]
Having flag disabled - fixed issue for me. Should be default.

**Comment by Taifun07** [comment]
> @Taifun07 What version of the browser are you using? 1.49.132 is the one that has cmd+C mapped to regular copy.

Right now I have 1.49.132. version
Since I disabled this feature it is fixed now. 
The interesting part is, that it was turning on auto when a tab with any Google product is open.

**Comment by spylogsster** [comment]
Hi everyone, Im still trying to reproduce the issue on macos with enabled feature on google sheets. it looks depends on some focus traveling between windows/elements to reproduce.  It would be great if someone can help and post videos from the browser launch to the problem with visible focus switches. Many thanks.

**Comment by nielsmadan** [comment]
Good lord. How did this ever make it into a production build? Time for some root cause analysis and improvements to your QA process, yes?

**Comment by AustinGitHub** [comment]
I think we can close this right? @spylogsster Thanks!

**Comment by MiriamWeyden** [comment]
The problem is not fixed yet, did I miss an update?

**Comment by AustinGitHub** [comment]
It should be, go to `brave://flags/` and then disable override hotkey of copy clean link and it should be fine

**Comment by MiriamWeyden** [comment]
Unfortunately, no results for this with me. 
<img width="793" alt="Bildschirmfoto 2023-04-20 um 07 56 17" src="https://user-images.githubusercontent.com/79315654/233271218-82686d7b-e8af-4018-969a-5ac2bab21b69.png">

**Comment by AustinGitHub** [comment]
oh I see you're on 111.1.49.120
update your browser

**Comment by MiriamWeyden** [comment]
Thank you so much, didn't see the last update. Now I was able to set it!
