### ISSUE TITLE
windows 10 desktop, all notifications still not working in brave browser

### ISSUE THREAD

**Issue by TKList** [brave/brave-browser#3235]
## Description 

windows 10 desktop, all notifications still not working in brave browser

## Steps to Reproduce

   1. Allow notifications from any site.
   2. Wait for notifications.
   3. Get zero notification. 

## Expected result:
Get all allowed notifications.

## Reproduces how often: 

Always. It never worked before the last update or after. 

## Brave version (brave://version info)

Version 0.59.34 Chromium: 72.0.3626.81 (Official Build) (64-bit)

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Have no idea. 
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 
No.

**Comment by TKList** [comment]
Mail.com extension notifications work. If that helps.

**Comment by srirambv** [comment]
Have you checked the system notification setting for Brave app?

**Comment by TKList** [comment]
Not an app, windows 10 desktop browser.

**Comment by rebron** [comment]
cc: @mandar-brave

**Comment by mattspew** [comment]
> Have you checked the system notification setting for Brave app?

Thought I add my two cents here after fixing my Brave notification issue.

I also had not been getting any desktop notifications and tried everything Brave related to fix it without success.

After reading this thread and this reply I decided to check my Windows 10 settings and it is now fixed. Nothing I'd read before prompted me to think it was a Windows setting.

**Windows --> Settings --> System --> Notifications & Actions --> Turn on "Get Notifications from apps and other senders".**

I then used the the following website to test notification: https://web-push-book.gauntface.com/demos/notification-examples/

**Comment by ZennfI** [comment]
> > Have you checked the system notification setting for Brave app?
> 
> Thought I add my two cents here after fixing my Brave notification issue.
> 
> I also had not been getting any desktop notifications and tried everything Brave related to fix it without success.
> 
> After reading this thread and this reply I decided to check my Windows 10 settings and it is now fixed. Nothing I'd read before prompted me to think it was a Windows setting.
> 
> **Windows --> Settings --> System --> Notifications & Actions --> Turn on "Get Notifications from apps and other senders".**
> 
> I then used the the following website to test notification: https://web-push-book.gauntface.com/demos/notification-examples/

Thank you so much! I spend too much time trying to figure out what was the problem with my website code...

**Comment by bsclifton** [comment]
cc: @Brave-Matt in case we wanted to capture above notes on support.brave.com

**Comment by Nzent** [comment]
![image](https://user-images.githubusercontent.com/26079832/229316067-986c0ddc-3acb-40d5-835b-6e896b00577f.png)
Still have this issue 
Windows 11 system notification is on

**Comment by kjozwiak** [comment]
@Nzent going to close this one off as it's pretty stale and labelled as `closed/not-actionable`. Looks like the original issues were resolved/addressed by enabling notifications via the `Windows` settings. If you're still having issues,. mind creating a new issue with STR/Cases and more information using https://github.com/brave/brave-browser/issues/new?assignees=&labels=OS%2FDesktop&projects=&template=desktop.md&title=. Thanks!
