### ISSUE TITLE
Update sidebar button's left & right margin

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#34249]
When `chrome://flags/#brave-web-view-rounded-corners` is enabled, sidebar button's left and right space seems different.
Different side space.
<img width="92" alt="Screenshot 2023-11-10 at 2 55 36 PM" src="https://github.com/brave/brave-browser/assets/6786187/a7af3937-a66c-4acf-8271-206102bd37bc">

It should be
<img width="87" alt="Screenshot 2023-11-10 at 2 56 06 PM" src="https://github.com/brave/brave-browser/assets/6786187/e7c6ee2f-c101-4851-9a2e-a1582873b186">

**Comment by rebron** [comment]
cc: @zenparsing

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.62.49 Chromium: 119.0.6045.134 (Official Build) nightly (x86_64)
-- | --
Revision | ebbe0beec9dfdb603463869912ad4ec19899293d
OS | macOS Version 11.7.10 (Build 20G1427)
```

### Steps:
1. installed `1.62.49`
2. launched Brave
3. ensured `brave://flags/#brave-web-view-rounded-corners` was set to `Enabled`
4. clicked on `Playlist` in the sidebar
5. examined the icon's border padding on both sides
6. confirmed it was uneven with `1.62.39`

### Confirmed the side-border padding in `1.62.49` was fixed, with both sides equal

`1.62.49` | `1.62.39`
---------|---------
<img width="98" alt="Screen Shot 2023-11-13 at 1 48 06 PM" src="https://github.com/brave/brave-browser/assets/387249/40c665b4-9ebc-44df-985c-1c65ab10ced7"> | <img width="111" alt="Screen Shot 2023-11-13 at 1 53 09 PM" src="https://github.com/brave/brave-browser/assets/387249/33fab65b-c895-4cbe-8b2d-33a10a01ee78">

**Comment by kjozwiak** [comment]
Removing the `QA-Pass` label as the above was uplifted from `master` into `1.61.x` via https://github.com/brave/brave-core/pull/21074 and will need to be re-checked using `1.61.x`. The above requires `1.61.85` or higher for `1.61.x` verification 👍

**Comment by GeetaSarvadnya** [comment]
Verified on Windows 10 x64. The issue is still reproducible. Logged https://github.com/brave/brave-browser/issues/34522

```
Brave | 1.61.85 Chromium: 119.0.6045.163 (Official Build) beta (64-bit)
-- | --
Revision | 5e2736df90772dd1b66ca5013e47c1fc467c9762
OS | Windows 10 Version 22H2 (Build 19045.3693)
```

**Comment by kjozwiak** [comment]
@stephendonner mind taking a look to see if you can reproduce it on `macOS`. Seemed like it was verified/working as per https://github.com/brave/brave-browser/issues/34249#issuecomment-1809200829.

**Comment by stephendonner** [comment]
> @stephendonner mind taking a look to see if you can reproduce it on `macOS`. Seemed like it was verified/working as per [#34249 (comment)](https://github.com/brave/brave-browser/issues/34249#issuecomment-1809200829).

Confirmed; still an issue - commented: https://github.com/brave/brave-browser/issues/34522#issuecomment-1826859415

**Comment by simonhong** [comment]
Left comment - https://github.com/brave/brave-browser/issues/34522#issuecomment-1827025260

**Comment by stephendonner** [comment]
## Verified `PASSED` using

```
Brave | 1.61.90 Chromium: 119.0.6045.163 (Official Build) beta (x86_64)
-- | --
Revision | 0e0de020c4ef9621e8a67a103299899837ce85a1
OS | macOS Version 11.7.10 (Build 20G1427)
```


example | example
---------|---------
<img width="143" alt="Screen Shot 2023-11-27 at 10 14 48 AM" src="https://github.com/brave/brave-browser/assets/387249/66aa6520-687b-47e8-924f-c2216a4222a6"> | <img width="149" alt="Screen Shot 2023-11-27 at 10 16 01 AM" src="https://github.com/brave/brave-browser/assets/387249/4bdb6260-fab5-4516-9c10-d26176530231">
