### ISSUE TITLE
Tab mute button not working for some users

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#36398]
## Description 

After the latest update to v1.63.162, some users are unable to mute individual tabs for a site if more than one tab for that site is open. For these users, opening more than one Twitch tab (for example), muting one tab using the icon on the tab, ends up muting both tabs. User's description of the behavior:

> _When I start watching a streamer on twitch on tab A and than open another twitch on tab B and watch a different streamer. The audio icon is showing on tab A and not on tab B but I can hear both audio content of both streamer on tab A. Muting tab B will not effect anything and can still hear from both tabs but muting tab A will mute from both content. I use mute tab and not mute site. The same thing also happen when I did the same for youtube._

One user recorded the behavior here:
https://streamable.com/q09sk2

## Steps to Reproduce

   1. Open a website with audio and/or video streaming 
   2. Open more than one tab on that site and stream audio/video on each tab
   3. Attempt to mute the audio on one of these tabs

## Actual result:

Both tabs are muted

## Expected result:
Only the tab that was clicked on should be muted

## Reproduces how often: 

Easily for the users encountering it

## Brave version (brave://version info)

1.63.162

## Miscellaneous Information:

User reports:
https://community.brave.com/t/sounds-coming-out-from-the-same-tab/533480
https://community.brave.com/t/unable-to-mute-browser-tabs-after-recent-update/533161

**Comment by AustinGitHub** [comment]
I can also vouch for this, as it is happening to me and it's very frustrating

**Comment by AustinGitHub** [comment]
@rebron can you also add the Regression tag? This is caused from a recent update/change as I haven't had this issue before. Thanks!

**Comment by SaphiLC** [comment]
It's REALLY annoying, hope it can be fixed fast, I'm checking alternative browsers until it's fixed, breaks my daily use of Brave 100%
videos also behave really weird when 2 tabs of the same site are open :(

**Comment by plakonn** [comment]
closing the single tab with volume icon will also make other tabs of the same source unable to play video... rly annoying

**Comment by Brave-Matt** [comment]
More users reporting:
https://community.brave.com/t/issue-with-audio-linking-across-multiple-tabs-unable-to-independently-mute-tabs/535516/4

**Comment by SaphiLC** [comment]
Looks like its fixed in v1.63.169
Thanks.

**Comment by plakonn** [comment]
Not for me.

> Looks like its fixed in v1.63.169 Thanks.

**Comment by eglepere** [comment]
Not fixed on v1.63.169 for me either.

**Comment by Saoiray** [comment]
@SaphiLC @plakonn @eglepere kind of interesting how it resolved for some in the update but not in others. What OS are each of you using? (Please be as specific as possible, like Windows 10, Windows 11 Pro, Mac Sonoma 14.4, etc) 

So far at least one I've seen who said it was resolved had been on Windows. Are those of you saying not fixed on Mac or Linux? Or you on Windows as well?

**Comment by eglepere** [comment]
> @SaphiLC @plakonn @eglepere kind of interesting how it resolved for some in the update but not in others. What OS are each of you using? (Please be as specific as possible, like Windows 10, Windows 11 Pro, Mac Sonoma 14.4, etc)
> 
> So far at least one I've seen who said it was resolved had been on Windows. Are those of you saying not fixed on Mac or Linux? Or you on Windows as well?

Edition	Windows 10 Home
Version	22H2
Installed on	‎02/‎11/‎2023
OS build	19045.4046
Experience	Windows Feature Experience Pack 1000.19053.1000.0

**Comment by plakonn** [comment]
> @SaphiLC @plakonn @eglepere kind of interesting how it resolved for some in the update but not in others. What OS are each of you using? (Please be as specific as possible, like Windows 10, Windows 11 Pro, Mac Sonoma 14.4, etc)
> 
> So far at least one I've seen who said it was resolved had been on Windows. Are those of you saying not fixed on Mac or Linux? Or you on Windows as well?

**Windows 11 Version 23H2** (Build 22631.3235); I also had this issue on 22H2, Fresh install of Brave Linux does not have that issue (running on the same hardware)

**This bug makes the browser unusable imho (it's not like i can't mute tabs... I can't play video on tabs i have once played video on and closed em)**

Steps to reproduce in my case:
1. open tabs of same source (at least 2 tabs; Youtube for example)
2. Play audio/video on one of 2 tabs, that one tab will get audio playing icon (no other tab of the same source (YouTube in this case) can get that icon anymore)
3. closing the tab with audio icon will make other tabs of the same source unable to play video/audio (sometimes F5 will make the tab to get audio icon and fix video for other same-source tabs (untill its closed again), but more often restart of whole browser is needed)

I don't want to mislead anyone but i think it may be chromium bug since i saw similar thing on chrome although it's not happening anymore (but im not rly sure with this one, i switch browsers quite often).
I also have many tabs open every time so it may be triggered by some RAM stuff probably... (just guessing)

sorry for bad english

**Comment by JDThralls** [comment]
It is certainly not fixed for me either, it seems to only have become more inconsistent.
Sometimes, the issue does not show up for hours on end and other times, it persists a full browser or even a system restart.
Sometimes, the bug even does not occur for the first two or three tabs but does for any tabs opened after that.

OS: Manjaro Linux
Kernel: 6.7.7-1-MANJARO
DE: Plasma 5.27.11
DS: X11 / Xorg

**Comment by SaphiLC** [comment]
> @SaphiLC @plakonn @eglepere kind of interesting how it resolved for some in the update but not in others. What OS are each of you using? (Please be as specific as possible, like Windows 10, Windows 11 Pro, Mac Sonoma 14.4, etc)
> 
> So far at least one I've seen who said it was resolved had been on Windows. Are those of you saying not fixed on Mac or Linux? Or you on Windows as well?

spoke too soon, yesterday the issue came back :( not sure if "volume master" extension has to do with it (? but yeah, bug still happening, so frustrating.

OS: Windows 10 Pro 22H2

**Comment by plakonn** [comment]
Brave: 1.64.109 Chromium: 123.0.6312.58; And it seems to be working finally!!!!!

**Comment by JDThralls** [comment]
Appears to be working for me now too.

**Comment by rebron** [comment]
Closing per last two comments.
