### ISSUE TITLE
Getting Error code: SIGILL when loading YouTube pages (v1.63.165)

### ISSUE THREAD

**Issue by sudoshindo** [brave/brave-browser#36573]
## Description 
Getting an error that says:

Aw, Snap! Something went wrong while displaying this webpage.
Error code: SIGILL

It seems that the error only happens on YouTube pages. If I hard-refresh the page it actually loads and navigating to other pages produces no issues, but initiating a new page load leads to the error again.

After downgrading to **v1.63.162** the error stopped appearing.

## Steps to Reproduce

   1. Visit YouTube

## Actual result:

https://global.discourse-cdn.com/brave/original/3X/6/8/6863e1f42831fb8a238683b7a1fa85b6d6d53e8e.png

## Expected result:

The page should just load.

## Reproduces how often: 

It consistently happens whenever I load various pages on YouTube.

## Brave version (brave://version info)

**I'm sorry if this isn't the expected format, but I just downgraded and I don't want to go back to the broken version at the moment**

v1.63.165
Linux (Fedora 39)

## Version/Channel Information:

- Can you reproduce this issue with the current release?
    Yes
- Can you reproduce this issue with the beta channel? 
    Didn't try
- Can you reproduce this issue with the nightly channel? 
    Didn't try

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
    Didn't try
- Does the issue resolve itself when disabling Brave Rewards? 
    Didn't try
- Is the issue reproducible on the latest version of Chrome? 
    Didn't try

**Comment by rebron** [comment]
@sudoshindo When you get a chance can you update to 1.63.169 and let us know if you're still seeing the issue?

**Comment by FloBEAUG** [comment]
@rebron Hello, I can confirm it's still happening in 1.63.169 (Linux mint 21.3)
Lots of SIGKILL / SIGSEGV playing youtube videos.
And some times it crashes the whole browser.

**Comment by sudoshindo** [comment]
As the person who created the issue, I want to say that I've been unable to test the latest version yet because I have hardware issues unrelated to this Brave bug. Hopefully I can deal with it quickly so I can get back to testing this bug.

**Comment by sudoshindo** [comment]
I'm back.
I'm currently on the 1.63.169 version.
It looks like the issue is solved.
Is the issue something that happened in upstream Chromium or is it Brave-specific?

**Comment by sudoshindo** [comment]
This error started happening to me again today, and I may have discovered additional information about this issue.

Here is my current brave://version info
(even though it might not be relevant)

Brave
1.64.109 Chromium: 123.0.6312.58 (Official Build) (64-bit) 
Revision
ded360c0dc8a4bd8aecb9cbe32a7aa4477d42246
OS
Linux (Fedora 39)

Okay, so today I opened a YouTube tab, `Error code: SIGILL` started happening again.

What I discovered is that this issue may be directly related to another issue I participated in, found here #33033 

Here are the actions I took before the problem stopped happening:

- I downgraded to 1.63.174
- I upgraded again to 1.64.109
- I logged out of my Google/YouTube account
- I ran `sudo sed -i -e 's|-stable|-stable --password-store=basic|g' /usr/share/applications/brave-browser.desktop`
- I logged in to YouTube again

It stopped happening.

Something I learned from issue #33033 is that after every Brave update, I should run `sudo sed -i -e 's|-stable|-stable --password-store=basic|g' /usr/share/applications/brave-browser.desktop` again to make sure my logins are preserved. If I don't, my assumption is that this "breaks" Brave's ability to store or read cookies. That issue also contains the context on why I need to run Brave with `--password-store=basic`, I will not repeat it here.

So this time around, I just forgot to run that command after I updated Brave on March 21.
Surprisingly, a lot of my logins actually get preserved this time, but now it causes an error instead, specifically on YouTube.

**Comment by KelvinNovais** [comment]
Also happening for me, but not for YouTube; it happens once in a while when I launch brave.

Brave	1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit) 
Revision	fc7619ef621fe4e6a0fa8b16c718f78ffc97a861
OS	Linux (Fedora 40)
JavaScript	V8 12.6.228.21
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Command Line	/opt/brave.com/brave/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --sync-url=https://sync-v2.brave.com/v2 --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --component-updater=url-source=https://go-updater.brave.com/extensions

**Comment by Brave-Matt** [comment]
Tons of users are still encountering this issue:
https://community.brave.com/t/error-code-sigill-in-fedora-40/557081/22

**Comment by 2uasimojo** [comment]
I was on f39 and brave wouldn't install at all -- some gpg error. It looked like a known problem with f39 so I upgraded to f40. Brave was then able to install at `1.68.128-1.x86_64`, but wouldn't open -- all tabs got `SIGILL`, even settings. Downgraded to `1.67.134-1.x86_64` and things seem copacetic (so far).

**Comment by dobbsrx** [comment]
I am on Brave 1.68.134 and I am getting SIGILLs on random tabs. Noticed it the most on twitch, but also random other pages including YouTube, discord, and local HTTP pages.

EndeavorOS
Plasma 6.1.3
Platform X11 
Kernel 6.10.2-arch1-2

**Comment by 2uasimojo** [comment]
Update: Since my [comment above](https://github.com/brave/brave-browser/issues/36573#issuecomment-2259250091) I haven't encountered this problem again. I've upgraded several times, now on "[Version 1.78.97 Chromium: 136.0.7103.93 (Official Build) (64-bit)](https://brave.com/latest/)" and f42.

**Comment by sudoshindo** [comment]
I'm going to close this because I'm not encountering this issue anymore.

I cannot 100% confirm the cause, I'm just going to assume that it really was the way I was handling the `--password-store=basic` flag. Either that, or the old RAM that I replaced was somehow causing it.

Now, instead of directly modifying `/usr/share/applications/brave-browser.desktop` which would get reverted every time I receive a Brave update, I created a copy at `~/.local/share/applications/brave-browser.desktop` and that's the one I would modify. It always takes precedence over the `.desktop` file found in `/usr` and any updates to the `brave-browser` package will not affect it.
