### ISSUE TITLE
Update "Quick commands" to be "Quick Commands" - follow up to #36777

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-browser#36845]
## Description 

On macOS on `1.63.174` "Quick Commands" is listed in the macOS app menu and hamburger menu with both words capitalized. In `1.66.2`, only the first word is capitalized "Quick commands" - it should probably match current release.

@rebron should say how it should look for other OS-es.

## Steps to Reproduce

   1. Install 1.66.2
   2. Look at hamburger menu --> see "Quick commands"
   3. Look at app menu (macOS) --> see "Quick commands"

## Actual result:

1.66.2:

Example | Example
--- | ---
<img width="1473" alt="3" src="https://github.com/brave/brave-core/assets/28145373/30f71564-1717-436e-a323-27ef32f8fd80"> | <img width="1199" alt="4" src="https://github.com/brave/brave-core/assets/28145373/c03d1a7a-528e-4ef0-8b64-521b58559452">

## Expected result:

1.63.174:

Example | Example
--- | ---
<img width="1180" alt="1 63 174" src="https://github.com/brave/brave-browser/assets/28145373/f34fce97-1082-4003-81b4-f9c2f9b5827f"> | <img width="1422" alt="1 63 174 2" src="https://github.com/brave/brave-browser/assets/28145373/14ebb3c1-1045-45c3-a1be-a733616e8486">

## Reproduces how often: 

easily

## Brave version (brave://version info)

```
Brave	1.66.2 Chromium: 123.0.6312.46 (Official Build) nightly (x86_64) 
Revision	295b49e6d8891d671e4e10a1066eb74fd42297e8
OS	macOS Version 13.6.4 (Build 22G513)
```

## Version/Channel Information:

- Can you reproduce this issue with the current release? 1.63.x no
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 1.66.x yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

cc @rebron

**Comment by abhinav26966** [comment]
Hi Brave Team, I am interested in working on this issue and would like to request it to be assigned to me. @LaurenWags @rebron

**Comment by bsclifton** [comment]
@abhinav26966 go ahead and work on it 😄 You can submit a pull request and you can tag myself or @rebron. Thanks!

**Comment by pk0dev** [comment]
I wanted to work on this and start contributing to brave, I realized that my current laptop won't be able to handle this project :smiling_face_with_tear: so I'll try contributing later when I have a decent laptop.

**Comment by 4nshuman** [comment]
Hello @bsclifton, big fan here and would love to contribute. Is this issue open for me to take up ?

**Comment by 4nshuman** [comment]
Hello @bsclifton, @rebron.
This was a cool issue to work on, I have fixed the issue. The issue in itself was pretty easy to fix but I had the opportunity to setup the entire brave dev environment.
Enjoyed every road block on the activity !! :D :D

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (arm64)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | macOS Version 14.6.1 (Build 23G93)
```

Verified using the STR from the description https://github.com/brave/brave-browser/issues/36845#issue-2188928080

Confirmed updated text `Quick Commands` is shown.

  - hamburger menu --> "Quick Commands"
  - app menu (macOS) --> "Quick Commands"

hamburger menu | app menu
------- | ------
![Image](https://github.com/user-attachments/assets/e26b8aae-618c-41ea-9db8-2776c28116d2)|![Image](https://github.com/user-attachments/assets/4d47f550-84b4-433d-862f-8d135c8eef8a)

**Comment by MadhaviSeelam** [comment]
Verification `in progress` using
```
Brave | 1.72.83 Chromium: 130.0.6723.58 (Official Build) beta (64-bit)
-- | --
Revision | b49615851cd2dc4b1c3f5f13d3207d3c032bfd8d
OS | Windows 11 Version 23H2 (Build 22631.4317)
```

Verified using the STR from the description https://github.com/brave/brave-browser/issues/36845#issue-2188928080

Confirmed updated text `Quick Commands` is shown.-  FAILED.  Text is not updated

  - hamburger menu --> "Quick Commands"

![Image](https://github.com/user-attachments/assets/2166cd50-6b31-459b-b17f-ebb2685aff06)

**Comment by LaurenWags** [comment]
Verified with

```
Brave | 1.72.97 Chromium: 131.0.6778.24 (Official Build) beta (64-bit)
-- | --
Revision | 4d800b613ffedb81f742cfd99cb700fc3d4c215a
OS | Linux
```

Confirmed Linux still shows "Quick commands" as this matches the casing for other items on the hamburger menu.

![Image](https://github.com/user-attachments/assets/08324cc2-48e7-4e26-b59c-3cc0f0152810)
