### ISSUE TITLE
Brave ignores /etc/hosts file settings

### ISSUE THREAD

**Issue by nprime496** [brave/brave-browser#39028]
### Description

My changes in `/etc/hosts` file to update DNS are ignored by Brave. I tried on Firefox and Chrome, the configuration works.

There are already similar issues filled (#13332 and https://github.com/brave/browser-laptop/issues/3750 ).

I disabled DNS over HTTP, no result.

I restarted Brave, no result.

I restarted my computer twice, no result.

Again, my other browsers worked immediately.

Please, I did not plan to spend so much time on this. What is the problem and the solution ?

### Steps to reproduce

1. `sudo nano /etc/hosts`
2. add the following line 
```
0.0.0.0 twitter.com
```
3. Restart the network manager : `sudo service NetworkManager restart`

4. Test that the loopback is applied
Expected result:
```
$ ping twitter.com
PING twitter.com (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.037 ms
```

5. Try to access the site using Brave browser.

### Actual result

The site opens.

### Expected result

The site should not open as a loopback is configured.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit) 
Revision	07af53490e0a52336cfb99a376f87671be258049
OS	Linux

### Channel information

- [X] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [X] with Brave Shields disabled
- [X] with Brave Rewards disabled
- [X] in the latest version of Chrome

### Miscellaneous information

This is a reccurent and persistent bug that has no explanation and workaround of my knowing. 

Related posts across the web : 
https://community.brave.com/t/hosts-file-localhost-loopback-failure-for-127-0-0-1-twitter-com/470023 (check this, it is very in depth experiment with reports)
https://community.brave.com/t/brave-seems-to-be-igoring-my-hosts-file-settings/427045/5 
https://community.brave.com/t/brave-doesnt-use-hosts-file-anymore/440885
https://www.reddit.com/r/brave_browser/comments/nhmlmb/make_brave_behave_a_hosts_file/
https://github.com/brave/browser-laptop/issues/3750

**Comment by fmarier** [comment]
This works for me on Ubuntu 22.04 with systemd-resolved.

Can you share the output of the following?

```
$ cat /etc/resolv.conf | grep -v "^#"

nameserver 127.0.0.53
options edns0 trust-ad
search lan

$ resolvectl status
Global
       Protocols: -LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 3 (wlp0s20f3)
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6
         Protocols: +DefaultRoute +LLMNR mDNS=resolve -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1
        DNS Domain: lan

Link 10 (enx98fdb49ce22d)
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6
         Protocols: +DefaultRoute +LLMNR mDNS=resolve -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.1.1
       DNS Servers: 192.168.1.1
        DNS Domain: lan
```

**Comment by nprime496** [comment]
Hi, the output is 

```
$ cat /etc/resolv.conf | grep -v "^#"

nameserver 127.0.0.53
options edns0 trust-ad
search .
```

**Comment by rillian** [comment]
@nprime496 Can you also share how you installed brave? Native packages? Snap or Flatpak? From brave.com or another source? I'm wondering if the packaging is hiding your /etc/hosts or otherwise affecting the resolver.

**Comment by nprime496** [comment]
> @nprime496 can you check if the domain names resolve correctly in `brave://net-internals/dns#dns`? There's also a button there to "clear resolver cache", which might be worth checking.
> 
> And please check if clearing/disabling browser cache changes anything (e.g. a hard reload can be done with shift+ctrl+r, cache can be cleared at `brave://settings/clearBrowserData`, developer tools also have a "disable cache" checkbox).
> 
> I only see pages load with a hosts entry to block their domain if they were previously loaded without the hosts entry. Otherwise they're inaccessible. And it seems the behavior is the same in Brave and Chromium, but different in Firefox.

It resolves correctly using `brave://net-internals/dns#dns`.

The output is : 
`Resolved IP addresses of "twitter.com": ["0.0.0.0"].`

Yet the site site is still accessible.

The hard reload using  `brave://settings/clearBrowserData` is a too destructive solution for me and I don't want to do it every day, I am automating something with my host file.


@rillian for the installation, I do not recall, how can I check it ?

**Comment by rillian** [comment]
> for the installation, I do not recall, how can I check it ?

It depends on your distribution and desktop environment. Generally, look for the package source in whatever tool you use to install/update software. For example, the gnome 'Software" application on Fedora has a popup menu listing the source paths (flatpak or rpm).
![image](https://github.com/brave/brave-browser/assets/225102/083b2358-6eaa-47d0-b866-c3a471dffb6e)

On the command line you can try things like
> dpkg-query --search brave-browser
or
> rpm -qf /usr/bin/brave-browser
or
> flatpak list | brave Brave

To see if there is a version installed through one of those systems.

**Comment by bsclifton** [comment]
@nprime496 has there been any update on your side for this?

**Comment by saichander17** [comment]
This issue still exists!

**Comment by systemOverview** [comment]
The issue still exists, any idea to why does it seem to get the loopback address on brave://net-internals/dns#dns but sources the address somewhere else when actually accessed?

**Comment by nprime496** [comment]
@bsclifton sorry for the lack of response, I go caught up by other things and my tech stack changed a lot so I can't even relate no more to the issue.

**Comment by MarekMalevic** [comment]
... I have uninstalled Brave and then found out I had the same problem even with Firefox. And I immediately realized the problem was I have to define subdomains in /etc/hosts for it to properly work. If I set there www.google.com along with google.com then Brave respects it and the page is not shown.

That is why I am editing this comment. It was my bad.

**Comment by bsclifton** [comment]
@MarekMalevic thanks for the update 😄
