### ISSUE TITLE
Segmentation fault when launching a second window via terminal

### ISSUE THREAD

**Issue by srirambv** [brave/brave-browser#4142]
## Description 

Segmentation fault when launching a second window via terminal. 

## Steps to Reproduce

   1. Launch brave from terminal
   2. Open a new terminal window and launch a second window
   3. Console logs segmentation fault and exits but the second browser window is still opened

## Actual result:

Release (Manjaro): No crash dump ID generated for release on Ubuntu
```
User namespaces are not detected as enabled on your system, brave will run with the sandbox disabled
Opening in existing browser session.
[106257:106257:0417/082009.710955:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)
```
Beta: [Crash Dump](https://stats.brave.com/dashboard#crash/5cb7201bdb1cfb001fc6b64b)
```
brave-browser-beta 
--2019-04-17 08:46:19--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.21.7
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.21.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: ‘/dev/fd/4’

     0K  
 Crash dump id:  5ad446cca388b589 
                                                  100% 2.18M=0s

2019-04-17 08:46:19 (2.18 MB/s) - ‘/dev/fd/4’ saved [16/16]

Segmentation fault (core dumped)
```
Dev: [Crash dump](https://stats.brave.com/dashboard#crash/5cb72045db1cfb001fc6ba74)
```
brave-browser-dev
--2019-04-17 08:47:01--  https://laptop-updates.brave.com/1/bc-crashes
Resolving laptop-updates.brave.com (laptop-updates.brave.com)... 151.101.21.7
Connecting to laptop-updates.brave.com (laptop-updates.brave.com)|151.101.21.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16 [text/html]
Saving to: ‘/dev/fd/4’

     0K          
 Crash dump id:  16e3a3a988197e80 
                                          100% 2.06M=0s

2019-04-17 08:47:01 (2.06 MB/s) - ‘/dev/fd/4’ saved [16/16]

Segmentation fault (core dumped)
```

## Expected result:
No segmentation fault to be shown when launching a second window via terminal

## Reproduces how often: 

Easy

## Brave version (brave://version info)

Brave | 0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
-- | --
Revision | e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS | Linux

### Reproducible on current release:
- Does it reproduce on brave-browser dev/beta builds? 
Yes
### Website problems only:  
- Does the issue resolve itself when disabling Brave Shields? 
N/A
- Is the issue reproducible on the latest version of Chrome? 
N/A
### Additional Information

Issue originally reported on community.  https://community.brave.com/t/second-launch-gives-segmentation-fault/53664/5

cc: @fmarier @bbondy

**Comment by fmarier** [comment]
I think I've also run into this on my personal laptop (Debian unstable, Brave release is my default `x-www-browser`). I hadn't been able to narrow it down to the second launch but that makes sense now since I leave the browser open all the time and it seems to happen when I click on links in akregator, emacs, mutt.

I've also noticed a strange `xdg-open`  behaviour (it opens two new tabs in Brave, and then it also opens the URL in Firefox, so 3 times in total) but everything looks good when launching URLs with `sensible-browser` instead.

**Comment by fmarier** [comment]
Other than making `xdg-open` annoying, it doesn't seem to cause any noticeable problems, so I'm not sure what's actually crashing.

**Comment by davidpodrebarac** [comment]
I have a similar problem, opening external links opens 3 new tabs with the same url. Opening links directly from the terminal results in segmentation fault, but it only opens 1 new tab.

**Comment by teresaejunior** [comment]
Clicking on links in the desktop brings that annoying popup on Xubuntu too. Here is a strace, if it may help: https://gist.githubusercontent.com/teresaejunior/e5c0f6b51f2d93e2ffe4fda1953d5b4d/raw/2d5d665b7f72b2e6421627ff6e8609d2b37144a4/strace

**Comment by maximbaz** [comment]
Workaround to make `xdg-open` work as expected is to make sure the executable that `brave.desktop` is calling always returns `0` exit code, for example make it execute a wrapper script like this one:

```
#!/bin/sh

/usr/bin/brave "$@" || true
```

**Comment by expl0ratory** [comment]
Great workaround, I was about to abandon the browser

**Comment by funkybob** [comment]
Will a packaged release version include a fix for this?

**Comment by fmarier** [comment]
I'm going to take a look at this, it's a pretty bad papercut.

**Comment by lasombra** [comment]
Interesting data. After applying the workaround described by @maximbaz I noticed, that brave coredumps every time I click on a link. This is on Fedora 30 x86_64.
```
Jul 08 08:50:04 modok kernel: brave[28553]: segfault at 10 ip 000055cddae2a0bd sp 00007ffdac8144f0 error 4 in brave[55cdd6c5d000+6d74000]
Jul 08 08:50:04 modok kernel: Code: 80 7b 17 00 79 0c 48 8b bd f0 fe ff ff e8 fb c5 80 fe 48 8d 85 60 fe ff ff 0f 57 c0 0f 11 85 60 fe ff ff 48 89 85 58 fe ff ff <49> 8b 44 24 10 49 3b 44 24 08 75 0e 31 c0 48 89 85 a8 fe ff ff e9
Jul 08 08:50:04 modok systemd[1]: Started Process Core Dump (PID 28703/UID 0).
Jul 08 08:50:04 modok audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@61-28703-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 08 08:50:05 modok systemd-coredump[28706]: Process 28553 (brave) of user 20682 dumped core.
                                               
                                               Stack trace of thread 28553:
                                               #0  0x000055cddae2a0bd n/a (brave)
                                               #1  0x000055cdd938905c n/a (brave)
                                               #2  0x000055cddb3465ac n/a (brave)
                                               #3  0x000055cdda41c9e6 n/a (brave)
                                               #4  0x000055cdd93891fe n/a (brave)
                                               #5  0x000055cdd9388545 n/a (brave)
                                               #6  0x000055cddb3465ac n/a (brave)
                                               #7  0x000055cdda41c9e6 n/a (brave)
                                               #8  0x000055cdd93881de n/a (brave)
                                               #9  0x000055cdd9339d0e n/a (brave)
                                               #10 0x000055cdd9339a6e n/a (brave)
                                               #11 0x000055cddb3465ac n/a (brave)
                                               #12 0x000055cdda41c9e6 n/a (brave)
                                               #13 0x000055cdd934784d n/a (brave)
                                               #14 0x000055cdd934566a n/a (brave)
                                               #15 0x000055cdd9366336 n/a (brave)
                                               #16 0x000055cdd8547bde n/a (brave)
                                               #17 0x000055cdd935fdad n/a (brave)
                                               #18 0x000055cdd935fc60 n/a (brave)
                                               #19 0x000055cdd935fcc4 n/a (brave)
                                               #20 0x000055cdd85255c8 n/a (brave)
                                               #21 0x000055cdd91e1ac8 n/a (brave)
                                               #22 0x000055cdd7a7a7d1 n/a (brave)
                                               #23 0x000055cdd7e7703e n/a (brave)
                                               #24 0x000055cdd7a792bb n/a (brave)
                                               #25 0x000055cdd7a7c7cb n/a (brave)
                                               #26 0x000055cdd7a77a60 n/a (brave)
                                               #27 0x000055cdd919809a n/a (brave)
                                               #28 0x000055cdd91cf020 n/a (brave)
                                               #29 0x000055cdd9196781 n/a (brave)
                                               #30 0x000055cdd6f57713 ChromeMain (brave)
                                               #31 0x00007f6fd5381f33 __libc_start_main (libc.so.6)
                                               #32 0x000055cdd6c5d02a _start (brave)
                                               
                                               Stack trace of thread 28569:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28574:
                                               #0  0x00007f6fd6a2abec read (libpthread.so.0)
                                               #1  0x000055cdd8528bc0 n/a (brave)
                                               #2  0x000055cdd9635e48 n/a (brave)
                                               #3  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #4  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28568:
                                               #0  0x00007f6fd545963e epoll_wait (libc.so.6)
                                               #1  0x000055cdd9648fba n/a (brave)
                                               #2  0x000055cdd9646782 n/a (brave)
                                               #3  0x000055cdd963b205 n/a (brave)
                                               #4  0x000055cdd95e729f n/a (brave)
                                               #5  0x000055cdd95c3c2f n/a (brave)
                                               #6  0x000055cdd7a82a84 n/a (brave)
                                               #7  0x000055cdd95fe028 n/a (brave)
                                               #8  0x000055cdd9635e48 n/a (brave)
                                               #9  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #10 0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28566:
                                               #0  0x00007f6fd545963e epoll_wait (libc.so.6)
                                               #1  0x000055cdd9648fba n/a (brave)
                                               #2  0x000055cdd9646782 n/a (brave)
                                               #3  0x000055cdd963b205 n/a (brave)
                                               #4  0x000055cdd95e729f n/a (brave)
                                               #5  0x000055cdd95c3c2f n/a (brave)
                                               #6  0x000055cdd95f61f4 n/a (brave)
                                               #7  0x000055cdd95fe028 n/a (brave)
                                               #8  0x000055cdd9635e48 n/a (brave)
                                               #9  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #10 0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28567:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28575:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28577:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28582:
                                               #0  0x00007f6fd6a274d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632202 n/a (brave)
                                               #2  0x000055cdd9632ab4 n/a (brave)
                                               #3  0x000055cdd963275f n/a (brave)
                                               #4  0x000055cdd95eea7c n/a (brave)
                                               #5  0x000055cdd95ee6e4 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28570:
                                               #0  0x00007f6fd5450e3b __select (libc.so.6)
                                               #1  0x000055cdd9595706 n/a (brave)
                                               #2  0x000055cdd9635e48 n/a (brave)
                                               #3  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #4  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28580:
                                               #0  0x00007f6fd6a274d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632202 n/a (brave)
                                               #2  0x000055cdda724d78 n/a (brave)
                                               #3  0x000055cdd95fd5af n/a (brave)
                                               #4  0x000055cdd9635e48 n/a (brave)
                                               #5  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #6  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28583:
                                               #0  0x00007f6fd6a274d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632202 n/a (brave)
                                               #2  0x000055cdd9632ab4 n/a (brave)
                                               #3  0x000055cdd963275f n/a (brave)
                                               #4  0x000055cdd95a5d34 n/a (brave)
                                               #5  0x000055cdd95e729f n/a (brave)
                                               #6  0x000055cdd95c3c2f n/a (brave)
                                               #7  0x000055cdd95fe028 n/a (brave)
                                               #8  0x000055cdd9635e48 n/a (brave)
                                               #9  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #10 0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28560:
                                               #0  0x00007f6fd544e5c7 __poll (libc.so.6)
                                               #1  0x000055cdd7ddd8f2 n/a (brave)
                                               #2  0x000055cdd95fd5af n/a (brave)
                                               #3  0x000055cdd9635e48 n/a (brave)
                                               #4  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #5  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28572:
                                               #0  0x00007f6fd544e5c7 __poll (libc.so.6)
                                               #1  0x00007f6fd67091de n/a (libglib-2.0.so.0)
                                               #2  0x00007f6fd67095a3 g_main_loop_run (libglib-2.0.so.0)
                                               #3  0x00007f6fd62e9d5a n/a (libgio-2.0.so.0)
                                               #4  0x00007f6fd67324e2 n/a (libglib-2.0.so.0)
                                               #5  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #6  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28571:
                                               #0  0x00007f6fd544e5c7 __poll (libc.so.6)
                                               #1  0x00007f6fd67091de n/a (libglib-2.0.so.0)
                                               #2  0x00007f6fd6709313 g_main_context_iteration (libglib-2.0.so.0)
                                               #3  0x00007f6fd6709361 n/a (libglib-2.0.so.0)
                                               #4  0x00007f6fd67324e2 n/a (libglib-2.0.so.0)
                                               #5  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #6  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28576:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28565:
                                               #0  0x00007f6fd6a2b7b6 waitpid (libpthread.so.0)
                                               #1  0x000055cdd963124d n/a (brave)
                                               #2  0x000055cdd962e833 n/a (brave)
                                               #3  0x000055cdd9635e48 n/a (brave)
                                               #4  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #5  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28578:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95eea50 n/a (brave)
                                               #5  0x000055cdd95ee684 n/a (brave)
                                               #6  0x000055cdd9635e48 n/a (brave)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28579:
                                               #0  0x00007f6fd6a2783c pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632340 n/a (brave)
                                               #2  0x000055cdd963292a n/a (brave)
                                               #3  0x000055cdd9632b01 n/a (brave)
                                               #4  0x000055cdd95ee0bf n/a (brave)
                                               #5  0x000055cdd95ee784 n/a (brave)
                                               #6  0x000055cdd95ee684 n/a (brave)
                                               #7  0x000055cdd9635e48 n/a (brave)
                                               #8  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #9  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28573:
                                               #0  0x00007f6fd545963e epoll_wait (libc.so.6)
                                               #1  0x000055cdd9648fba n/a (brave)
                                               #2  0x000055cdd9646782 n/a (brave)
                                               #3  0x000055cdd963b205 n/a (brave)
                                               #4  0x000055cdd95e729f n/a (brave)
                                               #5  0x000055cdd95c3c2f n/a (brave)
                                               #6  0x000055cdd95fe028 n/a (brave)
                                               #7  0x000055cdd9635e48 n/a (brave)
                                               #8  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #9  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28585:
                                               #0  0x00007f6fd545963e epoll_wait (libc.so.6)
                                               #1  0x000055cdd9648fba n/a (brave)
                                               #2  0x000055cdd9646782 n/a (brave)
                                               #3  0x000055cdd963b205 n/a (brave)
                                               #4  0x000055cdd95e729f n/a (brave)
                                               #5  0x000055cdd95c3c2f n/a (brave)
                                               #6  0x000055cdd95fe028 n/a (brave)
                                               #7  0x000055cdd9635e48 n/a (brave)
                                               #8  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #9  0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28587:
                                               #0  0x00007f6fd6a274d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632202 n/a (brave)
                                               #2  0x000055cdd9632ab4 n/a (brave)
                                               #3  0x000055cdd963275f n/a (brave)
                                               #4  0x000055cdd95a5d34 n/a (brave)
                                               #5  0x000055cdd95e729f n/a (brave)
                                               #6  0x000055cdd95c3c2f n/a (brave)
                                               #7  0x000055cdd95fe028 n/a (brave)
                                               #8  0x000055cdd9635e48 n/a (brave)
                                               #9  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #10 0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28581:
                                               #0  0x00007f6fd6a274d5 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                                               #1  0x000055cdd9632202 n/a (brave)
                                               #2  0x000055cdd9632ab4 n/a (brave)
                                               #3  0x000055cdd963275f n/a (brave)
                                               #4  0x000055cdd95a5d34 n/a (brave)
                                               #5  0x000055cdd95e729f n/a (brave)
                                               #6  0x000055cdd95c3c2f n/a (brave)
                                               #7  0x000055cdd95fe028 n/a (brave)
                                               #8  0x000055cdd9635e48 n/a (brave)
                                               #9  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #10 0x00007f6fd5459303 __clone (libc.so.6)
                                               
                                               Stack trace of thread 28586:
                                               #0  0x00007f6fd544e5c7 __poll (libc.so.6)
                                               #1  0x00007f6fba594ce6 n/a (libpulse.so.0)
                                               #2  0x00007f6fba5861f1 pa_mainloop_poll (libpulse.so.0)
                                               #3  0x00007f6fba586873 pa_mainloop_iterate (libpulse.so.0)
                                               #4  0x00007f6fba586920 pa_mainloop_run (libpulse.so.0)
                                               #5  0x00007f6fba594c2d n/a (libpulse.so.0)
                                               #6  0x00007f6fba50fd1c n/a (libpulsecommon-12.2.so)
                                               #7  0x00007f6fd6a215a2 start_thread (libpthread.so.0)
                                               #8  0x00007f6fd5459303 __clone (libc.so.6)
Jul 08 08:50:05 modok systemd[1]: systemd-coredump@61-28703-0.service: Succeeded.
```

**Comment by jtslear** [comment]
I would not have thought Brace to be the culprit, I was chasing my mime configuration for quite awhile before I stumbled on this issue.  I'd love to help assist in any way I can to help resolve this issue.

My method of reproducing the problem is performing the following:

```
% xdg-open http://icanhazip.com
[23304:23304:0818/173944.150379:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)
[24337:24337:0818/173951.130398:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)
[24490:24490:0818/173951.498205:ERROR:sandbox_linux.cc(369)] InitializeSandbox() called with multiple threads in process gpu-process.
Segmentation fault (core dumped)
xdg-open: no method available for opening 'http://icanhazip.com'
```
I ran an strace on the main pid at the time of the test, results are logged here:

https://gist.githubusercontent.com/jtslear/d81ee5df9c3f8ef0ac83c0e1a5070661/raw/5a83a257cbdf07e5c07a18328339ed7e8305bb8b/strace-brave

---

An odd thing to note is that this is not generating crash reports or dumps as described here: https://github.com/brave/browser-laptop/wiki/Crashes.  Instead I have a crash report from the system.  If by chance you have the ability to pull this crash from Ubuntu, the ID for the above reproduction is `b5ec69dc-c200-11e9-ae48-fa163e983629`.  If you are unable, I've saved it off and can provide it to you in another manner.

**Comment by fmarier** [comment]
I merged [@maximbaz's work-around](https://github.com/brave/brave-browser/issues/4142#issuecomment-504742158) on Friday. While the crash hasn't been identified/fixed yet, it will no longer cause more than one browser window to pop up.

**Comment by funkybob** [comment]
I'm happy the work around is released, but fear that as it no longer bites people, the motivation to fix the root cause will atrophy :/

**Comment by fmarier** [comment]
The work-around has been merged to the Beta (0.70.x) and Dev (0.71.x) branches too.

**Comment by fmestevez** [comment]
As mentioned on the issue linked above, still happening for me on Brave version 1.2.36, Manjaro Linux.

**Comment by fmarier** [comment]
@fmestevez I can definitely reproduce on Brave 1.2 (release) but not on 1.3 (beta), 1.4 (dev) or 1.5 (nightly). So this appears to have been fixed on 1.3 if you get a chance to test on beta.

**Comment by fmestevez** [comment]
Hey @fmarier. I installed the AUR `brave-nightly-bin-1.5.11-2`, but I'm still instantly getting this when clicking on the sandwich menu button:
```
❯ brave-nightly          
[7012:7012:0106/160309.047763:ERROR:sandbox_linux.cc(372)] InitializeSandbox() called with multiple threads in process gpu-process.
[6980:7005:0106/160309.146492:ERROR:rewards_service_impl.cc(206)] Failed to read file: /home/bant/.config/BraveSoftware/Brave-Browser/Default/ledger_state
[7030:7030:0106/160309.167809:ERROR:ledger_impl.cc(102)] Failed to initialize wallet
[7012:7012:0106/160309.190439:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
[6980:6980:0106/160309.691605:ERROR:CONSOLE(0)] "Error in event handler: TypeError: callbackList.fetch-sync-records is not a function
    at chrome-extension://nomlkjnggnifocmealianaaiobmebgil/extension/background.js:13:37", source: chrome-extension://nomlkjnggnifocmealianaaiobmebgil/_generated_background_page.html (0)
[6980:6980:0106/160310.108163:ERROR:CONSOLE(1)] "Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined", source: chrome-extension://odbfpeeihdkbihmopkbjmoonfanlbfcl/background.js (1)
[7017:7024:0106/160311.920577:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
[7017:7024:0106/160311.920944:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[7017:7024:0106/160311.921134:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[7017:7024:0106/160311.921289:ERROR:broker_posix.cc(110)] Error sending sync broker message: Broken pipe (32)
[1]    6980 segmentation fault (core dumped)  brave-nightly
```

This is not an issue on a different PC with Linux Mint. It didn't happen before on this PC until a month or so ago.

No rush anyways! Thanks.

**Comment by fmarier** [comment]
> I installed the AUR brave-nightly-bin-1.5.11-2, but I'm still instantly getting this when clicking on the sandwich menu button:

@fmestevez Is it crashing the whole browser (like #7581) or is it just a coredump which doesn't appear to have any user-visible impact when you open a second tab using something like `xdg-open https://example.com`?

**Comment by fmestevez** [comment]
It crashes the whole browser with exit code 139.

**Comment by fmarier** [comment]
> It crashes the whole browser with exit code 139.

In that case, you're seeing a different issue on that machine. This is most likely #7581 (inherited from the last Chromium merge).

**Comment by btlechowski** [comment]
No longer reproducible

Verification passed on

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Ubuntu 18.04 LTS

Verified test plan from the description

**Comment by srirambv** [comment]
Verification passed on 

Brave | 1.10.88 Chromium: 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{# 657}
OS | Linux

<details>
<Summary>Verified opening a second terminal and launching brave doesn't show any segmentation fault error message</summary>

Terminal 1 Console | Terminal 2 Console
-- | --
![image](https://user-images.githubusercontent.com/17010094/84496314-5e149580-acca-11ea-8d73-30f2ae4eddb7.png) | ![image](https://user-images.githubusercontent.com/17010094/84496336-6a98ee00-acca-11ea-8feb-8dca1d92b407.png)

</details>
