### ISSUE TITLE
HuffPost website stuck in infinite reload when using Shields

### ISSUE THREAD

**Issue by FWDekker** [brave/brave-browser#4149]
## Description 
The [HuffPost website](https://huffpost.com/) sends the user in an infinite loop of reloads when Shields is enabled.

## Steps to Reproduce
1. Ensure that Brave Shields is *enabled*.
2. Accept the consent form.
3. Go to [HuffPost.com](https://huffpost.com/) or [some article on the website](https://www.huffpost.com/entry/israel-flight-attendant-measles-outbreak_n_5cb760a3e4b09dc528ccf851).

## Actual result
The user is sent to the front page even when an article is visited. The page then keeps refreshing itself every second or so.

## Expected result
The page is loaded eventually.

## Reproduces how often
Easily reproduced

## Brave version (brave://version info)
```
Brave     0.62.51 Chromium: 73.0.3683.103 (Official Build) (64-bit)
Revision  e82a658d8159cabbd4938c1660f9bb00b4a82a23-refs/branch-heads/3683@{#902}
OS        Windows 10 OS Build 17763.437
```

## Version/channel information
I have not tried reproducing this bug on other versions.

## Other additional information
- The issue resolves itself when disabling Brave Shields.
- The issue is *not* reproducible on the latest version of Chrome.

**Comment by srirambv** [comment]
Works fine for me on Linux. @btlechowski can you check on Windows?

**Comment by FWDekker** [comment]
I was able to reproduce this on Linux using the steps above. I'm running Kubuntu 18.04 with Brave at the exact same revision as my Windows machine.

After going to `huffpost.com` I am redirected to `https://www.huffpost.com/?guccounter=1`, and after that I am continuously redirected to URLs of the form `https://www.huffpost.com/?guccounter=1&guce_referrer_us=aHR0cHM6Ly9ndWNlLmh1ZmZpbmd0b25wb3N0LmNvbS8&guce_referrer_cs=<some random string>`.

**Comment by FWDekker** [comment]
I mixed up the actual and expected results :man_facepalming: I have now corrected them

**Comment by jeroen7s** [comment]
Same issue here
as soon as I disable blocking for "third party cookies" the site works as normal
blocking All cookies also works

**Comment by srirambv** [comment]
I still cant reproduce this issue on Linux on a clean install of `0.63.48`. Default shields settings just load the site normally.

Here's a screen recording of  it https://youtu.be/AK3AGc7DDEc

Could you guys try clearing the browser cache once and try again?

**Comment by jeroen7s** [comment]
can definitely confirm it still occurs then for me
also still breaks in incognito window
-adblocking on
-3party cookies blocked
-encrypted connections on
-scripts allowed
-3p device recognition blocked

**Comment by btlechowski** [comment]
Reproduced on clean profile by loading `https://huffpost.com/` and consenting to ToS/GDPR. The page started to refresh itself eventually I got an error:
![image](https://user-images.githubusercontent.com/34715963/56809785-f6d12300-6834-11e9-941e-de54a3a2f297.png)

Brave | 0.63.48 Chromium: 74.0.3729.108 (Official Build) (64-bit)
-- | --
Revision | daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS | Windows 10 OS Build 17134.523

@srirambv Do you get consent form when going to `https://huffpost.com/` on clean profile?
![image](https://user-images.githubusercontent.com/34715963/56809991-7e1e9680-6835-11e9-83e2-ba9774b19539.png)

**Comment by FWDekker** [comment]
I created a fresh Ubuntu 18.04 VM and installed Brave 0.63.48. The issue still occurred.

What I find interesting is that your video does not show the "Before you continue..." consent menu when you open the page. It is only after I press "OK" that the redirecting starts. I realise now that I should have included that in the "Steps to Reproduce" section 😕

**Comment by jeroen7s** [comment]
first page_load: `https://www.huffpost.com/`
second page load: `https://www.huffpost.com/?guccounter=1&guce_referrer_us=aHR0c***NvbS8&guce_referrer_cs=q69A9rvs7MC******`
the last part `guce_referrer_cs` keeps changing on every request/every second

**Comment by jeroen7s** [comment]
Can confirm, when loading the site using a VPN to the USA, this issue does not occur
after disabling the VPN, the issue re-appears.

**Comment by FWDekker** [comment]
@jeroen7s Interesting. Can you confirm that it is not because of the VPN itself? For example by using a Europe-based VPN?

**Comment by srirambv** [comment]
@btlechowski @jeroen7s  I don't get a ToS consent and am not behind VPN. Can check with a EU VPN and update here.

**Comment by jeroen7s** [comment]
@FWDekker can confirm, connecing the VPN to Netherlands the issue occurs, connecting from my regular IP (Belgium) the issue also occurs
connecting the VPN to the US the issue is gone (so is the GDPR consent prompt).
All Tested using fresh incognito windows.

**Comment by btlechowski** [comment]
No longer reproducible on 

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

Steps:
1. Clean profile
2. Open `https://www.huffpost.com/`
3. Consent to GDPR if applicable

Note: checked on IP from Poland and US.

**Comment by FWDekker** [comment]
The issue no longer occurs for me either! 👍
