### ISSUE TITLE
Blocked ads sometimes leave additional white space on page

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-browser#4338]
## Description 

Some sites with ads blocked will leave white space on the page where the ad was blocked. In some cases, whitespace seems to be _added_ to the page as well.

Note that this may be related to region as most of the users reporting seem to be outside the US.
 
## Steps to Reproduce

   1. Visit bitcoinbazis.hu
   2. Ensure Shields are set to default or at least that Ads are blocked
[Detailed STR on PR]

## Actual result:

![image](https://user-images.githubusercontent.com/3299098/57322683-f6e4e480-70b8-11e9-8022-193994e99942.png)

## Expected result:
![image](https://user-images.githubusercontent.com/3299098/57322728-1714a380-70b9-11e9-8b55-ba2bb1e489b3.png)

## Reproduces how often: 

Easily

## Version/Channel Information:

Occurs on all channels 
- Can you reproduce this issue with the current release? ✅ 
- Can you reproduce this issue with the beta channel? ✅
- Can you reproduce this issue with the dev channel? ✅
- Can you reproduce this issue with the nightly channel? ✅

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
Yes -- setting Ads control to `Allow ads/tracking` also renders page correctly. 
- Does the issue resolve itself when disabling Brave Rewards?
No
- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

User reports (more to come):
https://community.brave.com/t/this-is-getting-really-annoying/55928
https://community.brave.com/t/page-rendering-issue/58045
![whitespace](https://user-images.githubusercontent.com/3299098/57323216-3b24b480-70ba-11e9-8e78-a361f68efa37.gif)

**Comment by petemill** [comment]
Fixed via https://github.com/brave/brave-core/pull/3121

**Comment by btlechowski** [comment]
Verification passed on

Brave | 0.69.129 Chromium: 77.0.3865.90 (Official Build) (64-bit)
-- | --
Revision | 58c425ba843df2918d9d4b409331972646c393dd-refs/branch-heads/3865@{#830}
OS | Ubuntu 18.04 LTS

Verified `bitcoinbazis.hu`

![image](https://user-images.githubusercontent.com/34715963/65731117-b2d49980-e0c4-11e9-9903-45a25cbfdb78.png)


The issue still reproduces on https://www.dia.net.au/. Logged https://github.com/brave/brave-browser/issues/6190
![image](https://user-images.githubusercontent.com/34715963/65731300-72c1e680-e0c5-11e9-8f16-24c52e5c3b47.png)
