### ISSUE TITLE
Ads grants notification is shown when Ads switch was OFF

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-browser#4340]
## Description 

After upgrade to the latest version, the Ads switch is getting turned OFF automatically. Ads grants and enable Ads notifications are shown on BAT logo. Ads grants notification is not checking Ads switch ON/OFF condition. If Ads is already turned OFF Ads grants notification should not be shown to the user.  
Ads switch turned OFF could be User interface issue. Might be it's ON in the backend and Ads grants notification logic is driven based on it (not sure).

## Steps to Reproduce

   1. Brave beta 0.63.45 (Ads are viewed on this version - profile was created on 17th April)
   2. Upgrade to 0.64.72 
   3. After upgrade Ads switch turned off ( Logged #4339)
   4. Click on BAT logo  in the URL bar
   5. Two notifications are shown on BAT log
   6. 1st Notification for Ads grants (In the Actual result screenshot I have already viewed notification and 
     claimed Ads grants)
  7. Click on the claim and accept Ads grants
   

## Actual result:

Ads grants notification is shown when Ads switch is OFF.

![image](https://user-images.githubusercontent.com/38657976/57325194-22061d00-7127-11e9-95c3-fe1730b4d6fa.png)

![image](https://user-images.githubusercontent.com/38657976/57325217-2df1df00-7127-11e9-930d-6efa8bd46ebe.png)

## Expected result:
Ads grants notification should not be shown when Ads switch is OFF

## Reproduces how often: 

Not sure

## Brave version (brave://version info)

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? NA
- Does the issue resolve itself when disabling Brave Rewards? NA
- Is the issue reproducible on the latest version of Chrome? NA

## Miscellaneous Information:

@brave/legacy_qa @tmancey @rebron

**Comment by rebron** [comment]
cc: @ryanml Related question. Are we showing/prompting Turn on Ads notification after every upgrade if they currently have Ads off. Example user is on 63.55 with Ads Off. See notification and disregards, keeps Ads Off. Upgrades to 64. User shouldn't see Turn on Ads notification again.

Is that right?

**Comment by LaurenWags** [comment]
@rebron I tried the following scenario for what you described, here are my steps:
1. Install 0.62.51
2. Enable Rewards, verify Ads UI does not allow enabling.
3. Go to brave://settings/help
4. Update to 0.63.55 (current release version), relaunch.
5. Get Notification about Ads. Dismiss it and do not enable Ads. Verify Ads panel does have toggle (US location) to enable if desired.
6. Update on `test` channel to 0.64.74. --> No notification to try Ads is observed. Ads are still off on brave://rewards page.

**Comment by tmancey** [comment]
@LaurenWags @mandar-brave @jsecretan @GeetaSarvadnya @alexwykoff I agree Ads being turned off was a bug but another ticket was created. However if a user did turn off ads, should they not still received ad grants for previous rewards? As if so, this ticket can be closed

**Comment by kjozwiak** [comment]
@tmancey agreed about users still receiving ad grant notifications for previous reward earnings even though they have ads disabled, but I think the above issue is about the `Turn on Ads` notification appearing after several upgrades even though the user dismissed the notification on a previous upgrade. We shouldn't be asking users to turn on ads every time they upgrade. However, it doesn't seem like @LaurenWags could reproduce it via https://github.com/brave/brave-browser/issues/4340#issuecomment-491443564.

**Comment by tmancey** [comment]
@kjozwiak This has been resolved as part of #5153. @LaurenWags could you please check this issue as part of #5153

**Comment by tmancey** [comment]
@LaurenWags Can this issue please be retested as part of https://github.com/brave/brave-browser/issues/6612 when merged

**Comment by tmancey** [comment]
Closing issue to be retested as part of #6612 (6612 for users who had ads disabled will see on-boarding again as a one-off. This was discussed with @jsecretan due to migration)

**Comment by LaurenWags** [comment]
Verified passed with

Brave | 1.2.40 Chromium: 79.0.3945.88 (Official Build) (64-bit)
-- | --
Revision | c2a58a36b9411c80829b4b154bfcab97e581f1f3-refs/branch-heads/3945@{#954}
OS | macOS Version 10.14.6 (Build 18G103)

* Confirmed still seeing the `Brave Ads have arrived!` notification as per https://github.com/brave/brave-browser/issues/6612#issuecomment-559132521
* This is logged with https://github.com/brave/brave-browser/issues/7133 and should be resolved in 1.4.x branch
