### ISSUE TITLE
Regional adblock filters are not pre-selected based on locale

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#4367]
Follow up to https://github.com/brave/brave-browser/issues/1931

## Steps to Reproduce

1, Start with a clean profile
2. Set locale to "fr" in `chrome://settings/languages`
3. Restart Brave
4. Visit `brave://adblock`
5. Verify that French regional list is selected

## Actual result:
`FRA: EasyList Liste FR` is not pre-selected

![image](https://user-images.githubusercontent.com/34715963/57416020-a2e41800-71fe-11e9-80b2-ecc981221855.png)

## Expected result:
`FRA: EasyList Liste FR` is pre-selected
![image](https://user-images.githubusercontent.com/34715963/57416078-e50d5980-71fe-11e9-96a3-7c9f480ca819.png)

## Reproduces how often: 

Easily reproduced

## Brave version (brave://version info)

Reproduced on

Brave | 0.64.72 Chromium: 74.0.3729.131 (Official Build) beta(64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

Not reproducible on 

Brave | 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)
-- | --
Revision | 518a41c1fa7ce1c8bb5e22346e82e42b4d76a96f-refs/branch-heads/3729@{#954}
OS | Windows 10 OS Build 17134.523

![image](https://user-images.githubusercontent.com/34715963/57416194-754b9e80-71ff-11e9-9328-decf0f3a2abe.png)

So this is a regression.

Note: also reproduced with Polish language. I also changed system locale, but it didn't fix the issue

cc @brave/legacy_qa @emerick

**Comment by emerick** [comment]
@btlechowski Just double-checking: When you set the locale to "fr", did you also check the option for "Display Brave in this language"? You'll know when you've properly done it, because Brave will then show a button to relaunch the browser. Sorry if you have done this, just wanted to confirm because it's easy to miss.

**Comment by btlechowski** [comment]
@emerick Yes, I did set the language and restarted the browser. Brave was launched in french locale.

**Comment by emerick** [comment]
Had a little bit of time to dig into this. When we pre-select the regional adblock filter based on the current locale, we only perform that check once at startup (otherwise, we'd end up always selecting that region even if the user decided to disable it in brave://adblock...) This means that in order to test this feature, the first run of Brave with the new profile must **already** be using the desired region.

I suggest testing it like this, at least on Windows:

1. Clear the profile
1. Start brave with the `--lang=fr` flag (or whatever other language)
1. Verify that brave://adblock shows the French list is selected
1. Exit brave
1. Start brave with a different language (e.g., `--lang=de`)
1. Verify that brave://adblock still shows the French list is selected
1. Unselect the french list
1. Start brave with the `--lang=fr` flag
1. Verify that brave://adblock still shows the French list is unselected

Something like that.

**Comment by antonok-edm** [comment]
It turns out we have a `langs` field in https://github.com/brave/adblock-resources, and as a result we were trying to use _language_ codes rather than _locale_ codes to preselect filter lists in brave://adblock.

Two of these were addressed in https://github.com/brave/adblock-resources/pull/56, although I haven't checked if that is an exhaustive fix.

**Comment by btlechowski** [comment]
@antonok-edm When the fix will be available in nightly?

**Comment by antonok-edm** [comment]
@btlechowski the fix I mentioned above is just for the Japanese and Indian lists, but that's already available everywhere (shipped as a component update).

If there are still other locales that should be pre-selecting lists and aren't, let me know and I can push out a similar update for those as well.

**Comment by btlechowski** [comment]
Still reproducible 

Brave | 1.37.46 Chromium: 98.0.4758.87 (Official Build) nightly (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 7 Service Pack 1 (Build 7601.24544)


After changing language to CZE, `Easylist-Cookie List - Filter Obtrusive Cookie Notices` was added to the list
I would expect `CZE, SVK: EasyList Czech and Slovak` to be add. This could be related to https://github.com/brave/brave-browser/issues/20825

![image](https://user-images.githubusercontent.com/34715963/154096160-786dfa7d-3f53-4428-8280-e696062a40bf.png)

**Comment by stephendonner** [comment]
## Verified `PASSED` using 

Brave | 1.50.91 Chromium: 111.0.5563.64 (Official Build) beta (x86_64)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | macOS Version 11.7.4 (Build 20G1120)

### Steps:
1. installed `1.50.91`
2. set operating system's region to the respective locale, from below
3. restarted the OS
4. launched Brave
5. opened `brave://adblock`
6. confirmed each locale's default, pre-selected list(s)

`fr` | `pl` | `cze` | `ja`
--|--|--|--
<img width="1312" alt="Capture d’écran 2023-03-14 à 17 07 55" src="https://user-images.githubusercontent.com/387249/225173494-a7cb0b58-5aa0-4ecf-913c-25ee8557cd58.png"> | <img width="1312" alt="Zrzut ekranu 2023-03-14 o 17 16 14" src="https://user-images.githubusercontent.com/387249/225173367-fec1126c-de26-49c8-97d2-8139d7275b59.png"> | <img width="1312" alt="Snímek obrazovky 2023-03-14 v 17 23 28" src="https://user-images.githubusercontent.com/387249/225173305-9c7f888f-51c2-4ef7-876f-bff62499ec5b.png"> | <img width="1312" alt="スクリーンショット 2023-03-14 17 29 23" src="https://user-images.githubusercontent.com/387249/225173443-955c2d58-811a-4aa8-83c6-4b60b18a4362.png">

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.50.93 Chromium: 111.0.5563.64 (Official Build) beta (64-bit)
-- | --
Revision | c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}
OS | Ubuntu 18.04 LTS

Set locale to 'pl' and verified PL lists are set on clean profile
![image](https://user-images.githubusercontent.com/34715963/226996802-67d0bb83-d235-4888-9138-654b34d2927a.png)

Changed locale to 'fr' and verified only 'fr' lists are set - FAILED
 
![image](https://user-images.githubusercontent.com/34715963/226998410-8c8fbba5-77a0-4e8e-aa35-958d90c58f32.png)

Logged: https://github.com/brave/brave-browser/issues/29249

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using
```
Brave | 1.50.107 Chromium: 112.0.5615.39 (Official Build) beta (64-bit)
-- | --
Revision | a0e7b9718a92bcd1cf33b7c95316caff3fc20714-refs/branch-heads/5615@{#753}
OS | Windows 11 Version 22H2 (Build 22621.1413)
```

Steps:

1. installed 1.50.107
2. set operating system's region to the respective locale, from below
3. restarted the OS
4. launched Brave
5. opened brave://adblock
6. confirmed each locale's default, pre-selected list(s)

`es` | 'pl` | `ru` | `ko`
---- | ---- | ---- | ----
<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/228393360-7066ee98-4350-4d93-bf8a-de0415ee6dd0.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/228393563-370d11d7-7813-42e3-a1da-4445c472cdde.png">|<img width="461" alt="image" src="https://user-images.githubusercontent.com/98358127/228393238-bb944f0d-712d-4e66-b08f-c75c48a7d83a.png">|<img width="452" alt="image" src="https://user-images.githubusercontent.com/98358127/228392723-ea003e3b-65f1-4d2a-9c29-36d43a544517.png">

**Comment by srirambv** [comment]
Verification passed on Oppo Reno 5 with Android 13 running 1.50.110 x64 build
- Verified steps from [brave/brave-core#17261](https://github.com/brave/brave-core/pull/17261)
- Verified regional filters for set locale is enabled by default

https://user-images.githubusercontent.com/17010094/229459716-c81b9fb5-5fd5-4983-9c16-c152cdcec1af.mp4
