### ISSUE TITLE
Brave hands when we type something in the search bar for a few seconds

### ISSUE THREAD

**Issue by meet-v** [brave/brave-browser#44903]
### Description

I am facing this issue too on Linux (Zorin OS 17.3 Core) with Brave (Version 1.76.81 Chromium: 134.0.6998.166 (Official Build) unknown (64-bit)). None of the troubleshooting has helped so far.

Issue was previously reported here: https://github.com/brave/brave-browser/issues/17811

### Steps to reproduce

1. Open Brave
2. Start typing in the search bar

### Actual result

Brave app hangs for quite a few seconds completely.

### Expected result

Typing should be reflected on the search bar in real time.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.76.81 Chromium: 134.0.6998.166 (Official Build) unknown (64-bit) 

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

### Miscellaneous information

Doesn't happen on Brave iOS 1.75 (179).
Don't have any other device to try it out elsewhere.

**Comment by mdarbyo** [comment]
I'm experiencing this behavior too using Brave stable version 1.76.82 -- this happens on both Fedora Linux 41 Workstation and Windows 11 Pro.

I have Google set as my default search engine for both normal and private windows. I'm currently testing whether changing my default search engine affects this behavior. Nothing conclusive to report yet.

**Comment by meet-v** [comment]
This happens irrespective of what search engine you are using as default. Tried it in Private Window also, same issue.
Definitely a browser issue.

**Comment by fallaciousreasoning** [comment]
Interesting - this doesn't reproduce for me. Would you guys mind trying some troubleshooting steps to see if we can narrow down what's causing it?

1. Try with a new profile by running `brave-browser --user-data-dir=/tmp/test-dir`
2. Try running with GPU disabled: `brave-browser --disable-gpu`

I think this is probably unrelated to the Search engine.

Out of interest, are you running under Wayland or X?

**Comment by meet-v** [comment]
Yeah, the issue is not consistent. It happens sometimes, doesn't happen the other times. But when it happens, it is very annoying. The next time it happens, I will try these steps you have mentioned and tell you the results.

**Comment by fallaciousreasoning** [comment]
Okay, that's quite interesting that it hangs searching from the NTP - that makes it sound like it's something going on with the Omnibox suggestions.

Does it happen:
1. With another search engine
2. If you turn off some of the other autocomplete suggestions at (brave://settings/appearance)

**Comment by meet-v** [comment]
Okay.... I think I am onto something. Recently, I have observed that **Search Hang Issue** on **Brave Browser** happens when **Evolution Mail** is also open in the background. I dunno, whether this was a one-off co-incidence, or something related.

Can we analyse this in detail technically? I think Evolution and Brave are cooking something up here.

**Comment by fallaciousreasoning** [comment]
Wow that's absolutely wild - it reproduces for me. You need to have an HTML email opened in `Evolution` (I used the one from https://www.phpclasses.org/browse/file/14672.html), you don't need to add an account.

Actually, having Evolution open even makes changing tabs way slower for me, but focusing/trying to type in the Search bar gave me a 30s hang.

**Comment by meet-v** [comment]
Ah! Finally it got reproduced. I am glad.

Let’s hope we find a solution to this too soon. Either on Brave or on Evolution.

Thanks for the patience though!

**Comment by fallaciousreasoning** [comment]
Huh, its not reproducing for me today doing exactly what I did yesterday. This is driving me mad 😆

**Comment by meet-v** [comment]
🤦‍♂️

Try with a new email. I think the mail you previously tried with may be downloaded offline now on evolution and so it may not be interrupting the browser… just firing in the blind here.

**Comment by RobbyCBennett** [comment]
I encountered this on Windows 11 today with the latest Brave release (Version 1.78.97). Here are some other problems I had at the same time
- Windows clipboard (Windows + V) wasn't working 
- Windows wouldn't shut down until I forced it with the power button
Once I forced a restart, all of the problems were fixed. I guess something in the OS was the source of the problem.

**Comment by bsclifton** [comment]
I guess one thing I would ask @meet-v @fallaciousreasoning is:
Can we reproduce the issue if you close Evolution email?

**Comment by meet-v** [comment]
If I don't open Evolution or if I close it, then the issue doesn't reappear, at least in my trials.
However, even with latest evolution version and latest brave version, this issue is still there and nothing has solved it yet.

I had switched to a different OS altogether because these issues were causing daily pain for me, for the lack of a better email client and a better browser on linux, but now I am back and encountered it again today -- the same issue even after 3 months of posting this.

We have even identified the exact reason for the "hang" or crash, which ideally was the work of the developers. We have narrowed it down to evolution vs brave. And still the issue is not resolved after all these months.

I am disappointed.

**Comment by fallaciousreasoning** [comment]
Hey @meet-v I still haven't manage to reproduce this other than the one time - changing tabs is fine, so is focusing the search bar.

Would you mind monitoring the CPU usage of Evolution and Brave while using them to see if one or the other of them spikes? Without an easy (and consistent) way to reproduce its hard for us to track down exactly what's wrong.

Some other things you could try:
- try running Brave or Evolution from inside a flatpak/snap and see if that stops them from interacting
- is this the same ZorinOS install you had before? Does it happen in a VM too? If not, maybe reinstalling could stop the conflict?
- Did it happen on the other OS you were using? Or just Zorin?

**Comment by meet-v** [comment]
The issue is when we type something in the search bar at the top of the window, irrespective of the search engine we are using. And this happens when Evolution is open in the background.

This happens on Zonrin OS. Do not have any other OS to test this scenario with.
The other OS I was using was Windows, not using Evolution there.

That's all the information I can help you with.
I believe someone else too had a similar issue, and they concurred on this thread about facing it.
And also, a google search yields similar complaints raised by many, though not with respect to evolution. Probably they haven't reached to that conclusion yet.

**Comment by amirrh6** [comment]
This issue affects me, too! I'm running the latest stable version (1.80.124) on Ubuntu 24.04, and it happens randomly when I click on address bar after opening a new tab.
The browser freezes for a few seconds, Ubuntu asks if I want to kill it or wait, It crashes after a few seconds even though I click on wait.

Once I restart the brave and try restoring the tabs, it could happen again for a few times.

Brave Version: 1.80.124 Chromium: 138.0.7204.168
Operating System: Linux 6.14.0-24-generic

Note that I don't have Evolution installed on my system.

Here are the submitted crash reports which are related to this issue (as far as I remember), from the newest to the oldest:

**This list is regularly updated**

* b6ee0a00-17e4-520e-0000-000000000000 (Tuesday, August 19, 2025 at 10:14:28 AM | v1.81.135)
* 9e300500-17e4-520e-0000-000000000000 (Saturday, August 16, 2025 at 9:26:19 AM)
* 69e80600-63a7-490e-0000-000000000000 (Sunday, August 10, 2025 at 10:08:34 AM)
* c6ec0600-63a7-490e-0000-000000000000
* c2ec0600-63a7-490e-0000-000000000000
* ca2d0100-63a7-490e-0000-000000000000
* cbec0600-63a7-490e-0000-000000000000
* 63640600-bf2d-370e-0000-000000000000
* d15b0600-bf2d-370e-0000-000000000000
* 51640600-bf2d-370e-0000-000000000000
* 58640600-bf2d-370e-0000-000000000000
* 9a231600-27f1-2d0e-0000-000000000000
* 2ef31300-27f1-2d0e-0000-000000000000
* f8f81100-27f1-2d0e-0000-000000000000
* efee1100-27f1-2d0e-0000-000000000000
* 4dd51100-27f1-2d0e-0000-000000000000
* ceee1100-27f1-2d0e-0000-000000000000
* 93cf1100-27f1-2d0e-0000-000000000000
* b7342900-4dc1-240e-0000-000000000000
* 9b7c2300-4dc1-240e-0000-000000000000
* b9ee1100-27f1-2d0e-0000-000000000000
* f6f81100-27f1-2d0e-0000-000000000000
* d2ee1100-27f1-2d0e-0000-000000000000
* b4ee1100-27f1-2d0e-0000-000000000000
* 9c7f1d00-fb81-1b0e-0000-000000000000
* 69822d00-6d45-120e-0000-000000000000 (Wednesday, July 2, 2025 at 10:11:18 AM)

**Comment by meet-v** [comment]
There is no solution to this. The brave team is not able to replicate and hence have not provided any solution to this. So, either change the browser or change the email client, as per your needs. I have changed the client.

**Comment by amirrh6** [comment]
The only email client I have installed is Thunderbird, which is not configured at all and I don't use it.
I'm not sure if any other apps on the system interferes with Brave.

I've been loyal to Brave since ~ 2 years ago, and I really don't want to abandon it. Hope we get a response from the team.

> There is no solution to this. The brave team is not able to replicate and hence have not provided any solution to this. So, either change the browser or change the email client, as per your needs. I have changed the client.
> […](#)

**Comment by fallaciousreasoning** [comment]
@amirrh6 just had a quick look at those Stacktraces - unfortunately there doesn't seem to be much detail about what's caused them - the Stacktrace just has a single line 😢 

[d15b0600-bf2d-370e-0000-000000000000](https://brave.sp.backtrace.io/p/brave/triage?time=(relative-first-seen%2Cfloating%2Cyear)&filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMmQxNWIwNjAwLWJmMmQtMzcwZS0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCU1RA%3D%3D&aggregations=((uname.sysname%2Cdistribution%2C3)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(guid%2Cunique)%2C(classifiers%2Chead))&stats=(channel%2Cexception_info%2Cabort_message)&fingerprint=891e6b513c720763c34b1e70a5756966358b02141042d1d73be4bd984e5f753c)

```
bool url::DoIDNHost<(url::CanonMode)0>
```


This [9a231600-27f1-2d0e-0000-000000000000
](https://brave.sp.backtrace.io/p/brave/triage?time=(relative-first-seen%2Cfloating%2Cyear)&filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjlhMjMxNjAwLTI3ZjEtMmQwZS0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCU1RA%3D%3D&aggregations=((uname.sysname%2Cdistribution%2C3)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(guid%2Cunique)%2C(classifiers%2Chead))&stats=(channel%2Cexception_info%2Cabort_message)&fingerprint=7186114eaecf8dbd5a89788100daa86312bd3be665f68042b027ada3b41d30c4&similarity=false) looks slightly more helpful, as it looks related to the URL bar:

```
[ 0 ] crashpad::ExceptionHandlerClient::SignalCrashDump(crashpad::ExceptionHandlerProtocol::ClientInformation const&, unsigned long) ( linux_syscall_support.h:4258 )
[ 1 ] crashpad::ExceptionHandlerClient::RequestCrashDump(crashpad::ExceptionHandlerProtocol::ClientInformation const&) ( exception_handler_client.cc:94 )
[ 2 ] crashpad::(anonymous namespace)::RequestCrashDumpHandler::HandleCrashImpl() ( crashpad_client_linux.cc:413 )
[ 3 ] crashpad::(anonymous namespace)::SignalHandler::HandleCrash(int, siginfo_t*, void*) ( crashpad_client_linux.cc:175 )
[ 4 ] crashpad::(anonymous namespace)::SignalHandler::HandleOrReraiseSignal(int, siginfo_t*, void*) ( crashpad_client_linux.cc:219 )
[ 5 ] 0x78072da45330 ( libc.so.6 )
[ 6 ] TemplateURL::active_data() ( template_url.cc:2203 )
```

The [2ef31300-27f1-2d0e-0000-000000000000
](https://brave.sp.backtrace.io/p/brave/triage?time=(relative-first-seen%2Cfloating%2Cyear)&filters=JTVCJTVCJTIyX3J4aWQlMjIlMkMlMjJlcXVhbCUyMiUyQyUyMjJlZjMxMzAwLTI3ZjEtMmQwZS0wMDAwLTAwMDAwMDAwMDAwMCUyMiU1RCU1RA%3D%3D&aggregations=((uname.sysname%2Cdistribution%2C3)%2C(ver%2Cmax)%2C(ver%2Cmin)%2C(guid%2Cunique)%2C(classifiers%2Chead))&stats=(channel%2Cexception_info%2Cabort_message)&fingerprint=9fa634a359b17e58fbd256119479d04028a11f30f73b11364dc53fd9545ee762&similarity=false) one looks like it was an OOM in the text shaping code 😨 

```
[ 00 ] partition_alloc::internal::OnNoMemoryInternal(unsigned long)::$_0::operator()() const ( oom.cc:85 )
[ 01 ] partition_alloc::internal::OnNoMemoryInternal(unsigned long) ( oom.cc:85 )
[ 02 ] partition_alloc::TerminateBecauseOutOfMemory(unsigned long) ( oom.cc:92 )
[ 03 ] partition_alloc::internal::OnNoMemory(unsigned long) ( oom.cc:102 )
[ 04 ] partition_alloc::internal::SetSystemPagesAccessInternal(unsigned long, unsigned long, partition_alloc::PageAccessibilityConfiguration) ( page_allocator_internals_posix.h:162 )
[ 05 ] partition_alloc::internal::PartitionBucket::SlowPathAlloc(partition_alloc::PartitionRoot*, partition_alloc::internal::AllocFlags, unsigned long, unsigned long, partition_alloc::internal::SlotSpanMetadata<(partition_alloc::internal::MetadataKind)1>**, bool*) ( page_allocator.cc:287 )
[ 06 ] allocator_shim::internal::PartitionAllocFunctionsInternal<(partition_alloc::internal::AllocFlags)16, (partition_alloc::internal::FreeFlags)2>::Malloc(unsigned long, void*) ( partition_root.h:1306 )
[ 07 ] base::allocator::dispatcher::internal::DispatcherImpl<base::PoissonAllocationSampler>::AllocFn(unsigned long, void*) ( dispatcher_internal.h:130 )
[ 08 ] malloc ( shim_alloc_functions.h:154 )
[ 09 ] v8::internal::UnifiedHeapMarkingVisitorBase::Visit(v8::TracedReferenceBase const&) ( worklist.h:0 )
[ 10 ] cppgc::internal::BasicMarkingState::ProcessEphemeron(void const*, void const*, cppgc::TraceDescriptor, cppgc::Visitor&) ( marking-state.h:331 )
[ 11 ] cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(v8::base::TimeDelta, unsigned long) ( marker.cc:736 )
[ 12 ] v8::internal::CppHeap::AdvanceMarking(v8::base::TimeDelta, unsigned long) ( cpp-heap.cc:868 )
[ 13 ] v8::internal::MarkCompactCollector::PerformWrapperTracing() ( mark-compact.cc:2191 )
[ 14 ] v8::internal::MarkCompactCollector::MarkTransitiveClosureUntilFixpoint() ( mark-compact.cc:2070 )
[ 15 ] v8::internal::MarkCompactCollector::CollectGarbage() ( mark-compact.cc:2352 )
[ 16 ] v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_0::operator()() const ( heap.cc:2685 )
[ 17 ] void heap::base::Stack::SetMarkerAndCallbackImpl<v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)::$_0>(heap::base::Stack*, void*, void const*) ( stack.h:185 )
[ 18 ] PushAllRegistersAndIterateStack ( brave )
[ 19 ] v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) ( stack.h:81 )
[ 20 ] cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint(cppgc::internal::NormalPageSpace&, unsigned long, std::align_val_t, unsigned short, void**) ( object-allocator.cc:193 )
[ 21 ] WTF::VectorBuffer<blink::HarfBuzzRunGlyphData, 0u, blink::HeapAllocator>::VectorBuffer(unsigned int) ( object-allocator.h:183 )
[ 22 ] blink::ShapeResultRun::ShapeResultRun(blink::SimpleFontData const*, hb_direction_t, blink::CanvasRotationInVertical, hb_script_t, unsigned int, unsigned int, unsigned int) ( vector.h:1728 )
[ 23 ] blink::ShapeResultRun* cppgc::MakeGarbageCollectedTrait<blink::ShapeResultRun>::Call<blink::SimpleFontData*, hb_direction_t, blink::CanvasRotationInVertical const&, hb_script_t const&, unsigned int const&, unsigned int, unsigned int>(cppgc::AllocationHandle&, blink::SimpleFontData*&&, hb_direction_t&&, blink::CanvasRotationInVertical const&, hb_script_t const&, unsigned int const&, unsigned int&&, unsigned int&&) ( allocation.h:240 )
[ 24 ] blink::ShapeResultRun::MergeIfPossible(blink::ShapeResultRun const&) const ( allocation.h:278 )
[ 25 ] blink::ShapeResult::CopyRangeInternal(unsigned int, unsigned int, unsigned int, blink::ShapeResult*) const ( shape_result.cc:1750 )
[ 26 ] blink::InlineNode::ShapeText(blink::InlineItemsData*, WTF::String const*, blink::HeapVector<cppgc::internal::BasicMember<blink::InlineItem, cppgc::internal::StrongMemberTag, cppgc::internal::DijkstraWriteBarrierPolicy, cppgc::internal::DisabledCheckingPolicy, cppgc::internal::CompressedPointer>, 0u> const*, blink::Font const*) const ( inline_node.cc:216 )
[ 27 ] blink::InlineNode::ShapeTextIncludingFirstLine(blink::InlineNodeData*, WTF::String const*, blink::HeapVector<cppgc::internal::BasicMember<blink::InlineItem, cppgc::internal::StrongMemberTag, cppgc::internal::DijkstraWriteBarrierPolicy, cppgc::internal::DisabledCheckingPolicy, cppgc::internal::CompressedPointer>, 0u> const*) const ( inline_node.cc:1672 )
[ 28 ] blink::InlineNode::SetTextWithOffset(blink::LayoutText*, WTF::String, blink::TextDiffRange const&) ( inline_node.cc:987 )
[ 29 ] blink::LayoutText::SetTextWithOffset(WTF::String, blink::TextDiffRange const&) ( layout_text.cc:841 )
[ 30 ] blink::Text::UpdateTextLayoutObject(blink::TextDiffRange const&) ( text.cc:496 )
[ 31 ] blink::CharacterData::SetDataAndUpdate(WTF::String const&, blink::TextDiffRange const&, blink::CharacterData::UpdateSource) ( character_data.cc:203 )
[ 32 ] blink::CharacterData::ParserAppendData(WTF::String const&) ( character_data.cc:81 )
[ 33 ] blink::HTMLConstructionSite::ExecuteQueuedTasks() ( html_construction_site.cc:255 )
[ 34 ] blink::HTMLTreeBuilder::ConstructTree(blink::AtomicHTMLToken*) ( html_construction_site.h:134 )
[ 35 ] blink::HTMLDocumentParser::PumpTokenizer() ( html_document_parser.cc:936 )
[ 36 ] blink::HTMLDocumentParser::PumpTokenizerIfPossible() ( html_document_parser.cc:640 )
[ 37 ] blink::HTMLDocumentParser::DeferredPumpTokenizerIfPossible(bool, base::TimeTicks) ( html_document_parser.cc:620 )
[ 38 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ( callback.h:156 )
[ 39 ] base::MessagePumpDefault::Run(base::MessagePump::Delegate*) ( message_pump_default.cc:42 )
[ 40 ] base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:629 )
[ 41 ] non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ( thread_controller_with_message_pump_impl.cc:0 )
[ 42 ] base::RunLoop::Run(base::Location const&) ( run_loop.cc:134 )
[ 43 ] content::RendererMain(content::MainFunctionParams) ( renderer_main.cc:356 )
[ 44 ] content::ContentMainRunnerImpl::Run() ( content_main_runner_impl.cc:699 )
[ 45 ] content::ContentMain(content::ContentMainParams) ( content_main.cc:374 )
[ 46 ] ChromeMain ( chrome_main.cc:222 )
[ 47 ] 0x70602222a1ca ( libc.so.6 )
[ 48 ] 0x70602222a28b ( libc.so.6 )
[ 49 ] _start ( brave )
[ 50 ] 0x7ffcc23fe518
```

cc @simonhong in case you have any insights - I'm kind of stumped

**Comment by amirrh6** [comment]
@fallaciousreasoning Thank you for taking a look at the crash logs. Let me know if I can do anything to help to narrow down the issue.
I'll try to keep the [crash logs list](https://github.com/brave/brave-browser/issues/44903#issuecomment-3121549830) updated, regularly,

**Comment by AW1534** [comment]
I'm having this issue, but it just completely crashes.
