### ISSUE TITLE
Font in tab bar and bookmarks too large

### ISSUE THREAD

**Issue by pietro-coretto** [brave/brave-browser#45173]
### Description

After the last update Brave now shows very large font size in tab bars and bookmarks. This has nothing to do with font in webpages which behaves normaly 

### Steps to reproduce

whenever I open Brave under any conditions 

### Actual result

![Image](https://github.com/user-attachments/assets/eccc0993-703a-4cbc-85c2-e07f8b8381a7)

### Expected result

interface fonts should be comparable to the os settings 

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave	1.77.95 Chromium: 135.0.7049.52 (Official Build) (64-bit) 

Revision	9e0bf4d8fff1d4549561cf6f59c2a200a0fb516f

OS	Linux Ubuntu 34.04 LTS

JavaScript	V8 13.5.212.10

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [x] in the latest version of Chrome

**Comment by pietro-coretto** [comment]
I found that the problem is resolved when I launch the browser from the terminal using 

```
brave-browser --force-device-scale-factor=1
```

**Comment by hazecodeio** [comment]
I have the same issue after I upgraded to the version you're on. I'm on Ubuntu 24.04 as well.
There are more issues than font size. I'm missing the **Profile-Picker** button from the bar 🤕

**Comment by pietro-coretto** [comment]
I also miss the profile-picker, but that's for another issue I think.

**Comment by Shivansh-Mittal** [comment]
Since morning, being bothered by this issue. Unable to comfortably use brave browser, switched back to chrome for time being.

**Comment by Shivansh-Mittal** [comment]
> I found that the problem is resolved when I launch the browser from the terminal using
> 
> ```
> brave-browser --force-device-scale-factor=1
> ```

this isn't working on my end.

![Image](https://github.com/user-attachments/assets/c3651b72-9450-40ee-bcda-9d301098ca4e)

**Comment by hazecodeio** [comment]
I downgraded to the previous release **1.76.82** and put it on hold till the fix is released
If interested:

```
sudo apt-cache policy brave-browser
sudo apt install brave-browser=1.76.82
sudo apt-mark hold brave-browser

```

**Comment by hazecodeio** [comment]
> > I found that the problem is resolved when I launch the browser from the terminal using
> > ```
> > brave-browser --force-device-scale-factor=1
> > ```
> 
> [@pietro-coretto](https://github.com/pietro-coretto) this isn't working on my end.
> 
> ![Image](https://github.com/user-attachments/assets/c3651b72-9450-40ee-bcda-9d301098ca4e)

You don't seem to have **brave-browser** on the path

**Comment by fullyDeepak** [comment]
I can confirm this on Fedora 41.
So I downgraded to the last working version 1.76.82-1 and freeze the update until they patch.

```bash
sudo dnf install brave-browser-1.76.82-1
sudo dnf versionlock add brave-browser
```

**Comment by Lowyx** [comment]
I can confirm the same bug on Pop!_OS 22.04 (LTS) with the same Brave and Chromium versions as OP.
And the proposed fix by OP (`brave-browser --force-device-scale-factor=1`) unfortunately doesn't fix the issue on my end.

**Comment by Shivansh-Mittal** [comment]
> > > I found that the problem is resolved when I launch the browser from the terminal using
> > > ```
> > > brave-browser --force-device-scale-factor=1
> > > ```
> > 
> > 
> > [@pietro-coretto](https://github.com/pietro-coretto) this isn't working on my end.
> > ![Image](https://github.com/user-attachments/assets/c3651b72-9450-40ee-bcda-9d301098ca4e)
> 
> You don't seem to have **brave-browser** on the path

After some minutes, I realized this and added it to my path in linux bashrc. 
But i just refreshed the snaps and problem is no longer existing.

**Comment by gato-rosa** [comment]
I have a similar issue: sometimes when I open Brave, the Brave UI uses the system font (Adwaita Sans on Fedora 42), and sometimes it uses a different smaller font.
