### ISSUE TITLE
Add a way to disable Tor via admin policy

### ISSUE THREAD

**Issue by bbondy** [brave/brave-browser#454]
## Test plan
1. Fresh install of Brave (clean profile)
2. Open `regedit`
3. For 64 bit, create the following keys:
`BraveSoftware\Brave`
under the existing key: 
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Policies\`
(for 32 bit, you can edit `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\`)
4. Create a DWORD value at this path called `TorDisabled` and set the value as 1
5. Launch Brave
6. Verify `Managed by your organization` shows as the last item under the hamburger menu
7. If you click `Managed by your organization`, it should take you to brave://management
8. Verify no Tor options are shown in the UI
9. Exit Brave
10. Open the profile directory (`%USERPROFILE%\AppData\Local\BraveSoftware\Brave-Browser\User Data`)and look for the Tor executable (usually under a path like `cpoalefficncklhjfpglfiplenlpccdb\1.0.6`). It should NOT be there.

## Original issue description
https://twitter.com/dlepi/status/1012732537196765189

Via a method like these work:
https://www.chromium.org/administrators/policy-list-3

**Comment by billrob** [comment]
I had to have my team uninstall this browser from our company's computers because of TOR.

**Comment by bbondy** [comment]
Thanks for letting us know @billrob. Note that it won't run without opt-in, but I know we need a way to completely disable it from even being installed, this will cover it.

**Comment by billrob** [comment]
@bbondy Security folks are at it again at my employer.  Since it has the option to private browse with TOR, they won't have any of it.  Boo.

**Comment by Jacalz** [comment]
I have this issue too, our School doesn't allow the use of VPN, proxys or Tor on our computers. Since it is opt in we can still use the browser if we want, but tthe use of Tor would be conflicting with their policy. Being able to completely remove it would be a great thing!

**Comment by notoriousturtle** [comment]
@BrendanEich 

You’re losing users because your team is failing to provide an option to disable Tor. Tor is a serious security concern.

**Comment by bsclifton** [comment]
@notoriousturtle starting Monday, @simonhong will be looking at a group policy to completely disable Tor. Please stay tuned

**Comment by simonhong** [comment]
@darkdh Can we turn on/off tor feature at runtime?
If not, I think we need that switch to control tor by admin policy.

**Comment by notoriousturtle** [comment]
Awesome, appreciated! @bsclifton @simonhong

**Comment by darkdh** [comment]
@simonhong we can't do that at runtime. You can grep `ENABLE_TOR` build flag and you can see why

**Comment by bsclifton** [comment]
Quick heads up for folks following this: we've got it solved 😄 (thanks @simonhong and reviewers that helped)

**Comment by btlechowski** [comment]
It seems that this PR is Windows only. Adding `OS/Windows` flag.

**Comment by tomlowenthal** [comment]
There's a selection of macOS fleet-management software which uses Group Policy. But I admit that it'd be hard to test that here.

**Comment by notoriousturtle** [comment]
@tomlowenthal are you talking about something like Jamf? The device management software should not be relevant. How can this be configured on the macOS version?

**Comment by tomlowenthal** [comment]
@notoriousturtle Yes, that sort of thing. The management software is unfortunately relevant because as far as I know macOS doesn't have a uniform way to expose config info to applications like Windows does.

**Comment by notoriousturtle** [comment]
@tomlowenthal jamf has to do it somehow right? How can a normal enduser disable the Tor feature?

**Comment by tomlowenthal** [comment]
There's a separate settings switch for that which we just implemented in brave/brave-core#4046 .

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.3.101 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 10 OS Version 1909

Brave | 1.3.101 Chromium: 79.0.3945.130 (Official Build) beta (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified the test plan from the description.

Verified `Managed by your organization` is shown in the hamburger menu

![image](https://user-images.githubusercontent.com/34715963/73150192-6080a500-40c5-11ea-99b3-312856749a11.png)

Verified that `Managed by your organization`, opens `brave://management`
`brave://management` is empty. Logged https://github.com/brave/brave-browser/issues/7920

Verified that Tor links are not shown in hamburger menu.
Verified that `Alt+Shift+n` does not open Tor Window
A reference to Tor can be seen in Private Window. Logged https://github.com/brave/brave-browser/issues/7921


Verified that tor component is not present in User profile

Verified Tor component is not listed in `brave://components/`

**Comment by Haimu-ad** [comment]
I am not able to create the key as it's saying '\' not allowed in naming key. So, what should I do?

**Comment by simonhong** [comment]
Hi @Haimu-ad , still can't set tor group policy?
I can set with below step.
1. Open Registry Editor(regedit)
2. Create `BraveSoftware/Brave` key under `HKEY_LOCAL_MACHINE\SOFTWARE\Policies`
3. Create DWORD value named `TorDisabled` with value 1
4. Launch Brave and check Tor feature is disabled

![image](https://user-images.githubusercontent.com/6786187/109442554-e36bf000-7a7b-11eb-8158-f109fa96c336.png)

Hope this helps!

**Comment by hartaranus** [comment]
This is Working Even without fresh install. We could disable and enable tor at anytime for our existing brave browser
