### ISSUE TITLE
Vertical tabs broken on Linux

### ISSUE THREAD

**Issue by ParadaCarleton** [brave/brave-browser#50162]
### Description

Enabling vertical tabs on Linux causes graphical glitches on Linux. Namely, it ignores the border-rounding value, which is supposed to be set by GTK and applies to all apps across the whole operating system. In addition, selecting vertical tabs results in misaligned window icons (the icons are placed too high).

### Steps to reproduce

1. Enable vertical tabs, 
2. Under "Theme", choose "Use GTK".

### Actual result

<img width="1531" height="255" alt="Image" src="https://github.com/user-attachments/assets/6fc465a9-aee5-495f-802b-07df0b24201d" />

### Expected result

For comparison, here are the correctly-aligned icons when using the "classic" theme.
<img width="293" height="67" alt="Image" src="https://github.com/user-attachments/assets/de046049-d5ef-4371-b845-1590d9cfadb2" />

In addition, here's the correctly-working window decorations when using the traditional (horizontal) tab layout, which applies the correct radius for window rounding.
<img width="1512" height="113" alt="Image" src="https://github.com/user-attachments/assets/0dc2a1f1-b47f-4d53-99fb-87cc309105b2" />

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

1.83.112 Chromium: 141.0.7390.70 (Official Build) (64-bit)
01304d7b02857a2809dac4956d35f20f3884da2c
Linux

### Channel information

- [ ] release (stable)
- [x] beta
- [x] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ParadaCarleton** [comment]
Actually, I just checked and it seems to be a lot more broken on the classic theme @simonhong :
<img width="1424" height="88" alt="Image" src="https://github.com/user-attachments/assets/1dc0f2c5-cb99-46d3-b3fc-930afd535ac3" />

**Comment by KristijanZic** [comment]
I'm experiencing the same, if not even worse issues on the latest Ubuntu.

Just for reference this is how a proper GTK window should look like (pay attention to headerbar and how all 4 corners of the window are rounded, also pay attention to close, min, max buttons):

<img width="1508" height="1045" alt="Image" src="https://github.com/user-attachments/assets/3ed42ee6-9cb3-4bf2-be3a-680b557be285" />

Now here is how Brave (both Stable and Nightly) look like. Pay attention to the bottom corners not being rounded, top corners not being rounded enough, and another window appearing behind the browser window, an empty titlebar at the top of the window, completely different close-min-max buttons...

<img width="1629" height="1051" alt="Image" src="https://github.com/user-attachments/assets/38dce850-b0a9-485d-bc33-3cbc4d1a6c85" />

<img width="1629" height="1051" alt="Image" src="https://github.com/user-attachments/assets/0d4cd615-9637-42aa-b4ef-7340cfef6d11" />

<img width="1629" height="1051" alt="Image" src="https://github.com/user-attachments/assets/37d9a2fd-8610-4761-b770-630e1f3577c5" />

**Comment by simonhong** [comment]
This issue is fixed by https://github.com/brave/brave-core/pull/35959.

Latest nightly with Gtk theme.

<img width="1023" height="726" alt="Image" src="https://github.com/user-attachments/assets/8497b673-a4a9-4a4e-b180-b891b1184d17" />

**Comment by btlechowski** [comment]
Verified with

Brave | 1.92.119 Chromium: 149.0.7827.103 (Official Build) beta (64-bit)
-- | --
Revision | 9d2298d5e445ba443c8a9a982151c53341e302aa
OS | Linux


#### Gtk

Verified Min/Max/Close controls are shown correctly
Verified Min/Max/Close controls work as expected

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/99346385-88c5-460e-8b28-d2cbb11fac5c" />

Verified corners are rounded

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/b17d2e84-e38a-46f8-81d2-f4a09e7086cf" />

Titlebar looks good

<img width="1854" height="1168" alt="Image" src="https://github.com/user-attachments/assets/c45054d2-8db1-4d66-a775-275a5f8d7426" />

**Comment by ParadaCarleton** [comment]
Thank you so much for your work on this @simonhong ! :)

One minor issue—the icon is misaligned/off-center, at least when using the GTK theme:
<img width="274" height="37" alt="Image" src="https://github.com/user-attachments/assets/5a736ecf-1699-47b7-aa40-21dd61c03232" />

Compare firefox:
<img width="194" height="43" alt="Image" src="https://github.com/user-attachments/assets/ea351df1-bbb3-48a7-b952-dff0e8738ef8" />

**Comment by jiesou** [comment]
> This issue is fixed by [brave/brave-core#35959](https://github.com/brave/brave-core/pull/35959).
> 
> Latest nightly with Gtk theme.
> 
> <img alt="Image" width="1023" height="726" src="https://private-user-images.githubusercontent.com/6786187/590228273-8497b673-a4a9-4a4e-b180-b891b1184d17.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMzMjE4NzEsIm5iZiI6MTc4MzMyMTU3MSwicGF0aCI6Ii82Nzg2MTg3LzU5MDIyODI3My04NDk3YjY3My1hNGE5LTRhNGUtYjE4MC1iODkxYjExODRkMTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA3MDZUMDcwNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNlZDY3MmMyYmQwNTFlMzEyZjlmM2I5YmYwNzQ0NDc5ZWVmNGE1OWYwNmJiOTg1OTRmZTcxNTQ1Njc0ODkzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.uxfzQJK1rbjQkdZ9xbhOAdgRx9AyFr3swwLmzKNiJ5U">

Thank you so much for your work on this
But bottom corners still not being rounded
