### ISSUE TITLE
No space added after text replacement on Mac OS

### ISSUE THREAD

**Issue by khatiskatsi** [brave/brave-browser#50257]
### Description

In any other app after text replacement has been inserted there is always space added for next word to write. But not in Brave on some websites. Brave does not add the space after text replacement is inserted.
For example writing here, on github, all works fine, but in messenger or instagram it is not. Some other websites function fine, on some same problem.

### Steps to reproduce

1. text replacement on
2. writing a word that should be automatically replaced
3. space after replaced word is not added

### Actual result

No space is added after replaced word.

### Expected result

space must be added after replaced word.

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

v1.83.118

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [ ] with Brave Shields disabled
- [ ] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by ichthyos** [comment]
FYI this has been fixed upstream in Chromium: https://issues.chromium.org/issues/458488135#comment23

**Comment by khatiskatsi** [comment]
> FYI this has been fixed upstream in Chromium: https://issues.chromium.org/issues/458488135#comment23

Thanks! This is great! But how do I fix it in the Brave? Will this fix be added in the next update?

**Comment by ichthyos** [comment]
The most recent release (version 1.84.141 with changelog in #50915) should include the fix, which was merged in #50891.

**Comment by khatiskatsi** [comment]
> The most recent release (version 1.84.141 with changelog in [#50915](https://github.com/brave/brave-browser/pull/50915)) should include the fix, which was merged in [#50891](https://github.com/brave/brave-browser/issues/50891).

yes, that's the version it got updated now, but still the same thing. after text is replaced, no space is added. In any other app it works just fine, but not in Brave. I really don't want to change the browser because of that. But it is very annoying.

**Comment by khatiskatsi** [comment]
> The most recent release (version 1.84.141 with changelog in [#50915](https://github.com/brave/brave-browser/pull/50915)) should include the fix, which was merged in [#50891](https://github.com/brave/brave-browser/issues/50891).

it is still not working. it did not fix it. on certain websites it is fine, on some no space is added.
