### ISSUE TITLE
[Brave Desktop] Users logged out of Google/multiple sites with cookie/localStorage deletion (Chromium 141)

### ISSUE THREAD

**Issue by CaseyLabs** [brave/brave-browser#50411]
## Summary

Users across all desktop platforms (Windows, macOS, and Linux) are being automatically logged out of Google services (and sometimes multiple sites). When this occurs, cookies and localStorage entries are fully deleted.

Brave version: `1.83.118`
Release channel: `stable`

Attn: @bsclifton @goodov 

## History

- Previous discussion: #49300 
- Findings: Cookies and local storage for affected domains were entirely deleted.
- Users would experience being logged out of Google and/or other domains after 2 hours.
- Histogram reporting the data loss: `Signin.BoundSessionCredentials.SessionTerminationTrigger`
- Example:

  ```
  Histogram: Signin.BoundSessionCredentials.SessionTerminationTrigger recorded 2 samples, mean = 1.0
  (flags = 0x41) [[#](chrome://histograms/#Signin.BoundSessionCredentials.SessionTerminationTrigger)]
  0  O                                                                         (0 = 0.0%)
  1  --O                                                                       (2 = 100.0%) {0.0%}
  2  
  ```

### Original Fix

- Fix PR:  https://github.com/brave/brave-variations/pull/1504
- Cause: Brave’s Bounce Tracking Mitigation (BTM, formerly DIPS) interacts incorrectly with third-party cookie partitioning. BTM’s periodic “preserve partitioned cookies” cleanup is misinterpreted by `BoundSessionCookieRefreshServiceImpl` as a first-party cookie deletion event, which prematurely terminates Google’s Device-Bound Session after roughly two hours.
- Fix: Introduced `BTMGoogleAuthWorkaround`, which disables the triggering action (`triggering_action: 'none'`) while keeping the DIPS feature active.
- Result: Users confirmed that the logout issue stopped once their installations received the `BTMGoogleAuthWorkaround` flag

## Current Status (2025-10-22)

- The logout issue has reappeared for some users since ~2025-10-10

- Users report recurring logouts from Google (and other domains) approximately every X hours in Brave 1.83.112 (Chromium 141.0.7390.70)

- Logged-out time may have increased from previously reported 2-hour time window for issue occurrence.

- The issue may have re-emerged following the merge of [PR #49977](https://github.com/brave/brave-variations/pull/1504)

- Possibly related: [Issue #46876](https://github.com/brave/brave-browser/issues/46876)

## Diagnostic Request

If you are a Brave user experiencing this issue, please provide the following diagnostic data:

1. Keep Brave open (minimized/running the background when not using) to ensure histograms are recorded.
2. After the logout occurs, open these URLs:
   - `brave://histograms/Signin.BoundSessionCredentials`
   - `brave://histograms/Net.DeviceBoundSessions`
   - `brave://histograms/Net.DeviceBoundSessions.DeletionReason`
3. Download the histogram data and attach the files as a comment to this issue.

**Comment by CaseyLabs** [comment]
A user histogram submitted on 2025-Oct-20 can be found on the original issue thread: https://github.com/brave/brave-browser/issues/49300#issuecomment-3422780971

**Comment by rafaellirio85** [comment]
Current histogram

[histograms (1).txt](https://github.com/user-attachments/files/23095599/histograms.1.txt)

**Comment by rafaellirio85** [comment]
Now it's logging me out every ten minutes or less
New histogram below

[histograms (2).txt](https://github.com/user-attachments/files/23097210/histograms.2.txt)

**Comment by bsclifton** [comment]
Possibly related https://github.com/brave/brave-browser/issues/50115

**Comment by rafaellirio85** [comment]
It seems like the version 1.83.120 fixed the issue. I'll keep tracking for a couple days to confirm.

Edit: Issue is back again.

**Comment by rafaellirio85** [comment]
Here's the most recent histogram.

[histograms (3).txt](https://github.com/user-attachments/files/23141834/histograms.3.txt)

**Comment by rafaellirio85** [comment]
Histogram from today after 40 minutes running brave

[histograms.txt](https://github.com/user-attachments/files/23186788/histograms.txt)

**Comment by Lythran** [comment]
I'm not sure if this will work for everyone, but I had the same issue where multiple sites (including github) would log me out even with "delete all cookies on exit" is turned off and "forget me when I close this site" is turned off. The way I solved it for me at least was:

1. Click on the site settings icon to the left of the url
2. Click "Cookies and Site data"
3. Click on "Manage on-device site data"
4. Click on "delete saved data for site"
5. Log in again

After I did this a couple of days ago, all my login credentials were saved and I didn't need to log in. I tried this with my other emails and affected profiles (such as proton mail) and it seemed like it worked. Though I understand that this will be a hassle to those who have multiple sites to log back into...
I believe in you, devs!

My os is Arch Linux running the 6.17.5-arch1-1 kernel
Brave Version: v1.83.120
Brave release channel: stable

https://github.com/user-attachments/assets/ac9bc945-56bf-448f-925b-c1a9c0df8605

**Comment by rafaellirio85** [comment]
Histogram after 1h running brave, first disconnection from Facebook.

[histograms.txt](https://github.com/user-attachments/files/23209745/histograms.txt)

**Comment by rafaellirio85** [comment]
First disconnection after a couple hours.

[histograms (1).txt](https://github.com/user-attachments/files/23303605/histograms.1.txt)

Brave 1.84.132
Chromium: 142.0.7444.60

**Comment by rafaellirio85** [comment]
Hi, @CaseyLabs. Any progress? It's becoming unbearable to use Brave under these circumstances.

New histogram below.

[histograms.txt](https://github.com/user-attachments/files/23329910/histograms.txt)

**Comment by goodov** [comment]
Sorry, folks, this is not that simple. Can you please test if logouts also happen in a new profile? I wonder if these are consequences of some kind of a migration that happened in the past that.

**Comment by rafaellirio85** [comment]
Do you mean a new Brave profile, @goodov?
What's weird is that I have the same Brave profile for a couple years so I'm not sure if that would be the case.

**Comment by goodov** [comment]
> Do you mean a new Brave profile, [@goodov](https://github.com/goodov)? What's weird is that I have the same Brave profile for a couple years so I'm not sure if that would be the case.

<img width="671" height="1016" alt="Image" src="https://github.com/user-attachments/assets/135c95d7-48bd-4337-aaad-c283994f0f95" />

**Comment by rafaellirio85** [comment]
I'll let it running all day today to see how it behaves.

**Comment by rafaellirio85** [comment]
I guess it's an issue with my profile. Nothing happened with the new one so far.
Well, I'll deal with it until it gets fixed because will be too much trouble setting up a new profile just as my current with no avail that won't keep happening.
Thanks, @goodov for the tip.

**Comment by goodov** [comment]
> I guess it's an issue with my profile. Nothing happened with the new one so far. Well, I'll deal with it until it gets fixed because will be too much trouble setting up a new profile just as my current with no avail that won't keep happening. Thanks, [@goodov](https://github.com/goodov) for the tip.

Maybe site data cleanup will be enough in you old profile:

<img width="755" height="753" alt="Image" src="https://github.com/user-attachments/assets/ed923f55-8dcc-47e6-b62f-b57ecb7a7546" />

**Comment by CaseyLabs** [comment]
Confirming that creating a new profile may have solved the issue: I've been running under a new profile for >48 hours now with no logouts, will continue to monitor.

Any ideas what happened in the old profile the caused the issue to reappear? (More curious than anything else.) Thanks!

**Comment by CaseyLabs** [comment]
I spoke too soon, issue just re-occurred again. Attached is my full histogram, but I wasn't able to capture any BoundSession related material.

[histograms.txt](https://github.com/user-attachments/files/23430001/histograms.txt)

**Comment by rafaellirio85** [comment]
Now brave just asked me if I wanted to save my facebook password even tho it was already saved. That's quite weird.
Attached histogram.

[histograms.txt](https://github.com/user-attachments/files/23454308/histograms.txt)

**Comment by rafaellirio85** [comment]
It's nearly impossible to use facebook at this moment. It'll boot me after 3 seconds.

[histograms (1).txt](https://github.com/user-attachments/files/23503897/histograms.1.txt)

I'm not gonna lie but this is quite frustrating. I've been using Brave for a long time and I like it but I depends on facebook to work.

**Comment by CaseyLabs** [comment]
Yeah, I just got hit twice by this issue this morning (logged out of Google within an hour). Not sure how to proceed here. cc: @bsclifton @goodov 

[histograms (2).txt](https://github.com/user-attachments/files/23506699/histograms.2.txt)

**Comment by goodov** [comment]
Doesn't look like this issue is session-bound related.

What OS do you use?

**Comment by CaseyLabs** [comment]
> What OS do you use?

OS: 
- CachyOS (Arch Linux based)
- Kernel: v6.17.7-5
- Desktop Environment: KDE Plasma v6.5.2
- QT version: v6.10.0

Browser:
- Brave 1.84.139 (Official Build) (64-bit)
- Chromium: 142.0.7444.163
- Arch: x64

Thanks @goodov!

**Comment by bill-mcgonigle** [comment]
I've been seeing this for a while on a standard Debian 12 amd64 install (my main desktop).  Currently on Brave 1.84.139.

A couple weeks ago this machine lost its sync chain, though other settings and history were still there.  I was able to re-add it from seed words from a phone.  The sync chain had been stable ever since I migrated it over to the v2 chain type (several years).

For whatever reason Google sites have not been giving me this problem.  Github, StackExchange, Reddit, Twitter, all get logged out within a few days. I have not seen logouts in minutes like others report.

Nothing remarkable in syslogs.  I scrubbed the machine's root zpool for good measure but no filesystem corruption was found.

Not sure if it's relevant but I have password, payment, address saving turned off.  The only experiment configured is `#enable-autofill-credit-card-upload` set to disabled.

On the console I see various normal site connect failures and complaints about no ipv6 stack, but the only things that look unusual are:
```
[38185:38185:1116/160055.574790:ERROR:CONSOLE:1] "Uncaught (in promise) ReferenceError: Mojo is not defined", source: chrome://resources/mojo/mojo/public/js/bindings.js (1)
[38185:38185:1116/162414.171642:ERROR:mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:732] Message 0 rejected by interface blink.mojom.WidgetHost
```

which seems to be IPC errors, but I have no idea if those are relevant.

**Comment by goodov** [comment]
If this is a Linux-only issue, then it might be related to secrets storages being used by browser. There's a histogram `OSCrypt.BackendUsage` (available only on Linux) which lists the backend that is currently in use. The values are:
```cpp
  kDefer = 0,
  kDeferFailed = 1,
  kBasicText = 2,
  kBasicTextFailed = 3,
  kGnomeLibsecret = 8,
  kGnomeLibsecretFailed = 9,
  kKwallet = 10,
  kKwalletFailed = 11,
  kKwallet5 = 12,
  kKwallet5Failed = 13,
  kKwallet6 = 14,
  kKwallet6Failed = 15,
```

To test if the secrets backend is the culprit I'd create a separate profile and launch browser with `--user-data-dir=/path/to/profile --password-store=basic`. This way we should exclude all possible kwallet/libsecret bugs. Please be aware that this will store your cookies and passwords technically unencrypted in this dir, so don't share it with anyone.

**Comment by rafaellirio85** [comment]
I'm using Windows 11.
Brave 1.84.139

**Comment by rafaellirio85** [comment]
It seems like the issue fixed by itself. It's running normally for the last ~48h.

**Comment by havit1** [comment]
Fedora Workstation 43
Brave 1.84.141 (Official Build) (64-bit) from Brave's dnf repository

Don't know if it helps somehow, but the issue does not seem to be consistent between profiles. I've just been logged out from everywhere in two of my profiles (i think Default and Profile 1), but logins in my third profile are alright. Cookies and history are NOT removed, I can see them all from settings.

Also I've seen some ideas that it's happening to specific websites, at least in my case, it happens to all logins (github, google, random e-shop site etc.). Again, don't know if it helps, but two logins in my third profile where I've NOT been logged out are MS Teams and Discord. 

P.S.
Shields are enabled in all 3 profiles.
Block Fingerprinting enabled in all 3 profiles. 
One profile has Aggressive Block for trackers, two others - default block
Forget me ... - is not enabled anywhere

Forgot to mention, for me it happens rather randomly. From last time when this happened till now - couple weeks, maybe a month. From second to last time till last time - definitely more than a month, maybe even more than couple months.

**Comment by vkrevs** [comment]
Just happened to me on openSUSE 15.6 with Brave 1.84.141 (Official Build) (64-bit)]/Chromium: 142.0.7444.176

**Comment by lllIIIlll** [comment]
This issue still happens to me, but only when I delete 'Browsing history' from the 'Advanced' tab in 'Delete browsing data'.

- Windows 11
- Brave 1.84.141 (Official Build) (64-bit)
- Chromium: 142.0.7444.176

**Comment by anon-ra** [comment]
Addendum: 

What somehow worked for me was installing the brave-bin from AUR (Manjaro/Arch Linux)
The problem does not appear to be present in this version, at least not for me.

**Comment by ourichermath** [comment]
Happened to me first thing this morning with YouTube.  Gmail was fine.  All the Histogram stuff you asked for looks blank to me and only the BoundSessionCredentials one will download (probably because the others are completely blank), but I'll attach it anyway.

<html>
<body>

Brave | 1.85.111 Chromium: 143.0.7499.40 (Official Build) (64-bit)
-- | --
Revision | 9c3716ba58ee849028317006445923e32f751bba
OS | Windows 11 Version 25H2 (Build 26200.7171)


</body>
</html>


[histogramsSessionCredentials.txt](https://github.com/user-attachments/files/23960300/histogramsSessionCredentials.txt)

**Comment by ourichermath** [comment]
And now, Gmail signed me out, but YouTube is still good.  Once again, only the BoundSessionCredentials histogram has anything in it and the other two are empty and won't download.

[histogramsSessionCredentials.txt](https://github.com/user-attachments/files/23964755/histogramsSessionCredentials.txt)

**Comment by bsclifton** [comment]
Thanks for reporting folks - I suspect this is coming back after we disabled an experiment with https://github.com/brave/brave-variations/pull/1569. We thought the fix from upstream was sufficient; it might not be the case.

I created a revert for that experiment and we can evaluate it now:
https://github.com/brave/brave-variations/pull/1577/files

Once this change is merged and goes live, you'll need to restart the browser. This would only affect folks who saw a regression this week. Stay tuned - I'll share more info.

**Comment by bsclifton** [comment]
OK folks - fix has been merged. It may take a few minutes to go into effect. 

If you were seeing this, please close and relaunch Brave. You can then check on brave://version/ and you should see `BTMGoogleAuthWorkaround:Enabled` under `Active Variations`.

Please confirm here if possible when you have the variation and if you are fixed.  Thanks to @goodov for creating https://github.com/brave/brave-browser/issues/51274 to understand why this could have caused breakage. 

Even with this fix, it seems we have a few folks with similar symptoms (losing the cookie for Google site), but I suspect it's a different root cause.

**Comment by ourichermath** [comment]
Both the wife and I have the reverted fix and we're still both logged into Gmail and YouTube (it's been roughly 4 hours).  So, I'd say the fix works.  If something changes, I'll let you know.  Thanks.

**Comment by rafaellirio85** [comment]
> Please confirm here if possible when you have the variation and if you are fixed.

Running the version 1.85.111 and I have the variation.
Brave logged me out from all my accounts, i.e. Reddit, Instagram, Facebook, Github etc, and I'm having to do the 2FA on all of them because it didn't recognize my device.

**Comment by bsclifton** [comment]
@rafaellirio85 you've definitely had a different issue... Maybe you can help provide some more info

If you visit `brave://settings/shields`, how do these settings look for you?
(this screenshot shows the default settings)
<img width="747" height="705" alt="Image" src="https://github.com/user-attachments/assets/05f7b2d9-b0df-48e6-a1e8-4247bc04f961" />

**Comment by rafaellirio85** [comment]
Here's mine, @bsclifton 

<img width="699" height="891" alt="Image" src="https://github.com/user-attachments/assets/841a509e-d0ae-4ed7-b66e-83567fb9a020" />

Only difference is the Trackers & ads blocking that I've set as agressive.

**Comment by Lythran** [comment]
> I'm not sure if this will work for everyone, but I had the same issue where multiple sites (including github) would log me out even with "delete all cookies on exit" is turned off and "forget me when I close this site" is turned off. The way I solved it for me at least was:
> 
> 1. Click on the site settings icon to the left of the url
> 2. Click "Cookies and Site data"
> 3. Click on "Manage on-device site data"
> 4. Click on "delete saved data for site"
> 5. Log in again
> 
> After I did this a couple of days ago, all my login credentials were saved and I didn't need to log in. I tried this with my other emails and affected profiles (such as proton mail) and it seemed like it worked. Though I understand that this will be a hassle to those who have multiple sites to log back into... I believe in you, devs!
> 
> My os is Arch Linux running the 6.17.5-arch1-1 kernel Brave Version: v1.83.120 Brave release channel: stable
> 
>  recording.mp4

I've had this issue yet again! Using the latest Brave version ```1.85.111 Chromium: 143.0.7499.40 (Official Build) (64-bit) ```
This is on a new installation on Fedora Linux with the "delete all cookies on exit" and "forget be when I close this site" are disabled. I'm unable to use:
```
brave://histograms/Signin.BoundSessionCredentials
brave://histograms/Net.DeviceBoundSessions
brave://histograms/Net.DeviceBoundSessions.DeletionReason
```
since every time it's in the background for a long time and even after the logout occurs, no data is shown. I'm only able to give the general histogram data if that's okay. I have also tried my own solution but it has failed me ;w;

[histograms.txt](https://github.com/user-attachments/files/24065888/histograms.txt)

It's the same sites that are affected. Gmail, Proton Mail, Github, etc. All gone!

**Comment by carb0hydrates** [comment]
Did anyone solve this issue.

any fix for this issue

**Comment by CaseyLabs** [comment]
I'm still encountering the logged-out issue on Brave Linux desktop. I did a full uninstall, removed all local files under `~/.config/BraveSoftware` and `/etc/brave`, and performed a fresh install. Same issue.

Interestingly, I don't see the `BTMGoogleAuthWorkaround:Enabled` under `Active Variations`:

```
Brave	1.85.116 Chromium: 143.0.7499.110 (Official Build) (64-bit) 
Revision	d9d2e023ad06c46a6ee40a14c4c5e639328b0e43
OS	Linux
JavaScript	V8 14.3.127.16
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
Command Line	/opt/brave-bin/brave --disable-domain-reliability --enable-dom-distiller --enable-distillability-service --origin-trial-public-key=bYUKPJoPnCxeNvu72j4EmPuK7tr1PAC7SHh8ld9Mw3E=,fMS4mpO6buLQ/QMd+zJmxzty/VQ6B1EUZqoCU04zoRU= --lso-url=https://no-thanks.invalid --variations-server-url=https://variations.brave.com/seed --variations-insecure-server-url=https://variations.brave.com/seed --flag-switches-begin --flag-switches-end --ozone-platform=wayland --component-updater=url-source=https://go-updater.brave.com/extensions --render-node-override=/dev/dri/renderD128
Executable Path	/opt/brave-bin/brave
Profile Path	/home/user/.config/BraveSoftware/Brave-Browser/Default
Variations Seed Type	Null
Command-line variations	eyJkaXNhYmxlLWZlYXR1cmVzIjoiRXllRHJvcHBlciIsImVuYWJsZS1mZWF0...
```

Attached is a histogram from a recent occurance. Thanks!

[histograms (3).txt](https://github.com/user-attachments/files/24280745/histograms.3.txt)

**Comment by CaseyLabs** [comment]
Anyone encounter this issue the last week? My Brave install has been stable for the last month, but I've been chronically logged out of of Google sites for the last 48 hours.

**Comment by pikawee** [comment]
I am currently on version 1.87.192 (Chromium: 145.0.7632.160) and have the same issue, facing logouts from Google sites and GitHub as well.

@bsclifton you might wanna check out https://github.com/brave/brave-browser/issues/53456#issuecomment-4020852886

**Comment by abue-ammar** [comment]
this a very annoying  issue.  Just  look how many times  i had to log in again  and  again. i just  want to stay logged in

![Image](https://github.com/user-attachments/assets/ba2f9ff3-89c1-4887-839d-740d3425c1ce)

**Comment by abue-ammar** [comment]
> Anyone encounter this issue the last week? My Brave install has been stable for the last month, but I've been chronically logged out of of Google sites for the last 48 hours.

yes facing this again  in android  latest nightly

**Comment by CaseyLabs** [comment]
Recent reports of similar logged-out issues (not operating system specific):

- Android (4 days ago): https://github.com/brave/brave-browser/issues/53453
- Windows (3 days ago): https://github.com/brave/brave-browser/issues/53456
- Windows (2 weeks ago): https://github.com/brave/brave-browser/issues/53108

Recent reports from Reddit:
- 1 hour ago: https://www.reddit.com/r/brave_browser/comments/1rqxzd1/how_do_ya_stay_logged_in/
- 3 days ago: https://www.reddit.com/r/brave_browser/comments/1rnybxk/brave_keeps_logging_me_out_of_google_even_after/
- 4 days ago: https://www.reddit.com/r/brave_browser/comments/1rn8te1/brave_logs_out_everything_everytime_i_reboot/
- 23 days ago: https://www.reddit.com/r/brave_browser/comments/1r5pt31/four_4_months_later_and_keep_loggin_out_from/
- 25 days ago: https://www.reddit.com/r/brave_browser/comments/1r4n34b/logged_out/

I encountered the issue again today on Linux. Histogram attached.

[histograms.txt](https://github.com/user-attachments/files/25914399/histograms.txt)

Attn: @bsclifton @goodov

**Comment by abue-ammar** [comment]
after i clean reinstalled brave it is fixed

**Comment by ranon-rat** [comment]
every password was deleted, and most sessions too, but for some reason the only sessions that I kept were the ones that I already had open when it closed. I am using fedora.



Brave 1.89.132 (Official Build) (64-bit)
Chromium: 147.0.7727.56

**Comment by abue-ammar** [comment]
> every password was deleted, and most sessions too, but for some reason the only sessions that I kept were the ones that I already had open when it closed. I am using fedora.
> 
> Brave 1.89.132 (Official Build) (64-bit) Chromium: 147.0.7727.56

if fixes when you clean reinstall brave. in android i was suffocating because it always logs me out. very annoying bug and it actually came from ungoogled chromium

**Comment by wrobelda** [comment]
This happened to me again today on Gnome and I think I know why.

I was working on a Gnome extension, for which I intended to run a nested Gnome session, using `dbus-run-session gnome-shell --devkit --wayland`. This actually fails for whatever reason, the result of which was my actual main Gnome session also misbehaving, likely due to some DBus conflicts. I logged out of my session, logged back in and was presented with Gnome error:

```
    Portal(
        PortalNotFound(
            OwnedInterfaceName(
                "org.freedesktop.portal.Secret",
            ),
        ),
    ),
```

, while Brave restored the session and opened all tabs in a logged-out state. I rebooted the system to bring back up the `org.freedesktop.portal.Secret`, but all sites remained logged-out in Brave.

I guess conclusion here is that whenever Brave fails to retrieve its application secrets from org.freedesktop.portal.Secret, it fails parmanently and discards prior secrets stored.

**Comment by lavavex** [comment]
Happens to me on CachyOS with latest updates on everything on Brave Origin Nightly [Brave 1.92.4 (Official Build) nightly (64-bit)]
X(Twitter), Youtube, Github, Everything seems to log out after a while and its getting really annoying to have to keep relogging into everything... Might just go back to Floorp at this point

**Comment by TylerJaacks** [comment]
This is happening to me on Windows as well.

**Comment by Crankster619** [comment]
This happens to me once every like 3-6 months or so, I open Brave and am logged out of every site and extension, it just happened again now after closing Brave and leaving the PC on overnight and then opening up Brave again. Unlike most reports here, this happens on startup after the browser has been closed, not while the browser is running. The histograms I attached are from the startup when the logout occurred, before restarting Brave again.

SessionTerminationTrigger differs from documented pattern:
My Signin.BoundSessionCredentials.SessionTerminationTrigger shows mean = 0.0 (both samples at bucket 0), not the mean = 1.0 pattern from #49300. Not sure if this reflects a different code path or is specific to the startup-triggered variant.

Other notable histogram findings:
CookieRotationResult.Startup: 100% failure at bucket 3 (both samples)
CookieRotationHttpResult.WithoutChallenge: 19/20 samples returned 401
Net.DeviceBoundSessions.DeletionReason: completely empty

Histogram files:
[Signin.BoundSessionCredentials.txt](https://github.com/user-attachments/files/29141596/Signin.BoundSessionCredentials.txt)
[Net.DeviceBoundSessions.txt](https://github.com/user-attachments/files/29141598/Net.DeviceBoundSessions.txt)

Brave 1.91.175 (Official Build) (64-bit)
Chromium: 149.0.7827.155
Windows 11

**Comment by chairulakmal** [comment]
I start to experience this problem with GitHub, Google, and multiple other services on 

Brave 1.91.175 (Official Build) (64-bit)
Chromium: 149.0.7827.155
Ubuntu 24.04

The problem seems to be fixed after reinstalling the same version of the app.
