### ISSUE TITLE
Memory Leak When Refreshing Page

### ISSUE THREAD

**Issue by cholyoak** [brave/brave-browser#50420]
### Description

I have a very simple page that reloads itself regularly using a `<meta http-equiv="refresh" content="60">` tag. As it is refreshed, the memory used by the tab continues to grow.

I initiall noticed this problem with a much more complicated page, but was able to reduce the problem down to even the simplest of pages (attached in the reproduction steps).

### Steps to reproduce

1. Load [this simple file](https://github.com/user-attachments/files/23090711/index.html) from a web server. (The problem doesn't seem to occur if loaded locally with a `file:///` URL.)
2. Wait for several hours. It will refresh itself many times.
3. Observe the memory use reported for the tab. It slowly grows as the page is refreshed.

### Actual result

Over time the memory use of the tab grows substantially.

In memory profiles, nothing shows up under `Detached elements` but when running a heap shapshot there is a large number of objects labelled as `Detached` that I'm guessing are all the old copies of the page from each reload. It seems they're never getting removed. I can include a sample heap snapshot if necessary.

<img width="347" height="986" alt="detached objects in the heap snapshot" src="https://github.com/user-attachments/assets/6c70de2e-3da8-4ea8-bfa0-48ed3bc779da" />

These objects do not show up in Chrome or Chromium.

### Expected result

The memory usage of the page should be stable. Memory use is stable with the identical page in Chrome (141.0.7390.122) and Chromium (141.0.7390.107).

### Reproduces how often

Easily reproduced

### Brave version (brave://version info)

Brave: `1.83.118 Chromium: 141.0.7390.108 (Official Build) (64-bit)`
Revision: `ec33d6d073bca3952d54e0cd4024fe34c3f11347`
OS: `Linux`

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome

**Comment by rebron** [comment]
@cholyoak Can you update to our latest 1.83.120 with CR 141.07390.122 and see if it's still happening?

**Comment by cholyoak** [comment]
Yes, it's the same with:

Brave: `1.83.120 Chromium: 141.0.7390.122 (Official Build) (64-bit)`
Revision: `2647fda258705fce2a699977648e614d3e23e4ae`

**Comment by cholyoak** [comment]
To quantify it, the tab (Brave open with no other tabs open) is up to 1.5GB usage after about 18 hours.

**Comment by huntercaron** [comment]
Also experiencing this, I can reproduce by finding a heavy webpage like a webapp that needs 1ish GB of memory, then refreshing a few times - memory usage will linearly increase with amount of refreshes until the browser crashes 

This is MacOS 15.7.1 with Brave v1.83.120

Attempting the same reproduction with Chrome 141.0.7390.123, memory usage stabilizes after each refresh and is totally fine

(Anyone looking for a drastic solution, I got tired of waiting and switched to Helium. It doesn't have this issue)

**Comment by ubunteroz** [comment]
I'm experiencing this, too. Memory usage is increasing after every refresh and can reach >1 GB after some refreshes.

macOS 26.0.1
Brave 1.84.132

**Comment by cholyoak** [comment]
I'm now running `1.84.135` and it looks like it has been resolved.

**Comment by GastonKhouri** [comment]
This problem has been going on for months and they don’t fix it. I’m on the latest version, I refresh each tab every minute, and with every refresh the tab increases by 100 MB. I’ve seen it reach up to 6 GB until I get an out-of-memory error. The only solution I’ve found is to install an old version of the browser.


<img width="234" height="45" alt="Image" src="https://github.com/user-attachments/assets/7fcdb9bf-f5e1-435f-8a0c-113ebf73c9c3" />


When using an old version of the browser, each tab does not exceed 500 MB of memory.

**Comment by A-t-s-u-s-h-i** [comment]
+1 reports in the community thread.

https://community.brave.app/t/topic/647947

Issue Summary: Memory usage increases with each page reload.

Steps to Reproduce:

1. Open any page (https://example.com)
2. Repeat reloading at 500ms intervals

Result of Operations: 

Reload Count | Memory Usage | MB or GB
1 time | 34,920K | ~34MB
100 times | 344,052K | ~345MB
200 times | 626,668K | ~612MB
500 times | 1,558,240K | ~1.5GB
1000 times | 3,091,732K | ~3.0GB

In Google Chrome, memory usage stayed between 30MB and 40MB no matter how many times it was reloaded, so I expect similar usage levels.

Windows 10 Home 1903/Brave 1.85.118 
Windows 10 Home 22H2/Brave 1.85.120

**Comment by cholyoak** [comment]
> I'm now running `1.84.135` and it looks like it has been resolved.

Yeah, I'm retracting this. I'm currently running `1.85.120` and still have these memory leaks on reload.

**Comment by MasterLink86** [comment]
Since this still exists in v1.86.142, but does _not_ exist in Chromium, I'm adding my "me too" here to bump this.

Example.com test on initial load:
<img width="510" height="48" alt="Image" src="https://github.com/user-attachments/assets/910c6f40-d2ed-4d70-ad58-0f79ab6b5591" />

After pressing F5 100 times:
<img width="523" height="53" alt="Image" src="https://github.com/user-attachments/assets/f211402b-fa35-450d-b987-b26b33b7fc8f" />

Again, cannot reproduce in Chromium, but have been able to reproduce in Brave as of it being brought to my attention a couple weeks ago.

**Comment by atuchin-m** [comment]
Will be fixed here: https://github.com/brave/brave-browser/issues/51705
