### ISSUE TITLE
using user wallets with withdraw funds from a restored wallet doesn't work

### ISSUE THREAD

**Issue by zavan** [brave/brave-browser#5398]
## Description
I downloaded the latest nightly version to test the new withdraw feature but it didn't work, uphold shows my "Brave Browser" card as empty.

## Steps to Reproduce
   1. Download latest version of Brave Browser nightly and install it
   2. Recover your funded wallet from the seed of the stable version
   3. Click "Withdraw" on the Rewards page
   4. Login into a verified uphold account, linking it to the Brave Wallet

## Actual result:
A new card called "Brave Browser" is created on Uphold, but it shows 0 funds.

<img width="388" alt="Screen Shot 2019-07-25 at 19 22 05" src="https://user-images.githubusercontent.com/1722965/61913687-45fe2100-af14-11e9-913e-5434eaeb14b5.png">
<img width="362" alt="Screen Shot 2019-07-25 at 19 22 16" src="https://user-images.githubusercontent.com/1722965/61913690-48607b00-af14-11e9-88ca-7295612e11d9.png">

## Expected result:
Funds show on "Brave Broswer" card on Uphold.

## Reproduces how often: 
Only tried once. Clicking "Withdraw" again simply redirects to the empty Uphold card.

## Brave version (brave://version info)
Brave	0.70.3 Chromium: 76.0.3809.62 (Official Build) nightly (64-bit)
Revision	7b77856b3aa34d72f246d12340fc1ded8b2c0e83-refs/branch-heads/3809@{#798}
OS	Mac OS X
JavaScript	V8 7.6.303.20
Flash	(Disabled)
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.62 Safari/537.36
Command Line	/Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly -psn_0_44706464 --enable-dom-distiller --disable-domain-reliability --disable-chrome-google-url-tracking-client --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --enable-features=NewExtensionUpdaterService,SimplifyHttpsIndicator --disable-features=AutofillServerCommunication,NetworkService,UnifiedConsent --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Brave Browser Nightly.app/Contents/MacOS/Brave Browser Nightly
Profile Path	/Users/zavan/Library/Application Support/BraveSoftware/Brave-Browser-Nightly/Default
Variations	d74ef32b-f693abd7

## Version/Channel Information:
This feature is currently only available on the nightly channel.

**Comment by kjozwiak** [comment]
@zavan sounds like this is basically https://github.com/brave/brave-browser/issues/5366 which was recently fixed and landed in `0.70.7` as per https://github.com/brave/brave-core/pull/2996. Looks like you're using `0.70.3` which wouldn't have the fix.

Once the new nightly gets pushed, the above should be resolved. I'll leave this opened for now until you get updated and verify if it's working for you 👍

**Comment by zavan** [comment]
@kjozwiak Thank you, I'll wait for the update.

**Comment by mandar-brave** [comment]
thanks
 @kjozwiak 
@NejcZdovc can you please link and close this issue.

**Comment by kjozwiak** [comment]
Closing as a duplicate of #5366 as mentioned above in my original comment. @zavan please re-open the issue if you can still reproduce once you've updated to the latest nightly 👍

**Comment by zavan** [comment]
Hi, I've updated to:
Version 0.70.12 Chromium: 76.0.3809.72 (Official Build) nightly (64-bit)

But the issue persists, funds do not show up on Uphold after clicking "withdraw".

**Comment by zavan** [comment]
I tried deleting Nightly and its data dir, reinstalling the latest version, restoring the wallet and clicking withdraw again. Same result.
