### ISSUE TITLE
Fails to load recommendation section on Expedia

### ISSUE THREAD

**Issue by chkk525** [brave/brave-browser#5635]
## Description 

Failed to load Recommendation section in Expedia's promotion page.

## Steps to Reproduce

   1. Open https://www.expedia.co.jp/expedia-sale?langid=1041&EMLCID=JP.MR.DISCOVER.HOURLYSALE.GENERIC&EMLDTL=DATE20190709.SID6336049.KEY6336049001314019.PAID203152219.LANGJA_JP.MCIDM.TEST1.VERSX.MIDS1-27554_2-23446_3-13190_4-999_5-999_6-999.MOD77-3-28-0-EMAIL-HERO-JA-JP_S2-P8_POS7_BTN1&mgparam=1%3ANjM5OTM3MjM%3AMDItYjE5MTg5LTU1YThmNDI5YjI0NzRhOTQ5NTY2ZWY3YzJkMTNiOTY1%3Aci5jaGlrYWtraUBnbWFpbC5jb20%3ASlAuTVIuRElTQ09WRVIuSE9VUkxZU0FMRS5HRU5FUklDJkVNTERUTD1EQVRFMjAxOTA3MDkuU0lENjMzNjA0OS5LRVk2MzM2MDQ5MDAxMzE0MDE5LlBBSUQyMDMxNTIyMTkuTEFOR0pBX0pQLk1DSURNLlRFU1QxLlZFUlNYLk1JRFMxLTI3NTU0XzItMjM0NDZfMy0xMzE5MF80LTk5OV81LTk5OV82LTk5OQ%3A%3A%3AIEZQPjKkKBCcTcQZsDSQjw&rfrr=AB.5037.1

## Actual result:

Left: Chrome <-> Right: Brave
![image](https://user-images.githubusercontent.com/3054915/62910647-4889c300-bdbc-11e9-9817-7c99bc8a0bb3.png)

## Expected result:
 - Load the banner 

## Reproduces how often: 

- Easily reproduce

## Brave version (brave://version info)

Brave	0.70.54 Chromium: 76.0.3809.100 (Official Build) nightly （64 ビット）
変更履歴	ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
OS	Mac OS X

## Version/Channel Information:

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
- Does the issue resolve itself when disabling Brave Rewards?
- Is the issue reproducible on the latest version of Chrome?

**Comment by ryanbr** [comment]
Is the link correct @chkk525 ?  I don't see any expedia elements on dmm

**Comment by chkk525** [comment]
@ryanbr Sorry the URL was incorrect. I updated it.

**Comment by ryanbr** [comment]
Should been resolved with the commit previously;

`@@||travel-assets.com/platform-analytics-prime/$script
`

**Comment by bsclifton** [comment]
@chkk525 is this still happening? I tried the URL above and it appears to work

**Comment by chkk525** [comment]
@bsclifton on Nightly it's not fixed. on release it is fixed.
![image](https://user-images.githubusercontent.com/3054915/63310724-c4dd5280-c336-11e9-8827-4da4a1a77269.png)

**Comment by ryanbr** [comment]
Just tested in Version 0.71.17 Chromium: 76.0.3809.100 (Official Build) nightly (64-bit)  Seems to be okay?

**Comment by chkk525** [comment]
@ryanbr Tested in 0.71.21 Chromium: 76.0.3809.100 (Official Build) nightly but the recommendation items still missing.

![image](https://user-images.githubusercontent.com/3054915/63421800-2ccd8f00-c444-11e9-9ef7-25c3bb33a7ef.png)

**Comment by ryanbr** [comment]
Hey @chkk525 was this resolved? just re-testing this and seems to be working well here.

**Comment by chkk525** [comment]
@ryanbr The part itself no longer seems to appear on the flash sale page. I checked a similar section on another page and it was showing up correctly.　

![Uploading image.png…]()
