### ISSUE TITLE
Brave Wallet overrides MetaMask web3 even when disabled

### ISSUE THREAD

**Issue by shanefontaine** [brave/brave-browser#6053]
## Description 
I am unable to connect to MetaMask when attempting to interact with a contract on remix.ethereum.org. 

The MetaMask injected web3 and the Brave injected web3 conflict and I am unable to use MetaMask.

As an aside, when the Brave Browser wallet is enabled, I get redirected to set up a Brave wallet. When the Brave Browser wallet is disabled, I still get redirected, but to a blank page instead.

## Steps to Reproduce

   1. Install and unlock MetaMask
   2. Go to https://remix.ethereum.org
   3. Go to the "Deploy and Run Transactions" tab
   4. Change the "Environment" to Injected Web3
   5. Attempt to make a transaction with MetaMask

## Actual result:
Unable to connect to MetaMask and send transactions.

## Expected result:
Able to connect to MetaMask and send transactions.

## Reproduces how often: 
Easily reproduced

## Brave version (brave://version info)

* Brave Browser Beta
* Brave: 0.70.93 Chromium: 76.0.3809.132 (Official Build) beta (64-bit)
* Revision: fd1acc410994a7a68ac25bc77513d443f3130860-refs/branch-heads/3809@{#1035}
* OS: Mac OS X

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields?
No

- Does the issue resolve itself when disabling Brave Rewards?
No

- Is the issue reproducible on the latest version of Chrome? 
No

## Miscellaneous Information:

The console produces the first image when first landing on the site. The console produces the second image after being redirected to brave wallet.

![Screen Shot 2019-09-17 at 12 53 22 PM](https://user-images.githubusercontent.com/9441295/65074702-36b2b700-d94a-11e9-9c1c-e9d432e09650.png)

![Screen Shot 2019-09-17 at 12 53 19 PM](https://user-images.githubusercontent.com/9441295/65074713-3b776b00-d94a-11e9-9c51-596fed6fb6e3.png)

**Comment by shanefontaine** [comment]
This seems to have been fixed with Version 0.70.97 Chromium: 77.0.3865.65 (Official Build) beta (64-bit).

Closing.

**Comment by Bitcoinera** [comment]
I am getting this same error and I have an newer version that the one you mention: Version 0.70.121 Chromium: 78.0.3904.70 (Official Build) (64-bit)

Perhaps it wasn't properly fixed after all?

**Comment by nukec** [comment]
Happening here as well as of today.

`Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)`

**Comment by joshstevens19** [comment]
Happening with me today.

Version 0.70.123 Chromium: 78.0.3904.97 (Official Build) (64-bit)

**Comment by PaulRBerg** [comment]
Yup, can also confirm this error still happens today, on version 0.70.123 Chromium: 78.0.3904.97.

The weird thing is that I'm not getting this error in my default Brave user profile, that I created a while ago. Instead, the error appears when I create a new user, install MetaMask and open a dapp.

Which is weird, because both the default user profile and the new one have the same version of the Brave browser when tapping the  "About Brave" menu option + the MetaMask version is the same (7.5.1).

**Comment by PaulRBerg** [comment]
**Update**: so it seems the latest version is actually 1.0.0, not 0.70.123.

Tap the small "Relaunch" button, to the right of the version label printed when tapping "About Brave". This issue with MetaMask should go away after the relaunch.

**Comment by drewstaylor** [comment]
I am still having this issue in version 1.0.0

**Comment by PaulRBerg** [comment]
@drewstaylor have you made sure you disabled the Brave Wallet? Search for "wallet" in settings and there should be a toggle.

**Comment by jderocher** [comment]
For anyone who still has issues, I solved the issue by making sure all of my Brave profiles had the Wallet disabled, then I restarted both Brave and my node dApp which was giving me the multiple wallet console error - that seemed to do the trick for me.

**Comment by drewstaylor** [comment]
> @drewstaylor have you disabled the Brave Wallet? Search for "wallet" in settings and there should be a toggle.

Thanks @PaulRBerg, I figured it out. I had it disabled but I didn't think to close and re-open Brave :)

**Comment by jeremyMG78** [comment]
This is now a problem again. It kept trying to get me to set up the brave wallet. Kinda intruseive. However, by disabling and closing then reopening brave in the instructions above I got it to work.
