### ISSUE TITLE
adblocker doesn't work if I am logged in to google

### ISSUE THREAD

**Issue by szaimen** [brave/brave-browser#6318]
1. log in to google
2. search for washing machine
3. see adverts
![image](https://user-images.githubusercontent.com/42591237/66245033-872c6180-e70b-11e9-9fa3-db80b1ee7944.png)
but there shouldn't be any adverts.

I am using Brave on Windows 10: Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
Scripts are allowed, adblocker is activated.

**Comment by ryanbr** [comment]
This should be resolved when we implement cosmetic filtering. So adblock div's will be hidden. Its currently being worked on, so watch this space :)

**Comment by szaimen** [comment]
@ryanbr is there another a PR or Issue, that I can track, where you implement Cosmetic Filters?

**Comment by ryanbr** [comment]
Sure; https://github.com/brave/brave-browser/issues/5381

**Comment by szaimen** [comment]
Thanks!

**Comment by szaimen** [comment]
I tried this again with cosmetic blocking enabled and it still shows first party ads. Is there something I am missing?

**Comment by bsclifton** [comment]
@szaimen I don't think first party ads are removed

cc: @antonok-edm @snyderp for confirmation

**Comment by snyderp** [comment]
@szaimen yes, by design we don't block first party ads. There will be a blog post going up this week detailing the policy, but the goal is to (i) block the privacy harming third party stuff that manages to circumvent network rules, and (ii) to remove the cosmetic blemishes that network blocking causes.  We're intentionally not harming sites that monetize in a privacy-respecting way

Support for `brave://adblock` is planned but not currently in place.

**Comment by szaimen** [comment]
@snyderp Actually, I thought this was the core of cosmetic blocking. Also why then removing ads on any of those websites (that doesn't make sense based on your explanation because they are first party ads):
![image](https://user-images.githubusercontent.com/42591237/74686241-2f315b80-51d1-11ea-9c1c-034ae52b14ec.png)

Also will this then be implemented at all https://github.com/brave/brave-browser/issues/5318? because it probably conflicts with your statement.

**Comment by snyderp** [comment]
In brave, the "core of cosmetic blocking" is (i) remove cosmetic effects of network rules, (ii) hide 3p ads that aren't blocked by network rules.  It is not to block first party ads.

Other tools and extensions have different goals.  If you're looking for something that will block first party ads at the cosmetic layer, there are several extensions that will do that for you.  :)

#5318 is still being discussed, no commitment or plan or timeline at the moment

**Comment by szaimen** [comment]
Okay. Thanks for making that clear!
Then it seems like those that I have mentioned aren't really first party ads?

**Comment by snyderp** [comment]
They're not cosmetic filters.  We block anything we think might have privacy harm at the network level, 1p or 3p (we rely on EasyList, other similar lists, and Brave generated lists for this).  We don't audit these lists in general because they're enormous and we rely on those groups to do that identification.

The reason we make special exceptions / checks for cosmetic rules is that there is no privacy cost / harm at the cosmetic level, so we are more lenient / cautious towards 1p ads at this point
