### ISSUE TITLE
Browser crash when Tor/Guest/Private window is opened just after launching browser - follow up to 6476

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#6565]
Follow up to https://github.com/brave/brave-browser/issues/6476

The browser still crashes, but in order to crash, the private window needs to be opened just after browser launch

## Steps to Reproduce

   1. Clean profile
   2. Launch Brave
   3. Immediately open  Tor/Guest/Private window
   4. Wait 10 seconds

## Actual result:

Crash

![6565](https://user-images.githubusercontent.com/34715963/67202897-0909d380-f40a-11e9-9868-0275c1d30a74.gif)

Note: Have not experienced the crash if waited for 10 seconds after launching Brave
Note: I was not able to generate crash dmps, nor crash ids 
Note: Crash reproduced on en_US locale

## Expected result:
No crash

## Reproduces how often: 

Always

## Brave version (brave://version info)

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @bsclifton @rebron

**Comment by kjozwiak** [comment]
Reproduced on `macOS 10.14.6 x64 using the following build:

Brave | 0.70.119 Chromium: 78.0.3904.50 (Official Build) (64-bit)
-- | --
Revision | 2accdc52c79976e264cd2694df6db31d1fccd8e8-refs/branch-heads/3904@{#658}
OS | macOS Version 10.14.6 (Build 18G95)

When Brave crashes, it creates the following two crash reports:

* https://stats.brave.com/dashboard#crash/5dadbf982c619d001f9c213d
   * `content::ChildThreadImpl::Init(content::ChildThreadImpl::Options const&)`
* https://stats.brave.com/dashboard#crash/5dadbf989ab519001f493664
   * `greaselion::GreaselionTabHelper::OnRulesReady(greaselion::GreaselionDownloadService*)`

We should fix this before releasing `0.70.x`. Crashes are never ideal especially when using major functionality like private and Tor windows.

**Comment by GeetaSarvadnya** [comment]
The issue is still reproducible on Windows also, tested against in Windows 10 x64 - 0.70.119

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/brave-core/commit/e2d9a611a1626a5ca9821bc6e07d36b2de26cf5c

Fixed on 0.71.x with https://github.com/brave/brave-core/commit/04531e96ad91d63a1f1a85271ca9e72d0613b5ae

And 0.72.x forward is fixed with https://github.com/brave/brave-core/pull/3319

**Comment by GeetaSarvadnya** [comment]
Verification passed on


Brave | 0.70.120 Chromium: 78.0.3904.70 (Official Build) (64-bit)
-- | --
Revision | edb9c9f3de0247fd912a77b7f6cae7447f6d3ad5-refs/branch-heads/3904@{#800}
OS | Windows 10 OS Version 1803 (Build 17134.1006)

- Verified the STR from the description
- Verified the locales the US, UK, New Zealand, Ireland, Germany, and Austalia. - No crash in PT/TOR/Guest windows
- Verified both clean and upgraded profile
- Verified no crash in PT/TOR/Guest windows, kept each window open for 20 secs and observed there is no crash
