### ISSUE TITLE
Brave always crashes when trying to enter a website

### ISSUE THREAD

**Issue by Ladrason** [brave/brave-browser#7363]
## Description 
Since the latest update (1.4.21) Brave keeps crashing whenever I try to enter any website at all except for the first search I do. The weird thing is that the website seems to load in if I open it in a new tab but once I try to view it Brave crashes.

Also, I'm sometimes able to open some websites, but not always.

I'll post two gifs as examples just to show what happens. I'm using a clean install of Brave nightly in the video.

https://i.imgur.com/mUysin0.gifv - This happens whenever I try to open a website or even just search for something.

https://i.imgur.com/CAiTUDt.gifv - When I open the website in a different tab it seems to load correctly but once I try to enter Brave crashes.

## Steps to Reproduce
   1. Open any website.

## Actual result:
Brave crashes without a warning.

## Expected result:
Website loads and is able to be viewed.

## Reproduces how often: 
Always (except for some parts of websites sometimes)

## Brave version (brave://version info)
Brave: 1.4.21 Chromium: 79.0.3945.74 (Official Build) nightly (64-bit)

Revision: 99b6d241cf84f7fa7434ae8a59f9e74eb1464280-refs/branch-heads/3945@{#888}

OS: Windows 10 OS Version 1909 (Build 18363.535)

## Version/Channel Information:
This can only be reproduced in the nightly build.

## Other Additional Information:
This always happens regardless if I have extensions on or off, if I have cleared the history and everything with it or if I even does an completely clean reinstall of Brave nightly.
I might be able to use it for a little bit after a clean install but soon it starts to crash regardless of what website I try to enter.

**Comment by nazbrok** [comment]
I also have crash issues on the latest nightly build under window 10.

Version 1.4.21 Chromium: 79.0.3945.74 (Official Build) nightly (64-bit).

Exemple of web page crashing 100% of the time when loading : 
[https://github.com/CryptoMF/frostybot](https://github.com/CryptoMF/frostybot)

**Comment by Ladrason** [comment]
This is still an issue in 1.4.25

**Comment by Ladrason** [comment]
Quite edit/update the problem is related to brave rewards as it only happens when I have it turned on.

Example: https://i.imgur.com/gwDukXR.gifv

**Comment by nazbrok** [comment]
Indeed, the brave reward seems to be the issue. I have no crash if I open those links in a private windows

**Comment by bsclifton** [comment]
cc: @NejcZdovc for triage

**Comment by bsclifton** [comment]
Possibly related crash report IDs:
- 77597c0fa1303278 (SQLite DB error)
- cf3e552cba89d77e (`ads::AdsImpl::GetWinnerOverTimeCategory()`)

**Comment by kjozwiak** [comment]
@Ladrason @nazbrok mind going into `brave://crashes` and sharing some of the reports that might be listed under there? The ideal case would be reproducing the crash and than sharing the latest crash report that's appearing in `brave://crashes`

You'll need to make sure the crash report is sent if you don't have `Automatically send crash reports to Brave` enabled via `chrome://settings/privacy`.

Example of a crash report that hasn't been submitted:

<img width="627" alt="Screen Shot 2019-12-17 at 7 36 52 PM" src="https://user-images.githubusercontent.com/2602313/71045893-a16bbe00-2104-11ea-9c18-fb87b5de32ec.png">

Example of a submitted crash report:

<img width="727" alt="Screen Shot 2019-12-17 at 7 37 08 PM" src="https://user-images.githubusercontent.com/2602313/71045912-ae88ad00-2104-11ea-8a3d-385113bd8579.png">

Once the crash report is submitted, please share the `Crash Report ID` so a developer can take a look and narrow down the crash/issue.

**Comment by NejcZdovc** [comment]
cc @tmancey for ads crash

**Comment by nazbrok** [comment]
I clicked on "send now" but the report is in the state "upload requested by user, not yet uploaded"

Do I have to do something to upload it ?

![image](https://user-images.githubusercontent.com/1686551/71074587-d61e5a80-2182-11ea-8125-8e03c21c43b7.png)

**Comment by nazbrok** [comment]
it's all good now.

Here are 3 crash reports :

Uploaded Crash Report ID d27928b57ad68be2
Uploaded Crash Report ID d6ab82dab2beb49a 
Uploaded Crash Report ID 9f883cfbb0d61a15

**Comment by bsclifton** [comment]
@nazbrok thanks for sending those! Should be enough information to narrow it down 🎉

**Comment by nazbrok** [comment]
cool, I hope we can get a fix soon as it's a very frustrating issue

**Comment by tmancey** [comment]
@nazbrok This crash is my priority and if I need any further information I will reach out. Once again, thank you

**Comment by NejcZdovc** [comment]
+1 from https://github.com/brave/brave-browser/issues/7382

**Comment by Ladrason** [comment]
Sorry for not responding any sooner even though I was mentioned specifically.

Here's my last three crash report IDs:
8a9d408553dc5e5a 
b175783f11ce8d80 
2e927417c16531d4

Full list here: https://i.imgur.com/tBx6Hgq.jpg

@tmancey @kjozwiak @bsclifton 
If there's anything else I can do to help out please feel free to contact me again and I'll do everything in my power to help out.

**Comment by tmancey** [comment]
@Ladrason Thank you

**Comment by tmancey** [comment]
> Possibly related crash report IDs:
> 
> * 77597c0fa1303278 (SQLite DB error)
> * cf3e552cba89d77e (`ads::AdsImpl::GetWinnerOverTimeCategory()`)

This is deprecated code as was refactored in 1.3.36. However, speaking with @NejcZdovc we believe we now know the cause of the issue and @NejcZdovc will create a PR

**Comment by tmancey** [comment]
@Ladrason @nazbrok Issue has been resolved, can you please check version `1.4.38` of Nightly when built

**Comment by nazbrok** [comment]
Brave say I have the latest version (1.4.25). I don't know how to update to the 1.4.38 ... on github there is no binaries

![image](https://user-images.githubusercontent.com/1686551/71177654-c2e7b980-226c-11ea-8abf-d6185e546a89.png)

And why brave didn't auto update to version after 1.4.25 5 I killed brave and restarted it and it still say I have the latest) ?

**Comment by Ladrason** [comment]
@nazbrok 

The update will most likely be released without a day or so as it usually is with the nightly releases.

**Comment by nazbrok** [comment]
ok I will wait then. thanks

**Comment by Ladrason** [comment]
@tmancey 
I've updated Brave to 1.4.38 but it still crashes when I have rewards turned on.

I've uploaded the crash report which has the ID 67d9b8636fa311e6

**Comment by tmancey** [comment]
> @tmancey
> I've updated Brave to 1.4.38 but it still crashes when I have rewards turned on.
> 
> I've uploaded the crash report which has the ID 67d9b8636fa311e6

Apologies as we were hoping to merge before the next build. Once this ticket is closed, then the fix will be in the next build. We are waiting for some internal tests to pass.

**Comment by nazbrok** [comment]
updated to latest version this morning.
this bug seems fixed to me.

thanks again

**Comment by NejcZdovc** [comment]
@nazbrok thank you for the feedback and all the help

**Comment by nazbrok** [comment]
I talked too fast.
 
this link crash my browser [https://www.meilleursagents.com/](https://www.meilleursagents.com/)

here is the crash report id : 3816ace99f8e5ebf

**Comment by nazbrok** [comment]
something weird. 

after the upgrade, all the no working links in this thread were working.
now when I try them again they again all crash my browser.

**Comment by nazbrok** [comment]
Note : Brave upgraded to latest version 1.4.38.
I see there is a 1.4.40 in the release tab, reading previous comment maybe the fix is in fact in this 1.4.40 ?

**Comment by NejcZdovc** [comment]
yes, only 1.4.40 has a fix. You can see where it landed https://github.com/brave/brave-core/commits/master

**Comment by Ladrason** [comment]
I've downloaded version 1.4.40 now and so far I've not had any crashes.

Thank you all developers for the quick fix. :)

**Comment by tmancey** [comment]
@Ladrason @nazbrok Thank you for your help in identifying the issue. Much appreciated

**Comment by nazbrok** [comment]
I confirm, looks ok now. thank you guys
