### ISSUE TITLE
dark mode doesn't affect window bar/header

### ISSUE THREAD

**Issue by habamax** [brave/brave-browser#7694]
## Description 
Dark mode is not applied to header bar

## Steps to Reproduce

   1. turn on dark mode in Win10 and in brave
 
## Actual result:
![image](https://user-images.githubusercontent.com/234774/72167506-487a0780-33dc-11ea-8ebe-33ac32c46e7d.png)

## Expected result:
Window header should also be dark

## Brave version (brave://version info)

![image](https://user-images.githubusercontent.com/234774/72167660-9bec5580-33dc-11ea-93ca-d3e821041334.png)

## Other Additional Information:
I use win10, but had to setup compatibility mode for win8 due to chrome error: https://support.google.com/chrome/thread/22780748?hl=en

**Comment by rebron** [comment]
@habamax Can you try this with our latest 1.3.x and are you using Windows Themes. I'm not seeing this with dark mode on Windows 10 and dark mode in Brave.

**Comment by habamax** [comment]
> 
> 
> @habamax Can you try this with our latest 1.3.x and are you using Windows Themes? I'm not seeing this with dark mode on Windows 10 and dark mode in Brave.

![image](https://user-images.githubusercontent.com/234774/75062406-cbba6d00-54f3-11ea-847c-940dd0854ae1.png)

**Comment by rebron** [comment]
@habamax Are you seeing the same thing in Chrome?

**Comment by habamax** [comment]
> @habamax Are you seeing the same thing in Chrome?

I don't have chrome installed

**Comment by bsclifton** [comment]
@habamax is this still a problem? We have fixed several theme related issues - please let us know

**Comment by habamax** [comment]
Nope.

![image](https://user-images.githubusercontent.com/234774/82017299-84bfbc00-968b-11ea-8c8f-d641fecc358c.png)

**Comment by bsclifton** [comment]
@habamax thanks for the quick response - dang. That's crazy- would you mind checking brave://gpu to see what is put there?

Specifically, I'm curious about the main values themselves and then the items under `Problems Detected`. There is a possibility that disabling hardware acceleration or maybe updating video card driver would resolve the problem. There's also a `Copy Report to Clipboard` button that can be easily shared (or screenshot works too)

**Comment by habamax** [comment]
sure, here they are:

<details><summary>brave://gpu</summary><p>


```
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Hardware Protected Video Decode: Unavailable
Rasterization: Hardware accelerated
Skia Renderer: Disabled
Video Decode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
clear_uniforms_before_first_program_use
decode_encode_srgb_for_generatemipmap
disable_accelerated_vpx_decode
disable_delayed_copy_nv12
disable_direct_composition
disable_discard_framebuffer
disable_dxgi_zero_copy_video
disable_nv12_dynamic_textures
exit_on_context_lost
force_cube_complete
msaa_is_slow
scalarize_vec_and_mat_constructor_args
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
Problems Detected
Protected video decoding with swap chain is for Windows and Intel only
Disabled Features: protected_video_decode
Some drivers are unable to reset the D3D device in the GPU process sandbox
Applied Workarounds: exit_on_context_lost
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
ANGLE crash on glReadPixels from incomplete cube map texture: 518889
Applied Workarounds: force_cube_complete
On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
Applied Workarounds: msaa_is_slow
Framebuffer discarding can hurt performance on non-tilers: 570897
Applied Workarounds: disable_discard_framebuffer
Direct composition flashes black initially on Win <10: 588588
Applied Workarounds: disable_direct_composition
Zero copy DXGI video hangs on shutdown on Win < 8.1: 621190
Applied Workarounds: disable_dxgi_zero_copy_video
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Decode and Encode before generateMipmap for srgb format textures on Windows: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
VPx decoding isn't supported well before Windows 10 creators update.: 616318, 667532
Applied Workarounds: disable_accelerated_vpx_decode
VPx decoding is too slow on Intel Broadwell, Skylake, and CherryTrail: 616318
Applied Workarounds: disable_accelerated_vpx_decode
Delayed copy NV12 crashes on Intel on Windows <= 8.1.: 727216
Applied Workarounds: disable_delayed_copy_nv12
Dynamic texture map crashes on Intel drivers less than version 24: 890227
Applied Workarounds: disable_nv12_dynamic_textures
ANGLE Features
disable_program_caching_for_transform_feedback (Frontend workarounds): Disabled
On some GPUs, program binaries don't contain transform feedback varyings
lose_context_on_out_of_memory (Frontend workarounds): Enabled: true
Some users rely on a lost context notification if a GL_OUT_OF_MEMORY error occurs
scalarize_vec_and_mat_constructor_args (Frontend workarounds) 398694: Enabled: true
Always rewrite vec/mat constructors to be consistent
sync_framebuffer_bindings_on_tex_image (Frontend workarounds): Disabled
On some drivers TexImage sometimes seems to interact with the Framebuffer
add_dummy_texture_no_render_target (D3D workarounds) anglebug:2152: Disabled: isIntel && capsVersion < IntelDriverVersion(4815)
On some drivers when rendering with no render target, two bugs lead to incorrect behavior
allow_clear_for_robust_resource_init (D3D workarounds) 941620: Disabled: false
Some drivers corrupt texture data when clearing for robust resource initialization.
call_clear_twice (D3D workarounds) 655534: Disabled: isIntel && isSkylake && capsVersion < IntelDriverVersion(4771)
Using clear() may not take effect
depth_stencil_blit_extra_copy (D3D workarounds) anglebug:1452: Disabled
Bug in some drivers triggers a TDR when using CopySubresourceRegion from a staging texture to a depth/stencil
disable_b5g6r5_support (D3D workarounds): Disabled: (isIntel && capsVersion < IntelDriverVersion(4539)) || isAMD
Textures with the format DXGI_FORMAT_B5G6R5_UNORM have incorrect data
dont_translate_uniform_block_to_structured_buffer (D3D workarounds): Disabled: !isWin10
Fails to allocate ShaderResourceView for StructuredBuffer on some drivers
emulate_isnan_float (D3D workarounds) 650547: Disabled: isIntel && isSkylake && capsVersion < IntelDriverVersion(4542)
Using isnan() on highp float will get wrong answer
emulate_tiny_stencil_textures (D3D workarounds): Disabled: isAMD && !(deviceCaps.featureLevel < D3D_FEATURE_LEVEL_10_1)
1x1 and 2x2 mips of depth/stencil textures aren't sampled correctly
expand_integer_pow_expressions (D3D workarounds): Enabled: true
The HLSL optimizer has a bug with optimizing 'pow' in certain integer-valued expressions
flush_after_ending_transform_feedback (D3D workarounds): Disabled: isNvidia
Some drivers sometimes write out-of-order results to StreamOut buffers when transform feedback is used to repeatedly write to the same buffer positions
force_atomic_value_resolution (D3D workarounds) anglebug:3246: Disabled: isNvidia
On some drivers the return value from RWByteAddressBuffer.InterlockedAdd does not resolve when used in the .yzw components of a RWByteAddressBuffer.Store operation
get_dimensions_ignores_base_level (D3D workarounds): Disabled: isNvidia
Some drivers do not take into account the base level of the texture in the results of the HLSL GetDimensions builtin
mrt_perf_workaround (D3D workarounds): Enabled: true
Some drivers have a bug where they ignore null render targets
pre_add_texel_fetch_offsets (D3D workarounds): Enabled: isIntel
HLSL's function texture.Load returns 0 when the parameter Location is negative, even if the sum of Offset and Location is in range
rewrite_unary_minus_operator (D3D workarounds): Disabled: isIntel && (isBroadwell || isHaswell) && capsVersion < IntelDriverVersion(4624)
Evaluating unary minus operator on integer may get wrong answer in vertex shaders
select_view_in_geometry_shader (D3D workarounds): Disabled: !deviceCaps.supportsVpRtIndexWriteFromVertexShader
The viewport or render target slice will be selected in the geometry shader stage for the ANGLE_multiview extension
set_data_faster_than_image_upload (D3D workarounds): Enabled: !(isIvyBridge || isBroadwell || isHaswell)
Set data faster than image upload
skip_vs_constant_register_zero (D3D workarounds): Disabled: isNvidia
In specific cases the driver doesn't handle constant register zero correctly
use_instanced_point_sprite_emulation (D3D workarounds): Disabled: isFeatureLevel9_3
Some D3D11 renderers do not support geometry shaders for pointsprite emulation
use_system_memory_for_constant_buffers (D3D workarounds) 593024: Enabled: isIntel
Copying from staging storage to constant buffer storage does not work
zero_max_lod (D3D workarounds): Disabled: isFeatureLevel9_3
Missing an option to disable mipmaps on a mipmapped texture
Version Information
Data exported	2020-05-15T06:46:12.749Z
Chrome version	Chrome/81.0.4044.138
Operating system	Windows NT 6.2.9200
Software rendering list URL	https://chromium.googlesource.com/chromium/src/+/8c6c7ba89cc9453625af54f11fd83179e23450fa/gpu/config/software_rendering_list.json
Driver bug list URL	https://chromium.googlesource.com/chromium/src/+/8c6c7ba89cc9453625af54f11fd83179e23450fa/gpu/config/gpu_driver_bug_list.json
ANGLE commit id	91c39dae9a51
2D graphics backend	Skia/81 5e3098d8fad5b3a6fa9c70d6438f416eec201db7
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --profile-directory=Default --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps --disable-features=TextFragmentAnchor,AllowPopupsDuringPageUnload,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Driver Information
Initialization time	454
In-process GPU	false
Passthrough Command Decoder	true
Sandboxed	true
GPU0	VENDOR= 0x8086, DEVICE=0x191b, SUBSYS=0x06df1028, REV=6 *ACTIVE*
GPU1	VENDOR= 0x1414, DEVICE=0x008c
Optimus	false
AMD switchable	false
Desktop compositing	Aero Glass
Direct composition	false
Supports overlays	false
YUY2 overlay support	NONE
NV12 overlay support	NONE
Diagonal Monitor Size of \\.\DISPLAY1	15.5"
Driver D3D12 feature level	D3D 12.1
Driver Vulkan API version	Not supported
Driver vendor	ANGLE (Intel)
Driver version	23.20.16.4973
GPU CUDA compute capability major version	0
Pixel shader version	5.0
Vertex shader version	5.0
Max. MSAA samples	16
Machine model name	
Machine model version	
GL_VENDOR	Google Inc.
GL_RENDERER	ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
GL_VERSION	OpenGL ES 2.0.0 (ANGLE 2.1.0.91c39dae9a51)
GL_EXTENSIONS	GL_ANGLE_base_vertex_base_instance GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_explicit_context GL_ANGLE_explicit_context_gles1 GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_multiview_multisample GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_CHROMIUM_sync_query GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_3D GL_OES_texture_border_clamp GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object GL_WEBGL_video_texture
Disabled Extensions	GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions	
Window system binding vendor	Google Inc. (adapter LUID: 000000000000ec56)
Window system binding version	1.4 (ANGLE 2.1.0.91c39dae9a51)
Window system binding extensions	EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_ANGLE_windows_ui_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_CHROMIUM_sync_control EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context EGL_ANGLE_display_texture_share_group EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control EGL_ANGLE_robust_resource_initialization EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache EGL_ANDROID_recordable EGL_ANGLE_image_d3d11_texture EGL_ANGLE_create_context_backwards_compatible
Direct rendering version	unknown
Reset notification strategy	0x8252
GPU process crash count	0
gfx::BufferFormats supported for allocation and texturing	R_8: not supported, R_16: not supported, RG_88: not supported, BGR_565: not supported, RGBA_4444: not supported, RGBX_8888: not supported, RGBA_8888: not supported, BGRX_8888: not supported, BGRX_1010102: not supported, RGBA_1010102: not supported, BGRA_8888: not supported, RGBA_F16: not supported, YVU_420: not supported, YUV_420_BIPLANAR: not supported, P010: not supported
Compositor Information
Tile Update Mode	One-copy
Partial Raster	Enabled
GpuMemoryBuffers Status
R_8	Software only
R_16	Software only
RG_88	Software only
BGR_565	Software only
RGBA_4444	Software only
RGBX_8888	GPU_READ, SCANOUT
RGBA_8888	GPU_READ, SCANOUT
BGRX_8888	Software only
BGRX_1010102	Software only
RGBA_1010102	Software only
BGRA_8888	Software only
RGBA_F16	Software only
YVU_420	Software only
YUV_420_BIPLANAR	Software only
P010	Software only
Display(s) Information
Info	Display[2528732444] bounds=[0,0 1536x864], workarea=[0,0 1536x824], scale=1.25, rotation=0, panel_rotation=0 external.
Color space information	{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}
SDR white level in nits	100
Bits per color component	8
Bits per pixel	24
Refresh Rate in Hz	60
Video Acceleration Information
Decode h264 baseline	48x48 to 4096x2304 pixels
Decode h264 baseline	48x48 to 2304x4096 pixels
Decode h264 main	48x48 to 4096x2304 pixels
Decode h264 main	48x48 to 2304x4096 pixels
Decode h264 high	48x48 to 4096x2304 pixels
Decode h264 high	48x48 to 2304x4096 pixels
Encode h264 baseline	0x0 to 3840x2176 pixels, and/or 30.000 fps
Encode h264 main	0x0 to 3840x2176 pixels, and/or 30.000 fps
Encode h264 high	0x0 to 3840x2176 pixels, and/or 30.000 fps
Vulkan Information
Diagnostics
0
b3DAccelerationEnabled	true
b3DAccelerationExists	true
bAGPEnabled	true
bAGPExistenceValid	true
bAGPExists	true
bCanRenderWindow	true
bDDAccelerationEnabled	true
bDriverBeta	false
bDriverDebug	false
bDriverSigned	false
bDriverSignedValid	false
bNoHardware	false
dwBpp	32
dwDDIVersion	12
dwHeight	1080
dwRefreshRate	60
dwWHQLLevel	0
dwWidth	1920
iAdapter	0
lDriverSize	1930440
lMiniVddSize	0
szAGPStatusEnglish	Enabled
szAGPStatusLocalized	Enabled
szChipType	Intel(R) HD Graphics Family
szD3DStatusEnglish	Enabled
szD3DStatusLocalized	Enabled
szDACType	Internal
szDDIVersionEnglish	12
szDDIVersionLocalized	12
szDDStatusEnglish	Enabled
szDDStatusLocalized	Enabled
szDXVAHDEnglish	Supported
szDXVAModes	ModeMPEG2_A ModeMPEG2_C ModeWMV9_C ModeVC1_C
szDescription	Intel(R) HD Graphics 530
szDeviceId	0x191B
szDeviceIdentifier	{D7B78E66-5A5B-11CF-F560-CF26BDC2DA35}
szDeviceName	\\.\DISPLAY1
szDisplayMemoryEnglish	8148 MB
szDisplayMemoryLocalized	8148 MB
szDisplayModeEnglish	1920 x 1080 (32 bit) (60Hz)
szDisplayModeLocalized	1920 x 1080 (32 bit) (60Hz)
szDriverAssemblyVersion	23.20.16.4973
szDriverAttributes	Final Retail
szDriverDateEnglish	28.02.2018 3:00:00
szDriverDateLocalized	2/28/2018 03:00:00
szDriverLanguageEnglish	English
szDriverLanguageLocalized	English
szDriverModelEnglish	WDDM 2.1
szDriverModelLocalized	WDDM 2.1
szDriverName	C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd12umd64.dll
szDriverNodeStrongName	oem118.inf:5f63e5340a14bf6c:iSKLD_w10_DS:23.20.16.4973:pci\ven_8086&dev_191b&subsys_06df1028
szDriverSignDate	Unknown
szDriverVersion	23.20.0016.4973
szKeyDeviceID	Enum\PCI\VEN_8086&DEV_191B&SUBSYS_06DF1028&REV_06
szKeyDeviceKey	\Registry\Machine\System\CurrentControlSet\Control\Video\{9ECB1987-A280-11E9-9E5E-B9CF6FFDEA2B}\0000
szManufacturer	Intel Corporation
szMiniVdd	unknown
szMiniVddDateEnglish	Unknown
szMiniVddDateLocalized	unknown
szMonitorMaxRes	Unknown
szMonitorName	Generic PnP Monitor
szNotesEnglish	No problems found.
szNotesLocalized	No problems found.
szOverlayEnglish	Supported
szRankOfInstalledDriver	00D10001
szRegHelpText	Unknown
szRevision	Unknown
szRevisionId	0x0006
szSubSysId	0x06DF1028
szTestResultD3D7English	Not run
szTestResultD3D7Localized	Not run
szTestResultD3D8English	Not run
szTestResultD3D8Localized	Not run
szTestResultD3D9English	Not run
szTestResultD3D9Localized	Not run
szTestResultDDEnglish	Not run
szTestResultDDLocalized	Not run
szVdd	unknown
szVendorId	0x8086
Log Messages
GpuProcessHost: The unsandboxed GPU process exited normally. Everything is okay.
```

</p></details>

**Comment by simonhong** [comment]
@habamax According to your screenshot, your OS is Win8. and I also saw this only win8.

**Comment by habamax** [comment]
> 
> 
> @habamax According to your screenshot, your OS is Win8. and I also saw this only win8.

There was an issue with chrome and all chrome based applications -- they just didn't work. The only solution at the time was to run them in compatibility mode -- let me check if it was fixed and I can run brave without it.


yes, now it works without compatibility mode but this issue is still there:

![image](https://user-images.githubusercontent.com/234774/82023276-b1c59c00-9696-11ea-8505-49cf61d0f3b4.png)


<details><summary>brave://gpu without compatibilty mode</summary><p>

```
Graphics Feature Status
Canvas: Hardware accelerated
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Out-of-process Rasterization: Disabled
OpenGL: Enabled
Hardware Protected Video Decode: Unavailable
Rasterization: Hardware accelerated
Skia Renderer: Disabled
Video Decode: Hardware accelerated
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
clear_uniforms_before_first_program_use
decode_encode_srgb_for_generatemipmap
disable_accelerated_vpx_decode
disable_delayed_copy_nv12
disable_direct_composition
disable_discard_framebuffer
disable_dxgi_zero_copy_video
disable_nv12_dynamic_textures
exit_on_context_lost
force_cube_complete
msaa_is_slow
scalarize_vec_and_mat_constructor_args
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
Problems Detected
Protected video decoding with swap chain is for Windows and Intel only
Disabled Features: protected_video_decode
Some drivers are unable to reset the D3D device in the GPU process sandbox
Applied Workarounds: exit_on_context_lost
Clear uniforms before first program use on all platforms: 124764, 349137
Applied Workarounds: clear_uniforms_before_first_program_use
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
ANGLE crash on glReadPixels from incomplete cube map texture: 518889
Applied Workarounds: force_cube_complete
On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
Applied Workarounds: msaa_is_slow
Framebuffer discarding can hurt performance on non-tilers: 570897
Applied Workarounds: disable_discard_framebuffer
Direct composition flashes black initially on Win <10: 588588
Applied Workarounds: disable_direct_composition
Zero copy DXGI video hangs on shutdown on Win < 8.1: 621190
Applied Workarounds: disable_dxgi_zero_copy_video
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Decode and Encode before generateMipmap for srgb format textures on Windows: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
VPx decoding isn't supported well before Windows 10 creators update.: 616318, 667532
Applied Workarounds: disable_accelerated_vpx_decode
VPx decoding is too slow on Intel Broadwell, Skylake, and CherryTrail: 616318
Applied Workarounds: disable_accelerated_vpx_decode
Delayed copy NV12 crashes on Intel on Windows <= 8.1.: 727216
Applied Workarounds: disable_delayed_copy_nv12
Dynamic texture map crashes on Intel drivers less than version 24: 890227
Applied Workarounds: disable_nv12_dynamic_textures
ANGLE Features
disable_program_caching_for_transform_feedback (Frontend workarounds): Disabled
On some GPUs, program binaries don't contain transform feedback varyings
lose_context_on_out_of_memory (Frontend workarounds): Enabled: true
Some users rely on a lost context notification if a GL_OUT_OF_MEMORY error occurs
scalarize_vec_and_mat_constructor_args (Frontend workarounds) 398694: Enabled: true
Always rewrite vec/mat constructors to be consistent
sync_framebuffer_bindings_on_tex_image (Frontend workarounds): Disabled
On some drivers TexImage sometimes seems to interact with the Framebuffer
add_dummy_texture_no_render_target (D3D workarounds) anglebug:2152: Disabled: isIntel && capsVersion < IntelDriverVersion(4815)
On some drivers when rendering with no render target, two bugs lead to incorrect behavior
allow_clear_for_robust_resource_init (D3D workarounds) 941620: Disabled: false
Some drivers corrupt texture data when clearing for robust resource initialization.
call_clear_twice (D3D workarounds) 655534: Disabled: isIntel && isSkylake && capsVersion < IntelDriverVersion(4771)
Using clear() may not take effect
depth_stencil_blit_extra_copy (D3D workarounds) anglebug:1452: Disabled
Bug in some drivers triggers a TDR when using CopySubresourceRegion from a staging texture to a depth/stencil
disable_b5g6r5_support (D3D workarounds): Disabled: (isIntel && capsVersion < IntelDriverVersion(4539)) || isAMD
Textures with the format DXGI_FORMAT_B5G6R5_UNORM have incorrect data
dont_translate_uniform_block_to_structured_buffer (D3D workarounds): Disabled: !isWin10
Fails to allocate ShaderResourceView for StructuredBuffer on some drivers
emulate_isnan_float (D3D workarounds) 650547: Disabled: isIntel && isSkylake && capsVersion < IntelDriverVersion(4542)
Using isnan() on highp float will get wrong answer
emulate_tiny_stencil_textures (D3D workarounds): Disabled: isAMD && !(deviceCaps.featureLevel < D3D_FEATURE_LEVEL_10_1)
1x1 and 2x2 mips of depth/stencil textures aren't sampled correctly
expand_integer_pow_expressions (D3D workarounds): Enabled: true
The HLSL optimizer has a bug with optimizing 'pow' in certain integer-valued expressions
flush_after_ending_transform_feedback (D3D workarounds): Disabled: isNvidia
Some drivers sometimes write out-of-order results to StreamOut buffers when transform feedback is used to repeatedly write to the same buffer positions
force_atomic_value_resolution (D3D workarounds) anglebug:3246: Disabled: isNvidia
On some drivers the return value from RWByteAddressBuffer.InterlockedAdd does not resolve when used in the .yzw components of a RWByteAddressBuffer.Store operation
get_dimensions_ignores_base_level (D3D workarounds): Disabled: isNvidia
Some drivers do not take into account the base level of the texture in the results of the HLSL GetDimensions builtin
mrt_perf_workaround (D3D workarounds): Enabled: true
Some drivers have a bug where they ignore null render targets
pre_add_texel_fetch_offsets (D3D workarounds): Enabled: isIntel
HLSL's function texture.Load returns 0 when the parameter Location is negative, even if the sum of Offset and Location is in range
rewrite_unary_minus_operator (D3D workarounds): Disabled: isIntel && (isBroadwell || isHaswell) && capsVersion < IntelDriverVersion(4624)
Evaluating unary minus operator on integer may get wrong answer in vertex shaders
select_view_in_geometry_shader (D3D workarounds): Disabled: !deviceCaps.supportsVpRtIndexWriteFromVertexShader
The viewport or render target slice will be selected in the geometry shader stage for the ANGLE_multiview extension
set_data_faster_than_image_upload (D3D workarounds): Enabled: !(isIvyBridge || isBroadwell || isHaswell)
Set data faster than image upload
skip_vs_constant_register_zero (D3D workarounds): Disabled: isNvidia
In specific cases the driver doesn't handle constant register zero correctly
use_instanced_point_sprite_emulation (D3D workarounds): Disabled: isFeatureLevel9_3
Some D3D11 renderers do not support geometry shaders for pointsprite emulation
use_system_memory_for_constant_buffers (D3D workarounds) 593024: Enabled: isIntel
Copying from staging storage to constant buffer storage does not work
zero_max_lod (D3D workarounds): Disabled: isFeatureLevel9_3
Missing an option to disable mipmaps on a mipmapped texture
Version Information
Data exported	2020-05-15T07:26:18.664Z
Chrome version	Chrome/81.0.4044.138
Operating system	Windows NT 6.2.9200
Software rendering list URL	https://chromium.googlesource.com/chromium/src/+/8c6c7ba89cc9453625af54f11fd83179e23450fa/gpu/config/software_rendering_list.json
Driver bug list URL	https://chromium.googlesource.com/chromium/src/+/8c6c7ba89cc9453625af54f11fd83179e23450fa/gpu/config/gpu_driver_bug_list.json
ANGLE commit id	91c39dae9a51
2D graphics backend	Skia/81 5e3098d8fad5b3a6fa9c70d6438f416eec201db7
Command Line	"C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application\brave.exe" --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,MixedContentSiteSetting,SimplifyHttpsIndicator,AutoupgradeMixedContent,PassiveMixedContentWarning,WebUIDarkMode,DnsOverHttps --disable-features=TextFragmentAnchor,AllowPopupsDuringPageUnload,AutofillServerCommunication,LookalikeUrlNavigationSuggestionsUI,NotificationTriggers,AudioServiceOutOfProcess,SmsReceiver,VideoPlaybackQuality --flag-switches-begin --load-media-router-component-extension=1 --flag-switches-end --enable-audio-service-sandbox --disable-webrtc-apm-in-audio-service --disable-sync
Driver Information
Initialization time	268
In-process GPU	false
Passthrough Command Decoder	true
Sandboxed	true
GPU0	VENDOR= 0x8086, DEVICE=0x191b, SUBSYS=0x06df1028, REV=6 *ACTIVE*
GPU1	VENDOR= 0x1414, DEVICE=0x008c
Optimus	false
AMD switchable	false
Desktop compositing	Aero Glass
Direct composition	false
Supports overlays	false
YUY2 overlay support	NONE
NV12 overlay support	NONE
Diagonal Monitor Size of \\.\DISPLAY1	15.5"
Driver D3D12 feature level	D3D 12.1
Driver Vulkan API version	Not supported
Driver vendor	ANGLE (Intel)
Driver version	23.20.16.4973
GPU CUDA compute capability major version	0
Pixel shader version	5.0
Vertex shader version	5.0
Max. MSAA samples	16
Machine model name	
Machine model version	
GL_VENDOR	Google Inc.
GL_RENDERER	ANGLE (Intel(R) HD Graphics 530 Direct3D11 vs_5_0 ps_5_0)
GL_VERSION	OpenGL ES 2.0.0 (ANGLE 2.1.0.91c39dae9a51)
GL_EXTENSIONS	GL_ANGLE_base_vertex_base_instance GL_ANGLE_client_arrays GL_ANGLE_depth_texture GL_ANGLE_explicit_context GL_ANGLE_explicit_context_gles1 GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_lossy_etc_decode GL_ANGLE_memory_size GL_ANGLE_multi_draw GL_ANGLE_multiview_multisample GL_ANGLE_pack_reverse_row_order GL_ANGLE_program_cache_control GL_ANGLE_provoking_vertex GL_ANGLE_request_extension GL_ANGLE_robust_client_memory GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_CHROMIUM_bind_generates_resource GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_color_buffer_float_rgb GL_CHROMIUM_color_buffer_float_rgba GL_CHROMIUM_copy_compressed_texture GL_CHROMIUM_copy_texture GL_CHROMIUM_lose_context GL_CHROMIUM_sync_query GL_EXT_blend_func_extended GL_EXT_blend_minmax GL_EXT_color_buffer_half_float GL_EXT_debug_marker GL_EXT_discard_framebuffer GL_EXT_disjoint_timer_query GL_EXT_draw_buffers GL_EXT_float_blend GL_EXT_frag_depth GL_EXT_instanced_arrays GL_EXT_map_buffer_range GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_sRGB GL_EXT_shader_texture_lod GL_EXT_texture_compression_bptc GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_storage GL_EXT_unpack_subimage GL_KHR_debug GL_KHR_parallel_shader_compile GL_NV_EGL_stream_consumer_external GL_NV_fence GL_NV_pack_subimage GL_NV_pixel_buffer_object GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_compressed_EAC_R11_signed_texture GL_OES_compressed_EAC_R11_unsigned_texture GL_OES_compressed_EAC_RG11_signed_texture GL_OES_compressed_EAC_RG11_unsigned_texture GL_OES_compressed_ETC2_RGB8_texture GL_OES_compressed_ETC2_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_RGBA8_texture GL_OES_compressed_ETC2_punchthroughA_sRGB8_alpha_texture GL_OES_compressed_ETC2_sRGB8_alpha8_texture GL_OES_compressed_ETC2_sRGB8_texture GL_OES_depth24 GL_OES_depth32 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_3D GL_OES_texture_border_clamp GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_array_object GL_WEBGL_video_texture
Disabled Extensions	GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent
Disabled WebGL Extensions	
Window system binding vendor	Google Inc. (adapter LUID: 000000000000ec56)
Window system binding version	1.4 (ANGLE 2.1.0.91c39dae9a51)
Window system binding extensions	EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_d3d_texture_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_ANGLE_windows_ui_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture EGL_ANGLE_create_context_webgl_compatibility EGL_CHROMIUM_create_context_bind_generates_resource EGL_CHROMIUM_sync_control EGL_EXT_pixel_format_float EGL_KHR_surfaceless_context EGL_ANGLE_display_texture_share_group EGL_ANGLE_create_context_client_arrays EGL_ANGLE_program_cache_control EGL_ANGLE_robust_resource_initialization EGL_ANGLE_create_context_extensions_enabled EGL_ANDROID_blob_cache EGL_ANDROID_recordable EGL_ANGLE_image_d3d11_texture EGL_ANGLE_create_context_backwards_compatible
Direct rendering version	unknown
Reset notification strategy	0x8252
GPU process crash count	0
gfx::BufferFormats supported for allocation and texturing	R_8: not supported, R_16: not supported, RG_88: not supported, BGR_565: not supported, RGBA_4444: not supported, RGBX_8888: not supported, RGBA_8888: not supported, BGRX_8888: not supported, BGRX_1010102: not supported, RGBA_1010102: not supported, BGRA_8888: not supported, RGBA_F16: not supported, YVU_420: not supported, YUV_420_BIPLANAR: not supported, P010: not supported
Compositor Information
Tile Update Mode	One-copy
Partial Raster	Enabled
GpuMemoryBuffers Status
R_8	Software only
R_16	Software only
RG_88	Software only
BGR_565	Software only
RGBA_4444	Software only
RGBX_8888	GPU_READ, SCANOUT
RGBA_8888	GPU_READ, SCANOUT
BGRX_8888	Software only
BGRX_1010102	Software only
RGBA_1010102	Software only
BGRA_8888	Software only
RGBA_F16	Software only
YVU_420	Software only
YUV_420_BIPLANAR	Software only
P010	Software only
Display(s) Information
Info	Display[2528732444] bounds=[0,0 1536x864], workarea=[0,0 1536x824], scale=1.25, rotation=0, panel_rotation=0 external.
Color space information	{primaries:BT709, transfer:IEC61966_2_1, matrix:RGB, range:FULL}
SDR white level in nits	100
Bits per color component	8
Bits per pixel	24
Refresh Rate in Hz	60
Video Acceleration Information
Decode h264 baseline	48x48 to 4096x2304 pixels
Decode h264 baseline	48x48 to 2304x4096 pixels
Decode h264 main	48x48 to 4096x2304 pixels
Decode h264 main	48x48 to 2304x4096 pixels
Decode h264 high	48x48 to 4096x2304 pixels
Decode h264 high	48x48 to 2304x4096 pixels
Encode h264 baseline	0x0 to 3840x2176 pixels, and/or 30.000 fps
Encode h264 main	0x0 to 3840x2176 pixels, and/or 30.000 fps
Encode h264 high	0x0 to 3840x2176 pixels, and/or 30.000 fps
Vulkan Information
Diagnostics
0
b3DAccelerationEnabled	true
b3DAccelerationExists	true
bAGPEnabled	true
bAGPExistenceValid	true
bAGPExists	true
bCanRenderWindow	true
bDDAccelerationEnabled	true
bDriverBeta	false
bDriverDebug	false
bDriverSigned	false
bDriverSignedValid	false
bNoHardware	false
dwBpp	32
dwDDIVersion	12
dwHeight	1080
dwRefreshRate	60
dwWHQLLevel	0
dwWidth	1920
iAdapter	0
lDriverSize	1930440
lMiniVddSize	0
szAGPStatusEnglish	Enabled
szAGPStatusLocalized	Enabled
szChipType	Intel(R) HD Graphics Family
szD3DStatusEnglish	Enabled
szD3DStatusLocalized	Enabled
szDACType	Internal
szDDIVersionEnglish	12
szDDIVersionLocalized	12
szDDStatusEnglish	Enabled
szDDStatusLocalized	Enabled
szDXVAHDEnglish	Supported
szDXVAModes	ModeMPEG2_A ModeMPEG2_C ModeWMV9_C ModeVC1_C
szDescription	Intel(R) HD Graphics 530
szDeviceId	0x191B
szDeviceIdentifier	{D7B78E66-5A5B-11CF-F560-CF26BDC2DA35}
szDeviceName	\\.\DISPLAY1
szDisplayMemoryEnglish	8148 MB
szDisplayMemoryLocalized	8148 MB
szDisplayModeEnglish	1920 x 1080 (32 bit) (60Hz)
szDisplayModeLocalized	1920 x 1080 (32 bit) (60Hz)
szDriverAssemblyVersion	23.20.16.4973
szDriverAttributes	Final Retail
szDriverDateEnglish	28.02.2018 3:00:00
szDriverDateLocalized	2/28/2018 03:00:00
szDriverLanguageEnglish	English
szDriverLanguageLocalized	English
szDriverModelEnglish	WDDM 2.1
szDriverModelLocalized	WDDM 2.1
szDriverName	C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\ki126974.inf_amd64_9168fc04b8275db9\igd12umd64.dll
szDriverNodeStrongName	oem118.inf:5f63e5340a14bf6c:iSKLD_w10_DS:23.20.16.4973:pci\ven_8086&dev_191b&subsys_06df1028
szDriverSignDate	Unknown
szDriverVersion	23.20.0016.4973
szKeyDeviceID	Enum\PCI\VEN_8086&DEV_191B&SUBSYS_06DF1028&REV_06
szKeyDeviceKey	\Registry\Machine\System\CurrentControlSet\Control\Video\{9ECB1987-A280-11E9-9E5E-B9CF6FFDEA2B}\0000
szManufacturer	Intel Corporation
szMiniVdd	unknown
szMiniVddDateEnglish	Unknown
szMiniVddDateLocalized	unknown
szMonitorMaxRes	Unknown
szMonitorName	Generic PnP Monitor
szNotesEnglish	No problems found.
szNotesLocalized	No problems found.
szOverlayEnglish	Supported
szRankOfInstalledDriver	00D10001
szRegHelpText	Unknown
szRevision	Unknown
szRevisionId	0x0006
szSubSysId	0x06DF1028
szTestResultD3D7English	Not run
szTestResultD3D7Localized	Not run
szTestResultD3D8English	Not run
szTestResultD3D8Localized	Not run
szTestResultD3D9English	Not run
szTestResultD3D9Localized	Not run
szTestResultDDEnglish	Not run
szTestResultDDLocalized	Not run
szVdd	unknown
szVendorId	0x8086
Log Messages
GpuProcessHost: The unsandboxed GPU process exited normally. Everything is okay.
```


</p></details>

**Comment by habamax** [comment]
> Can you test again after turn off the Transparency effects? Thanks!


![image](https://user-images.githubusercontent.com/234774/82023628-3a443c80-9697-11ea-8e4d-797a648a124e.png)

**Comment by simonhong** [comment]
OK thanks for checking. I assume that win8 force its color to application header.

**Comment by habamax** [comment]
> 
> 
> OK thanks for checking. I assume that win8 force its color to application header or chromium doesn't handle properly.

But last screenshots were made without win8 compatibility...

**Comment by simonhong** [comment]
Oh, you're using win 10 and it has win 8 compatibility mode? I didn't know that mode.

**Comment by habamax** [comment]
> 
> 
> Oh, you're using win 10 and it has win 8 compatibility mode? I didn't know that mode.

Yes, and I set it because of nasty chrome/chromium bug that just made all chromium based application to crash including chrome itself.

**Comment by habamax** [comment]
And I have just install chrome to check:

![image](https://user-images.githubusercontent.com/234774/82024949-429d7700-9699-11ea-861a-dce9a9a468b8.png)

**Comment by simonhong** [comment]
I also can reproduce this issue with win8 compatible mode.
but It is fixed after running w/o comp. mode.

**Comment by simonhong** [comment]
Did you set comp. mode for all users?

**Comment by simonhong** [comment]
When I set win8 comp mode for all users, I also can see this issue every time.
but after rollback to non comp. mode for all users, I don't see this issue.

**Comment by habamax** [comment]
> 
> 
> Did you set comp. mode for all users?

It was just a shortcut where I set compatibility.

And looks like it was saved somewhere else: even though I have deleted that shortcut and run brave directly it still shows me Win8

![image](https://user-images.githubusercontent.com/234774/82025224-b2abfd00-9699-11ea-9c08-dc48f10807ef.png)

**Comment by simonhong** [comment]
I think you should make below comp.mode unchecked.
I assume your brave.exe still has checked..
![image](https://user-images.githubusercontent.com/6786187/82025357-2d8e0b80-96cc-11ea-92be-4e189c57064c.png)

**Comment by habamax** [comment]
Solved! Thanks @simonhong !

![image](https://user-images.githubusercontent.com/234774/82025510-1e8e6580-969a-11ea-8fd6-4ed086c59698.png)

**Comment by simonhong** [comment]
Great. Happy to help! 👍

**Comment by simonhong** [comment]
Can we close this issue? :)

**Comment by habamax** [comment]
I guess yes
