### ISSUE TITLE
Ads history will not be shown at all if there is an ad older than 7 days

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-browser#7743]
Found when testing https://github.com/brave/brave-browser/issues/5863
We show 7 day ads history, if there is an ad older than 7 days, the whole ads history will not be shown. This is a regression in 1.3.x.

Important: This issue is not reproducible on 1.2.x, 1.4.x, 1.5.x 
Important: Talked to @tmancey, and he said that this issue is fixed by https://github.com/brave/brave-browser/issues/6757

## Steps to Reproduce

   1. Clean install
   2. Enable rewards
   3. Open `brave://rewards`
   4. Close Brave
   5. Copy generated ads history file to `User Data\Default\ads_service\` (ask @btlechowski for the file)
   6. Launch Brave
   7. Reload `brave://rewards` few times

## Actual result:

`7-day Ads History` link is not shown at all on `brave://rewards`

## Expected result:
`7-day Ads History` link is shown
![image](https://user-images.githubusercontent.com/34715963/72478981-79e73e80-37f3-11ea-9806-14d0205c36f1.png)

## Reproduces how often: 

100% repro rate

## Brave version (brave://version info)

**Reproducible on**

Brave | 1.3.91 Chromium: 79.0.3945.117 (Official Build) beta (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

**Not reproducible on**

Brave | 1.5.36 Chromium: 79.0.3945.117 (Official Build) nightly (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

Brave | 1.4.60 Chromium: 79.0.3945.117 (Official Build) dev (64-bit)
-- | --
Revision | 04f0a055010adab4484f7497fbfdbf312c307f1d-refs/branch-heads/3945@{#1019}
OS | Windows 7 Service Pack 1 (Build 7601.24530)

## Version/Channel Information:

- Can you reproduce this issue with the current release? no
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the dev channel? no
- Can you reproduce this issue with the nightly channel? no

cc @brave/legacy_qa @rebron @tmancey @NejcZdovc

**Comment by tmancey** [comment]
Needs investigation to confirm if resolved by https://github.com/brave/brave-browser/issues/6757

**Comment by btlechowski** [comment]
@tmancey I think the `client.json` you provided will always be a false-positive as the oldest ad shares the `uuid` with other ad and therefor will never be shown.

**Comment by tmancey** [comment]
@btlechowski Re-checking now, thanks

**Comment by tmancey** [comment]
@btlechowski Tested with: And works as expected on both 1.3 and 1.5. Can you please send your client.json to show the issue. Thanks

[client.json.zip](https://github.com/brave/brave-browser/files/4096728/client.json.zip)

**1.5.x:**
<img width="1392" alt="1 5 x" src="https://user-images.githubusercontent.com/1188719/72889005-aa087300-3d06-11ea-9fab-c466eeac4201.png">

**1.3.x (not sorted as we only implemented sorting on 1.4 and above.):**
<img width="1312" alt="Screenshot 2020-01-22 at 11 00 00" src="https://user-images.githubusercontent.com/1188719/72889011-ad9bfa00-3d06-11ea-8a79-942b56a7bbb4.png">

**Comment by btlechowski** [comment]
The issue only reproduces on 1.3.x.

I still see duplicate `uuid` in the new client.json
![image](https://user-images.githubusercontent.com/34715963/72906388-72172500-3d32-11ea-9e17-3b8afb3d182d.png)

This is the file I use when the issue reproduces: [client.zip](https://github.com/brave/brave-browser/files/4097993/client.zip)
The file contains 8 ads, an ad is shown each day.
If I delete `Test Ad 001` (ad from 8th day), the history is shown

**Comment by tmancey** [comment]
@LaurenWags @btlechowski I have now reproduced the issue on 1.3. A decision needs to be made if we should uplift both #7869 and #6757 to resolve this issue

**Comment by LaurenWags** [comment]
cc @kjozwiak @rebron re: https://github.com/brave/brave-browser/issues/7743#issuecomment-578671946

**Comment by LaurenWags** [comment]
Closing issue as it was not reproduced in 1.4.x milestone by @btlechowski (original reporter) and it will not be fixed for 1.3.x.

Additionally, we will have to test #8046 with this issue.

**Comment by btlechowski** [comment]
Verification passed on

Brave | 1.4.85 Chromium: 80.0.3987.87 (Official Build) beta (64-bit)
-- | --
Revision | 449cb163497b70dbf98d389f54e38e85d4c59b43-refs/branch-heads/3987@{#801}
OS | Windows 7 Service Pack 1 (Build 7601.24544)

Verified steps from the description. File used: [client.zip](https://github.com/brave/brave-browser/files/4195141/client.zip)
It has 1000 ads, 10 ads per day. Only most recent ads are shown.
![image](https://user-images.githubusercontent.com/34715963/74379539-4561a500-4de8-11ea-8ed3-74c89a01939b.png)
