### ISSUE TITLE
Fix signature tor-client signature failure on macOS Catalina

### ISSUE THREAD

**Issue by jumde** [brave/brave-browser#7987]
![image](https://user-images.githubusercontent.com/1903815/73480491-d64b7180-434e-11ea-9e80-be3096808745.png)

**Comment by rebron** [comment]
cc: @mbacchi, @mihaiplesa

**Comment by btlechowski** [comment]
Many users complain that Tor stopped working for them.

https://community.brave.com/t/private-window-with-tor/104893

**Comment by denismp** [comment]
I am having the same issue on High Sierra.

**Comment by jumde** [comment]
Hi @denismp, we pushed an update to `Brave Tor Client Updater` crx.  Can you check if the issue is resolved for you? If not, can you try the following steps:

- Navigate to brave://components and check if the component version is 1.0.8 for `Brave Tor Client Updater (Mac)`.
- If yes, restart the browser and open `New Private Window with Tor`.
- If not, click `Check for Update`. It should update to v1.0.8
- Once updated, restart the browser and open `New Private Window with Tor`.

**Comment by denismp** [comment]
I clicked on Check for Update and it says "Component not updated".  So what do I do next?

**Comment by jumde** [comment]
Does it show `v1.0.8`? If so, can you try restarting the browser and opening a `Private window with Tor`?

**Comment by denismp** [comment]
I did, but is says the is no updated and Tor still does not work.

**Comment by jumde** [comment]
Thanks @denismp. Could you share a screenshot of the component list in `brave://components` and the error that you are seeing when you open `Private Windows with tor` to help us debug.

**Comment by Ajworry** [comment]
same problem here
brave: Verze 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
tor: v1.0.8

**Comment by denismp** [comment]
@jumde 
![2020-02-09_12-52-26](https://user-images.githubusercontent.com/2000960/74107187-8e410180-4b3b-11ea-94bc-075f0fc4a0c9.jpg)
![2020-02-09_12-52-51](https://user-images.githubusercontent.com/2000960/74107188-8ed99800-4b3b-11ea-8406-293dc8df91c9.jpg)

Sorry it took so long.

**Comment by jumde** [comment]
@denismp - Thanks for the screenshot. This helps. 

So you're not seeing the notarization error `tor cannot be opened because Apple cannot check it for malicious software` but you're not able to load any site in Tor? If so, can you please share any errors that you see in `/Users/<user-name>l/Library/Application Support/BraveSoftware/Brave-Browser/tor/data/tor.log`.

**Comment by jumde** [comment]
> same problem here
> brave: Verze 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
> tor: v1.0.8

Hi @Ajworry - which version of MacOS are you using? Could you share a screenshot of the error that you're seeing? Thanks!

**Comment by Ajworry** [comment]
high sierra 10.13.6

`Feb 03 20:06:00.000 [notice] Tor 0.3.5.8 opening new log file.
Feb 03 20:06:00.253 [notice] Tor 0.3.5.8 running on Darwin with Libevent 2.1.9-beta, OpenSSL 1.0.2q, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Feb 03 20:06:00.255 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 03 20:06:00.256 [notice] Configuration file "/nonexistent" not present, using reasonable defaults.
Feb 03 20:06:00.306 [notice] Opening Socks listener on 127.0.0.1:9350
Feb 03 20:06:00.306 [notice] Opened Socks listener on 127.0.0.1:9350
Feb 03 20:06:00.306 [notice] Opening Control listener on 127.0.0.1:0
Feb 03 20:06:00.306 [notice] Control listener listening on port 57130.
Feb 03 20:06:00.306 [notice] Opened Control listener on 127.0.0.1:0
Feb 03 20:06:00.000 [notice] Bootstrapped 0%: Starting
Feb 03 20:06:01.000 [notice] Starting with guard context "default"
Feb 03 20:06:01.000 [notice] Bootstrapped 5%: Connecting to directory server
Feb 03 20:06:02.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Feb 03 20:06:04.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Feb 03 20:06:04.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Feb 03 20:06:04.000 [notice] Bootstrapped 25%: Loading networkstatus consensus
Feb 03 20:06:08.000 [notice] Bootstrapped 45%: Asking for relay descriptors
Feb 03 20:06:08.000 [notice] I learned some more directory information, but not enough to build a circuit: We need more microdescriptors: we have 4448/6574, and can only build 27% of likely paths. (We have 76% of guards bw, 74% of midpoint bw, and 48% of exit bw = 27% of path bw.)
Feb 03 20:06:09.000 [notice] Bootstrapped 63%: Loading relay descriptors
Feb 03 20:06:18.000 [notice] Bootstrapped 71%: Loading relay descriptors
Feb 03 20:06:19.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Feb 03 20:06:19.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Feb 03 20:06:20.000 [notice] Bootstrapped 100%: Done
Feb 03 20:06:22.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:06:25.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:06:32.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:06:33.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:07:08.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:07:20.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:07:48.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:08:27.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:08:43.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:10:17.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:12:18.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:13:58.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:21:23.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:24:20.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:31:25.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:41:26.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 20:51:27.000 [notice] Have tried resolving or connecting to address '[scrubbed]' at 3 different places. Giving up.
Feb 03 21:01:09.000 [notice] Catching signal TERM, exiting cleanly.`

**Comment by riastradh-brave** [comment]
This is very strange.  Can you try loading https://check.torproject.org/ or https://www.example.com/ just to confirm we're connecting to the same things that are known to be up on the internet?

**Comment by Ajworry** [comment]
after update brave on 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit) Tor doesn't work

No internet
There is something wrong with the proxy server, or the address is incorrect.
Try:

Contacting the system admin
Checking the proxy address
ERR_PROXY_CONNECTION_FAILED

**Comment by jumde** [comment]
Hi @denismp , @Ajworry : We were able to reproduce the issue you are running into. Thanks for all your help. We are working on a fix, stay tuned! Thanks

**Comment by denismp** [comment]
Is there any further update on this?

**Comment by jumde** [comment]
Hi @denismp, we are actively working on this. Sorry for the delay here. We are running into compatibility issues with older versions of macos. We should have a fix soon.

**Comment by eDave56** [comment]
Please be aware that this isn't just a macOS problem; Windows users are also experiencing it. While I haven't had the problem on either platform for weeks, there are still ongoing problems as seen here:
https://community.brave.com/t/private-window-with-tor/104893/44?u=hnktong

and people are getting frustrated. An update from the devs would be good. I'll post a link to @jumde 's comment of 4 days ago.

**Comment by jumde** [comment]
@denismp @Ajworry @eDave56 - We just released an update of the extension, could you please try these steps:

1. Navigate to brave://components and check if the version of Tor Client Updater is 1.0.9
2. Open New Private window with Tor and check if you can open check.torproject.org

Let me know if you're still running into any issues.

**Comment by Ajworry** [comment]
@denismp thanks working

**Comment by jumde** [comment]
Please re-open if you are still seeing issues.

**Comment by oleyka** [comment]
Looks like the same issue is back again:

* OS X Catalina 10.15.6
* Brave Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)
* tor-0.3.5.11-darwin-brave-0

**Comment by fco-pires** [comment]
I am having this issue with brave on MacOS Monterrey. Yesterday it was working fine, but now when I open a private window with Tor it shows a popup saying “tor-0.4.6.10-darwin-brave-0” can't be opened because apple cannot check it for malicious software.

- OS X Moterrey 12.3.1
- Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)
- tor-0.4.6.10-darwin-brave-0
- Tor client updater 1.0.25

**Comment by eDave56** [comment]
Not observed with two Intel Macs:
```
Brave 1.39.70 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64) on macOS Version 10.14.6 (Build 18G9323)

Brave 1.39.18 Chromium: 100.0.4896.60 (Official Build) nightly (x86_64) on macOS Version 12.3.1 (Build 21E258)
```

I then ran the updater on the 12.3.1 machine and had no problem with:
```
Brave 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64) still on macOS Version 12.3.1 (Build 21E258)
```

**Comment by eDave56** [comment]
I realized that I was only testing Nightly, so I updated and tested Release. No problem on the 10.14.6 machine, but the 12.3.1 update kept sitting and spinning. I quit Brave on that machine, copied the updated app from the 10.14.6 machine, launched, and Tor connected successfully (I tested a couple of websites to be sure).

Here are Tor, Brave, and macOS version information for completeness:
```
Tor Version: 0.4.6.10
Tor Process Id: 15160
Tor Proxy URI: socks5://127.0.0.1:50952
Tor Connection Status: Connected
Tor Initialization Progress:
-
Brave 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64) on macOS Version 10.14.6 (Build 18G9323)
```

and
```
Tor Version: 0.4.6.10
Tor Process Id: 16728
Tor Proxy URI: socks5://127.0.0.1:54388
Tor Connection Status: Connected
Tor Initialization Progress:
-
Brave 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64) on macOS Version 12.3.1 (Build 21E258)
```

**Comment by fco-pires** [comment]
> @fco-pires do you have an M1 or Intel macOS? If you're not sure, can you go to brave://version and copy the first 3 lines and paste them here please?

It's an Intel Mac.

Anyway, here are the 3 lines:

Brave | 1.37.116 Chromium: 100.0.4896.127 (Versão oficial) (x86_64)
-- | --
Revisão | ff0d0695743e65305d7194f9bd309e5e1c824aa0-refs/branch-heads/4896_88@{#4}
SO | macOS Versão 12.3.1 (Compilação 21E258)

**Comment by eDave56** [comment]
Here's a weird thing: even though both machines' Release Braves and the 12.3.1 machine's Nightly use tor 0.4.6.10, the 10.14.6 machine's *Nightly* uses tor 0.4.6.9  even after updating it to Brave 1.39.73 Chromium: 101.0.4951.34 (Official Build) nightly (x86_64).

**Comment by fco-pires** [comment]
I tried uninstalling and reinstalling Brave and now it's working again. I really don't know what caused this issue, as it was working yesterday and began to show the popup today.
