### ISSUE TITLE
Update Ben Karpinski's photo attribution link from Fall 2019 wallpapers

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-browser#7997]
### Description: 
Currently, Ben Karpinski's photo attribution link is set as [www.benkarpinski.com/landscapes](url). He has requested that we update it to [http://bklandscapes.com/](url). His image is included in the Fall 2019 batch of new wallpapers.

![Screen Shot 2020-01-31 at 11 34 54 AM](https://user-images.githubusercontent.com/2388823/73569918-3cec9000-4420-11ea-946f-1223654de42f.png)

## Test plan
1. Load picture (thumbnail shown above)
2. Make sure image is attributed properly to Bren Karpinski

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` for now since https://github.com/brave/brave-core/pull/4398 was reverted.

**Comment by bsclifton** [comment]
@LaurenWags it should be there actually- I did open a revert, but we fixed a different way 😄 Let me make a note there (my bad)

Comment left https://github.com/brave/brave-core/pull/4398#issuecomment-601426627 😄 Removing `QA/Blocked` label

**Comment by LaurenWags** [comment]
Verified using 

Brave | 1.7.71 Chromium: 80.0.3987.149 (Official Build) dev (64-bit)
-- | --
Revision | 5f4eb224680e5d7dca88504586e9fd951840cac6-refs/branch-heads/3987_137@{#16}
OS | macOS Version 10.14.6 (Build 18G3020)

Issue from description still reproduces. When Ben Karpinski's image is shown, his image is still attributed to `https://benkarpinski.com/landscapes/` not `http://bklandscapes.com/` as mentioned in the description.

Logged follow up issue https://github.com/brave/brave-browser/issues/8831

**Comment by bsclifton** [comment]
removing `QA/Yes` and milestone as https://github.com/brave/brave-browser/issues/8831 is a duplicate of this issue
