### ISSUE TITLE
Frequent intermittent hanging when HW acceleration is enabled

### ISSUE THREAD

**Issue by aaronovz1** [brave/brave-browser#9824]
## Description 

Hardware acceleration causes intermittent freezing of the browser. The browser locks up for a few seconds while opening new tabs and loading new pages. Each time the lock up occurs there is a message printed in the Xorg log:

`nvLock: client timed out, taking the lock`

## Steps to Reproduce

   1. Open new tabs, browse new pages

## Actual result:

Freezing

## Expected result:
No freezing with HW acceleration enabled

## Reproduces how often: 

Easily reproducible

## Brave version (brave://version info)

Brave | 1.8.96 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
-- | --
Revision | 8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}
OS | Linux
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Command Line | /opt/brave.com/brave/brave --enable-dom-distiller --disable-domain-reliability --no-pings --extension-content-verification=enforce_strict --extensions-install-verification=enforce --sync-url=https://no-thanks.invalid --enable-features=PasswordImport,WebUIDarkMode,AutoupgradeMixedContent,PassiveMixedContentWarning,MixedContentSiteSetting,SimplifyHttpsIndicator,DnsOverHttps --disable-features=AutofillServerCommunication,TextFragmentAnchor,AllowPopupsDuringPageUnload,LookalikeUrlNavigationSuggestionsUI,SmsReceiver,AudioServiceOutOfProcess,NotificationTriggers,VideoPlaybackQuality --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --disable-sync
Executable Path | /opt/brave.com/brave/brave
Profile Path | /home/user/.config/BraveSoftware/Brave-Browser/Default

## Version/Channel Information:

- Can you reproduce this issue with the current release? Yes
- Can you reproduce this issue with the beta channel? Haven't tried
- Can you reproduce this issue with the dev channel? Haven't tried
- Can you reproduce this issue with the nightly channel? Haven't tried

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No
- Does the issue resolve itself when disabling Brave Rewards? No
- Is the issue reproducible on the latest version of Chrome? Not sure

## Miscellaneous Information:

OS: Ubuntu Mate 20.04
Kernel: 5.6
GFX: nVidia Quadro P1000 (driver version 440)

**Comment by Martina-Neumayer** [comment]
I am using the beta channel AUR releases on Arch linux. 

In my case is almost that same as mentioned above with one "extra" thing.. those missing libraries at the beginning of the entire issue.

After some checks, I think (I'm not 100% sure) the released here on github beta package is somehow broken.

There's completely no clue about this problem in the pkgbuild itself. Pkgbuild is as usual, identical to the previous versions.

So.. the main question here is (as I mentioned before in the report: #11412): why the browser looks for libs in their own directories instead of using the default system ones?

After manually adding all needed libraries, no matter if I copy them or just simlink, HW works but only for some short time period.

Circa 30 min, and after that Brave begin to lag, choking itself,  scroll jumping, freezing, screen glitching etc.

The first symptom is the video playback which began totally unusable due to the big a/v desync. If I exit the full screen mode on YouTube then entire browser screen turns black and only what I can do is to kill brave proces from the Arch task manager or force reboot the entire machine. 

At this point brave is completely unresponsive, it can't be minimized, closed and so on, cpu and gpu usage goes to the maximum and the laptop fans are starting to howl like crazy.

I tried the actual stable branch version also but on my latest kernel 5.8.5-arch1-1 it is segfaulting and force-closing at the moment of starting.

Downgrading the beta to the previous version helps, there are no issues with it at all.

**Comment by hugobuddel** [comment]
Not sure whether this is related. Brave does not crash with hardware acceleration, but it does break within half an hour of usage by turning most of the user interface black.

![bravehwblack](https://user-images.githubusercontent.com/1306453/91661898-25bd7000-eadf-11ea-82d0-13da80525559.png)

Version 1.14.65 Chromium: 85.0.4183.83 (Official Build) beta (64-bit)

For now I have fixed this simply by turning hardware acceleration off. Haven't investigated much further, and everything seems smooth enough without HW acceleration, so I'll keep it off for now.

**Comment by Martina-Neumayer** [comment]
Update..
Brave updated to the 1.14.73 Chromium: 85.0.4183.83 version and the HW problem still there.
Yet again there are messages about missing libraries in the brave://gpu panel.
In other words, nothing has changed from the previous HW issue report.
https://pastebin.com/rJuJrZRR

**Comment by howdev** [comment]
@hugobuddel Is not smooth even with hardware acceleration off. The google maps will be very slow. It is only lagging in my experience when Vulkan experimental flag is enabled. The Vulkan runs webgl much faster

**Comment by Srijan1214** [comment]
I have the same issue here on the arch. However, I do not get the "nvLock ..." Xorg log.

**Comment by Sahasrara** [comment]
I think this may be related to a bug I filed here for the chromium project:
https://issues.chromium.org/issues/429538661

**Comment by bsclifton** [comment]
Huge thanks @Sahasrara for filing that! We can use that issue to track this particular issue

It looks like the team has helped and the problem occurs a lot less for you now. I starred the issue and will keep an eye on it 😄
